### ISSUE TITLE
Error when plotting with greater than 9 clusters

### ISSUE THREAD

**Issue by zoesteier** [statOmics/tradeSeq#10]
I would like to plot the knots for my data that contains 10 clusters, but the built in palette only allows for 9 colors, so I get the following error when trying to use plotGeneCount:

n too large, allowed maximum for palette Set1 is 9. Returning the palette you asked for with that many colors

Can you please allow for the input of a color palette that isn't limited by "Set1" (e.g. brewer.paired())?

**Comment by HectorRDB** [comment]
Hi,
If you install the newest version of tradeSeq, the plotGeneCount function will have change and you should be able to use 10 clusters or more.

**Comment by zoesteier** [comment]
The newest version of tradeSeq has resolved this issue. Thanks!
