### ISSUE TITLE
Extract only certain pseudotime values from monocle

### ISSUE THREAD

**Issue by huanz4** [statOmics/tradeSeq#101]
Thanks for making and maintaining such useful tool!!

I extracted pseudotime values from monocle but only included cells with pseudotime values greater than 0.1.
I am going to cluster genes expression for these cells. Does it matter if I don't have a start pseudotime, which is 0, I assume?

Sorry, I am new to coding and also to single cell seq analysis. I can provide more information if my question wasn't clear.

**Comment by koenvandenberge** [comment]
Hi @huanz4 

Thanks for your interest in using `tradeSeq`.
For some of the DE test functions like the `patternTest` we do assume the starting point to be more or less around a pseudotime of 0. If `0.1` is your lowest pseudotime you could always for example subtract `0.1` from all pseudotime values.

**Comment by huanz4** [comment]
Hi Koen,

Thanks for the suggestion! 
I will definitely try it out when I encounter these functions.
Have a nice day!

Best,
Huan
