### ISSUE TITLE
P-value from DE analysis outputs

### ISSUE THREAD

**Issue by mvis1231** [statOmics/tradeSeq#102]
Hi,
I have a quick question about the p-values from associationTest, startVsEndTest, and diffEndTest.

Are the p-values the adjusted p-values? If so, Bonferroni correction was used or something else?
If the p-values are not adjusted, are the users supposed to adjust the p-values?

Thank you so much for your response and time in advance!

**Comment by koenvandenberge** [comment]
Hi @mvis1231 

The p-values returned by all tests are 'raw' p-values and no form of multiple testing correction has been applied yet. 
We indeed recommend the users to adjust the p-values for multiple testing, see for example the `p.adjust` function.
