### ISSUE TITLE
diffEndTest and pattern test issues

### ISSUE THREAD

**Issue by ark2173** [statOmics/tradeSeq#103]
Hi! I'm having issues with both the diffendtest and the patterntest. My sample has 4 lineages that I want to compare. However, when I use the "pairwise" argument, both tests fail with the following error:

![Screen Shot 2020-12-20 at 8 55 31 PM](https://user-images.githubusercontent.com/48217584/102731391-b5449400-4305-11eb-821a-134cf34e8560.png)

Is there any work around for this error? Thanks!

**Comment by koenvandenberge** [comment]
Hi @ark2173 

Apologies for the slow response. 
Could you let us know what version of `tradeSeq` you are using and if possible provide a reproducible example so we can look into it?

Thanks,
Koen

**Comment by ark2173** [comment]
Hi! uninstalling and reinstalling seemed to work for me
