### ISSUE TITLE
Analysis following fitGAM-  Error in xy.coords(x, y, setLab = FALSE) : 'list' object cannot be coerced to type 'integer

### ISSUE THREAD

**Issue by scideas** [statOmics/tradeSeq#105]
Dear TradeSeq team,

I was optimistic about this package after obtaining some underwhelming results from monocle3.
Initially, I wasn't able to get the fitGAM function to work, but after installing the latest github version, the fitGAM function finally ran to completion. Now, I was able to run the associationTest () function just fine, using my slingshot singleCellExperiment object that tradeseq analysis was added to, but for some reason, I keep getting an error every time I try running any of the subsequent analysis steps: 

**Here are the portions of the code that have worked:** 
sce <- fitGAM(counts = sce, nknots=9, verbose=T , parallel=TRUE, BPPARAM = BPPARAM )
ATres2 <- associationTest(sce)

**Next when I try running the following line:** 
startRes <- startVsEndTest(models = sce)

**I obtain the following error message:**
"Error in xy.coords(x, y, setLab = FALSE) : 'list' object cannot be coerced to type 'integer'"

Is there anything obvious that I'm doing wrong here? I can't find a rowdata slot in my singlecellexperiment object, but all of the other coldata and metadata slots are present.

I checked out the documentation for the startVsEndTest() and other functions used in the vignette but wasn't able to figure out whats going on based on the information that is provided. 

sessionInfo()
 R version 4.0.2 (2020-06-22)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows Server >= 2012 x64 (build 9200)

Matrix products: default

Random number generation:
 RNG:     Mersenne-Twister 
 Normal:  Inversion 
 Sample:  Rounding 

attached base packages:
 [1] splines   parallel  stats4    stats     graphics  grDevices utils     datasets  methods  
[10] base     

other attached packages:
 [1] dplyr_1.0.2                 stringr_1.4.0               readxl_1.3.1               
 [4] SeuratWrappers_0.3.0        monocle_2.18.0              DDRTree_0.1.5              
 [7] irlba_2.3.3                 VGAM_1.1-4                  Matrix_1.2-18              
[10] Seurat_3.2.2                ggplot2_3.3.2               slingshot_1.8.0            
[13] princurve_2.1.5             RColorBrewer_1.1-2          tradeSeq_1.3.23            
[16] SingleCellExperiment_1.12.0 SummarizedExperiment_1.20.0 Biobase_2.50.0             
[19] GenomicRanges_1.42.0        GenomeInfoDb_1.26.1         IRanges_2.24.0             
[22] S4Vectors_0.28.0            BiocGenerics_0.36.0         MatrixGenerics_1.2.0       
[25] matrixStats_0.57.0         

Thanks for your help, and Merry Christmas/Happy New Year!

**Comment by koenvandenberge** [comment]
Hi @scideas 

Apologies for the slow response. 
Could you let us know what version of `tradeSeq` you are using and if possible provide a reproducible example so we can look into it? tradeSeq doesn't seem to be included in your session info.

Thanks,
Koen

**Comment by scideas** [comment]
Hey Koen, 

I didn't realize markdown had a completely different sessionInfo() running, so I updated the original posting to show some of the actual packages that were used.
To answer your questions, I was running **tradeSeq_1.3.23**  following the use of slingshot_1.8.0. 

As I was putting together a reproducible example, I noticed the function actually works fine when using the simulated dataset generated by the slingshot demo, so I'm wondering if there is some sort of issue with the singlecellexperiment object I'm using, which was converted over from Seurat after initial processing. 

Would you be willing to take a look at my SingleCellExperiment object, which I processed through slingshot and tradeseq? perhaps there is something obvious you'll be able to detect with the sample. It's only ~200Mb, but could I pm the link to you? Let me know what email I should use.  

Thanks for your help,
Aaron

**Comment by HectorRDB** [comment]
Hi @scideas, 
i can help with that issue. Please email you data at hector dot rouxdebezieux at berkeley dot edu. 
Best

**Comment by scideas** [comment]
Email sent- thanks, Hector

**Comment by HectorRDB** [comment]
Hi @scideas 
I have received your email. I pinpointed the issue: there is a bug in the code such that is fails when there is 10 or more lineages present. This is clearly a bug in our side and I will work to fix it (and update you when this is done). 
Having just a subset of the data, it is hard to judge but just note that, in our experience, it is rare for that many lineages to be meaningful, i.e. to really represent true biological processes. I would advice that you take a careful look at those lineages to make sure they are indeed real.

**Comment by HectorRDB** [comment]
Hi @scideas 
The latest commit should have fixed the issue. Please use the latest `tradeSeq` version from github using
```
devtools::install_github("statOmics/tradeSeq")
```
and let me know if that fixes that bugs. 
Best

**Comment by HectorRDB** [comment]
@koenvandenberge 
I think I fix all those problems but if you have time, could you review the latest [commit](https://github.com/statOmics/tradeSeq/commit/e1ba81b3934dc0391cdf5667baa60305ee7c5c4f) and check I have not missed anything... 
Thanks

**Comment by HectorRDB** [comment]
Update: my first fix had a lot of bugs but it now seems to be working correctly

**Comment by scideas** [comment]
Thanks, Hector- I will give it a shot and let you know how it goes

**Comment by scideas** [comment]
Update: 
I was able to get that function to run- thanks! However, I got hung up in a subsequent step: 

counts <- counts(sce)
sigGeneStart <- names(sim)[oStart[4]]
plotSmoothers(sim, counts, gene = sigGeneStart)
plotGeneCount(sim, counts, gene = sigGeneStart)

The Error traceback I encountered happened during plotSmoothers(), saying that the matrix was 'NULL':
![image](https://user-images.githubusercontent.com/48698173/103857803-d2ef5880-507c-11eb-9d23-e8987af29148.png)

I can attest that the pseudotime matrix isn't null. Here is a small snapshot from that matrix: 
![image](https://user-images.githubusercontent.com/48698173/103857967-19dd4e00-507d-11eb-9082-9268fc219576.png)

The counts matrix is also not empty: 
![image](https://user-images.githubusercontent.com/48698173/103858481-07174900-507e-11eb-8465-4dfa4d1aeeca.png)


I tried entering the pseudotime matrix directly into the function, just to check what happened, and the function didn't like that...

The genes being selected in the above function are also not empty vectors, so I'm at a loss for what's going on here. 

The only thing that could potentially be screwing this up is that I hadn't saved my downsampled Seurat object before having to reinstall tradeseq and restart R, but I set a seed beforehand, so I think the matrix should be identical to the object used for tradeseq analysis. Just wanted to throw that in as a possibility. 

Thanks again for your help

**Comment by HectorRDB** [comment]
Hi @scideas 
Could you tell me what the `sim` object is? Is this the output from slingshot or from the `fitGAM` function?

**Comment by scideas** [comment]
Yes, it is a slingshot object that contains the output from fitGAM. It’s the same as the file I sent Hector. 

Thanks,
Aaron

**Comment by scideas** [comment]
Hey @HectorRDB, I'm sure you've got plenty on your plate, but I was curious whether you'd been able to look further into issue I ran into with plotSmoothers? The odd issue I had with the input vector showing that the pseudotime matrix input. 

I can resend the slingshot+tradeSeq object via email if you'd like. So close to the finish line, but disappointed I can't get to the best part after getting everything else working!

Thank you very much,
Aaron

**Comment by HectorRDB** [comment]
Hi @scideas 
Indeed it's a bit packed but I should have some time on Friday
Best

**Comment by HectorRDB** [comment]
HI @scideas,
I cannot reproduce the issue with your data. Could you let me know what `sigGeneStart`. Specifically, can you confirm that it is only one gene? 
Thanks

**Comment by scideas** [comment]
Hey @HectorRDB Thanks for looking into this. You actually inadvertently solved my problem! It is indeed working now! I must've modified my SingleCellExperiment object in some way prior to running that function, because after I reloaded the object I sent you it actually worked like a charm. Thank you so much for resolving this issue- time for me to start digging into all the goldmine of data now! :P
All the best,
Aaron
