### ISSUE TITLE
output of predictCells and predictSmooth

### ISSUE THREAD

**Issue by adamgayoso** [statOmics/tradeSeq#107]
Hello,

I'm curious about the output of the gam predictions.

1. For predictCells, does this provide \eta as defined in the manuscript?
![Screen Shot 2021-01-04 at 10 02 59 AM](https://user-images.githubusercontent.com/10859440/103564807-08752580-4e74-11eb-8814-101023fc984c.png)

2. For predictSmooth, is this just \eta without the addition of the observed covariates/offset (and at a range of pseudotime points)? So in some sense, predictSmooth is "corrected" for this variation?

**Comment by HectorRDB** [comment]
Hey @adamgayoso 
Thanks for this comment. That is correct for the `predictCells` function. 
For `predictSmooth`, this is \eta using the same observed covariates and offset for all points. For now, we use the values of the first cell, although I now realize it may not be the best way to do it. 

In practice, we do not use `predictCells` a lot but `predictSmooth` allows to do clustering of gene patterns and can produce much nicer heatmaps than using the logcounts (see for example [this](https://kstreet13.github.io/bioc2020trajectories/articles/workshopTrajectories.html#visualization-of-de-genes))
Let me know it that helps.
Best

**Comment by adamgayoso** [comment]
Yes I'd like to use `predictSmooth` for clustering gene patterns -- just wanted to make sure I understood it. 

It might be helpful to provide the option to return just the pseudotime component for `predictSmooth`. Or at least make more clear in the documentation what it outputs in the notation of your manuscript.

Thanks!

**Comment by HectorRDB** [comment]
If you want to do clustering, I would recommend scaling after running `predictSmooth`. You might also find the the `clusterExpressionPatterns` function useful. It relies on the clusterExperiment package and clusters on the output of `predictSmooth`, after centering and scaling to have a variance of 1. 

I will update the documentation, thanks for the advice
