### ISSUE TITLE
heatmap using one lineage

### ISSUE THREAD

**Issue by guillemsanchezsanchez1996** [statOmics/tradeSeq#111]
Dear all,
Thank you for this fantastic package, I have tried different strategies for lineage tracing but your tool is extremely useful and straightforward to use.

I've been following your useful code posted here --> [https://kstreet13.github.io/bioc2020trajectories/articles/workshopTrajectories.html#visualization-of-de-genes]
to analyse my own dataset. Regarding your DGE heatmap code... I'm a little bit confused as my dataset includes 3 lineages  so when I plot it, it's difficult to understand which genes define the trajectory of a particular lineage;
![image](https://user-images.githubusercontent.com/59885051/104346040-40790a00-54ff-11eb-9937-615e1d1b94d9.png)

Do you know how can I plot just a single lineage?

Thanks in advance,

Guillem

**Comment by koenvandenberge** [comment]
Hi @guillemsanchezsanchez1996 

Thanks for your interest, and for your feedback on the workshop!

The `predictSmooth` function you are referring to returns a matrix, with genes in the rows and a grid of estimated smoother values in the columns. Note that the name of each column should tell you the lineage and the grid point. In your case, based on the column names of your heatmap, it indeed looks like you have three lineages, and you only selected the first 50 columns, but you should have 150 columns (3 lineages * 50 grid points per lineage) if you've followed the workshop code with your own dataset.

So you can sort or subset the columns in any order you like to give you a heatmap across lineages or for a single lineage.
Alternatively, you can also set the argument `tidy=TRUE` in `predictSmooth` which will give you a tidy data frame you can use for plotting with e.g. `ggplot2`.

Hope this helps.

**Comment by guillemsanchezsanchez1996** [comment]
> Hi @guillemsanchezsanchez1996
> 
> Thanks for your interest, and for your feedback on the workshop!
> 
> The `predictSmooth` function you are referring to returns a matrix, with genes in the rows and a grid of estimated smoother values in the columns. Note that the name of each column should tell you the lineage and the grid point. In your case, based on the column names of your heatmap, it indeed looks like you have three lineages, and you only selected the first 50 columns, but you should have 150 columns (3 lineages * 50 grid points per lineage) if you've followed the workshop code with your own dataset.
> 
> So you can sort or subset the columns in any order you like to give you a heatmap across lineages or for a single lineage.
> Alternatively, you can also set the argument `tidy=TRUE` in `predictSmooth` which will give you a tidy data frame you can use for plotting with e.g. `ggplot2`.
> 
> Hope this helps.

aaaaaaaaja! yes it helped a lot!! The main problem was the 3x50 grid points....sometimes one gets stuck with the most trivial things......now the heatmap looks nice :) 

![image](https://user-images.githubusercontent.com/59885051/104435539-ce4f0680-558c-11eb-8d19-65328815f5d1.png)

thanks a lot for your quick response,

Guillem
