### ISSUE TITLE
fitGAM: Error in .local(counts, ...) : unused argument (conditions = NULL)

### ISSUE THREAD

**Issue by sarahpenir** [statOmics/tradeSeq#112]
First of all, thank you for this tool!

I am running an updated version of tradeSeq `(v 1.4.0)`. The function `evaluateK` works with an `sce` object. However, the `fitGAM` function throws the following error on an `sce` object:

`GAM <- fitGAM(sce, nknots = 6, parallel=TRUE, BPPARAM = BPPARAM, verbose = TRUE)`
 `Error in .local(counts, ...) : unused argument (conditions = NULL)`

If I do a workaround, such that I obtain the count matrix and the slingshot dataset separately and feed them to the `fitGAM` function, the process proceeds successfully and as usual:

`countMatrix <- as.matrix(assay(sce, "counts"))`
`slingshot <- SlingshotDataSet(sce)`
`GAM <- fitGAM(counts = countMatrix, sds = crv, nknots = 6, parallel=TRUE, BPPARAM = BPPARAM, verbose = TRUE)`

What could be causing this? Thank you!

**Comment by HectorRDB** [comment]
Hi @sarahpenir ,
Can you try re-installing from github to see if this fixes the issue? 
Best,

**Comment by sarahpenir** [comment]
Thanks, it is working now!
