### ISSUE TITLE
plotSmoothers: pointCol not coloring cells according to passed variable + border = TRUE only returns the smoother in white

### ISSUE THREAD

**Issue by sarahpenir** [statOmics/tradeSeq#114]
Good day! I am using the latest version of the package in Github (just updated today). 

When using `plotSmoothers` with an `sce` object, I noticed that it doesn't color the cells according to the variable passed to `pointCol` but is stored in the `$data` slot of the resulting `ggplot` object as `pCol`. I suspect it's missing `aes(color = pCol)` in the `geom_point` argument? But this can be remedied by adding a `geom_point` layer on top of the `plotSmoothers` result. 

Moreover, when setting `border = TRUE`, the plot only returns the smoother colored in white and not the second layer of the smoother colored according to the vector passed in `curvesCols` (thanks for this new feature!). Otherwise, it works really great when `border = FALSE`. Maybe the second `geom_line` corresponding to the colored smoothers is potentially not being printed properly?

Thank you again for this wonderful tool!

**Comment by koenvandenberge** [comment]
Hi @sarahpenir,

Thanks very much for picking this up and pointing it out; both issues should have been fixed now if you install the latest version.

Best,
Koen

**Comment by HectorRDB** [comment]
Haha @koenvandenberge we should have coordinated :)
Made a small change that is more ggplot friendly :)

**Comment by sarahpenir** [comment]
Thank you so much for working on this quickly! Can confirm that it's working now :)

All the best,
Sarah
