### ISSUE TITLE
AssociationTest returns NA

### ISSUE THREAD

**Issue by HectorRDB** [statOmics/tradeSeq#117]
The output of `associationTest` returns NA for all columns expect for the meanLogFC. The error does not appear on the website, suggesting it might be due to local package incompatibility. 
@koenvandenberge Do you have the same issue?

**Comment by koenvandenberge** [comment]
Thanks for spotting! This was because, when using the new contrasts, inverting the variance-covariance matrix the way we used to do it (using `qr.solve`) fails. Inverting via Cholesky decomposition is now the default.

**Comment by HectorRDB** [comment]
That dit it. Thanks!!

**Comment by teekhout** [comment]
Hi,
I'm also getting NA as output for all columns except meanLogFC. I followed the tutorial for multiple conditions, using `rowData(sce)$assocRes <- associationTest(sce, lineages = TRUE, l2fc = log2(2))`
I tried removing the l2fc parameter and even the lineages-parameter, but output remained NA for all columns. 
Any idea what could be the problem?

Thanks for the help!

**Comment by koenvandenberge** [comment]
Hi @teekhout , what's the `tradeSeq` version you're working with?

**Comment by teekhout** [comment]
I recently installed from github, so it should be the most recent version I guess.
sessionInfo() says tradeSeq_1.5.16

**Comment by koenvandenberge** [comment]
Hi @teekhout,

Thank you for reporting, and our apologies for the inconvenience. This was related to recent developments in extending the`associationTest` to multiple contrast types (see the `contrastType` argument) as well as across conditions.
I believe this has now been fixed, please let me know if issues still persist.

**Comment by YingxinLin** [comment]
Hi,

I also got NA values for some genes from association test using all default setting. I tried to set contrastType to different parameters, but still exist some NA values in the results. Are some of these NA to be expected? My tradeSeq package version is 1.7.02.

Yingxin

**Comment by koenvandenberge** [comment]
Hi @YingxinLin ,

Thanks for reaching out. For some genes, it is hard to calculate the variance-covariance matrix of the contrasts, and in those cases we may return `NA` values. This sometimes happens with genes that for example are barely expressed except for a few cells. If you're only having a couple of `NA` values, it should be fine.
