### ISSUE TITLE
fitGAM for sample using Hashing (HTO)

### ISSUE THREAD

**Issue by Roedani** [statOmics/tradeSeq#118]
Dear @koenvandenberge,

Sorry for asking another help, but I am using a new data set, which I have hashing samples and I was able to perform the differential expression and evaluateK. 
<img width="231" alt="Screen Shot 2021-02-01 at 11 16 01 AM" src="https://user-images.githubusercontent.com/74432483/106485682-e07edf00-647e-11eb-9e9f-c04f14a8943f.png">
<img width="667" alt="Screen Shot 2021-02-01 at 11 16 51 AM" src="https://user-images.githubusercontent.com/74432483/106485801-fd1b1700-647e-11eb-9b83-dcbd20a9af1e.png">

But when I tried to perform the fitGAM I got this error 
Error in .local(counts, ...) : 
  unused argument (conditions = c(4, 1, 3, 1, 4, 4, 4, 3, 1, 3, 1, 3, 1, 1, 1, 1, 3, 4, 4, 3, 1, 3, 4, 1, 3, 3, 1, 3, 1, 3, 3, 3, 3, 3, 3, 3, 1, 3, 4, 1, 3, 4, 1, 3, 3, 4, 3, 4, 3, 3, 1, 3, 3, 3, 3, 3, 3, 1, 3, 3, 3, 1, 3, 1, 2, 3, 1, 1, 1, 3, 3, 3, 4, 3, 1, 3, 3, 3, 3, 1, 4, 3, 1, 3, 3, 1, 3, 3, 3, 3, 1, 3, 3, 3, 1, 3, 3, 3, 3, 3, 3, 1, 3, 3, 1, 3, 3, 1, 1, 3, 1, 3, 3, 4, 3, 1, 1, 3, 3, 4, 4, 1, 3, 4, 3, 1, 3, 3, 1, 4, 3, 1, 3, 4, 1, 3, 4, 4, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 2, 3, 3, 4, 3, 1, 1, 1, 3, 3, 4, 
1, 1, 3, 4, 1, 3, 3, 4, 3, 3, 1, 1, 1, 3, 3, 1, 3, 4, 1, 3, 3, 3, 3, 1, 1, 3, 1, 4, 1, 4, 3, 1, 3, 3, 1, 1, 1, 1, 3, 3, 3, 1, 3, 1, 1, 4, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 1, 4, 3, 3, 3, 4, 3, 3, 1, 3, 3, 3, 3, 1, 3, 1, 3, 1, 3, 3, 1, 1, 3, 3, 3, 1, 3, 3, 1, 1, 3, 3, 1, 3, 1, 3, 3, 3, 3, 3, 3, 4, 4, 4, 3, 3, 1, 3, 1, 3, 3, 3, 1, 3, 1, 1, 4, 3, 3, 3, 1, 1, 3, 4, 3, 3, 3, 3, 4, 3, 3, 1, 3, 1, 3, 1, 1, 4, 3, 3, 1, 3, 3, 3, 4, 1, 3, 1, 3, 3, 3, 3, 3, 1, 3, 3, 1, 3, 3, 3, 4, 3, 3, 3, 

this is my evaluateK
set.seed(3)
icMat <- evaluateK(counts = sce_1,
                   conditions = factor(colData(sce_1)$HTO_classification),
                   nGenes = 300,
                   k = 3:7)

this is my fitGAM
sce_1 <- fitGAM(counts = sce_1,
             conditions = factor(colData(sce_1)$HTO_classification),
              nknots = 5)

> print(sce_1)
class: SingleCellExperiment 
dim: 32285 1321 
metadata(0):
assays(2): counts logcounts
rownames(32285): Xkr4 Gm1992 ... AC234645.1 AC149090.1
rowData names(9): mvp.mean mvp.dispersion ... vst.variance.standardized
  vst.variable
colnames(1321): sample1_AAACCCATCAAAGACA-1 sample1_AAACCCATCCCAGGAC-1 ...
  sample2_TTTGATCTCATCTATC-1 sample2_TTTGGAGCAGGCCTGT-1
colData names(17): orig.ident nCount_RNA ... slingClusters
  slingPseudotime_1
reducedDimNames(2): PCA UMAP
altExpNames(0):

> print(SlingshotDataSet(sce_1))
class: SlingshotDataSet 

 Samples Dimensions
    1321          2

lineages: 1 
Lineage1: mHTO06  mHTO04  mHTO02  mHTO03  

curves: 1 
Curve1: Length: 19.857	Samples: 1321

Thank you very much,
Rodrigo

**Comment by koenvandenberge** [comment]
Hi Rodrigo,

Based on the `fitGAM` error it looks like you are working with a version of `tradeSeq` that has not yet implemented fitting using different conditions, but then it is unexpected that the `evaluateK` code is working. Are you working with the latest version of `tradeSeq`?
Also, in your `fitGAM` code, it seems like you might have forgotten to provide the trajectory information, i.e., the Slingshot object or the relevant pseudotimes and cell weights.

Best,
Koen

**Comment by Roedani** [comment]
Hi Koen,

Thanks for getting back to me.
I jus updated  my tradeSeq version and the error keeps the same.
<img width="683" alt="Screen Shot 2021-02-03 at 8 23 55 AM" src="https://user-images.githubusercontent.com/74432483/106753072-29f33980-65f9-11eb-8c80-32896346b310.png">

And when I tried to specify the cellWeight and the pseudotime, the error did not change, but instead to show numbers it shows my condition names.
cellWeights = colData(sce_1)$slingClusters,
pseudotime = colData(sce_1)$slingPseudotime_1
Error in .local(counts, ...) : 
  unused arguments (cellWeights = c("mHTO06", "mHTO09", "mHTO08", "mHTO03", "mHTO06", "mHTO07", "mHTO07", "mHTO07", "mHTO08", "mHTO07", "mHTO08", "mHTO07", "mHTO06", "mHTO02", "mHTO03", "mHTO03", "mHTO08", "mHTO07", "mHTO07", "mHTO04", "mHTO07", "mHTO04", "mHTO04", "mHTO04", "mHTO02", "mHTO03", "mHTO07", "mHTO02", "mHTO01", "mHTO04", "mHTO07", "mHTO07", "mHTO01", "mHTO08", "mHTO03", "mHTO07", "mHTO09", "mHTO07", "mHTO06", "mHTO07", "mHTO09", "mHTO06", "mHTO03", "mHTO07", "mHTO07", "mHTO06", "mHTO04", "mHTO03",

I isolated each feature barcode then I combined only two to perform the fitGAM and the error keeps the same. 
Error in .local(counts, ...) : 
  unused argument (conditions = c(1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 

Thanks,
Rodrigo

**Comment by koenvandenberge** [comment]
Hi Rodrigo,

Can you please share the full command you're using? Why are you using the cluster labels as cell-level weights?
Is it possible to share a reproducible example?

**Comment by Roedani** [comment]
Hi Koen,

Sure!

This the full command
deng_1 <- as.SingleCellExperiment(Neutrophil, assay="RNA")

sce_1 <- slingshot(deng_1, reducedDim = 'UMAP', clusterLabels = colData(deng_1)$HTO_classification,
                   start.clus = 'inner', approx_points = 150)

# plotting UMAP using slinshot object with line
plot(reducedDims(sce_1)$UMAP, asp = 1, pch = 16, xlab = "UMAP-1", ylab = "UMAP-2",
     col = hcl.colors(100, alpha = .5)[cut(sce_1$slingPseudotime_1, breaks = 100)])
lines(SlingshotDataSet(sce_1))

# calculating the Differential progression
ks.test(slingPseudotime(sce_1)[colData(sce_1)$HTO_classification == "mHTO04", 1],
        slingPseudotime(sce_1)[colData(sce_1)$HTO_classification == "mHTO06", 1])

ds <- list(mHTO06_1 = density(slingPseudotime(sce_1)[colData(sce_1)$HTO_classification == "mHTO06", 1]),
           mHTO04_1 = density(slingPseudotime(sce_1)[colData(sce_1)$HTO_classification == "mHTO04", 1]))

xlim <- range(c(ds$mHTO06_1$x, ds$mHTO04_1$x))
ylim <- range(c(ds$mHTO06_1$y, ds$mHTO04_1$y))
plot(xlim, ylim, col = "white", xlab = "Pseudotime", ylab = "")
polygon(c(min(ds$mHTO06_1$x),ds$mHTO06_1$x,max(ds$mHTO06_1$x)),
        c(0,ds$mHTO06_1$y,0), col = rgb(0,0,0,.5))
polygon(c(min(ds$mHTO04_1$x),ds$mHTO06_1$x,max(ds$mHTO06_1$x)),
        c(0,ds$mHTO04_1$y,0), col = alpha(brewer.pal(4,'Set1')[1], alpha = .5))
legend("topright", legend = c("Non-tumor", "tumor"), 
       fill = alpha(c(1, brewer.pal(3, "Set1")[1]), alpha = .5), bty = "n")

#Different expression
set.seed(3)
icMat <- evaluateK(counts = sce_1,
                   conditions = factor(colData(sce_1)$HTO_classification),
                   nGenes = 300,
                   k = 3:7)

set.seed(3)
sce_1 <- fitGAM(counts = sce_1,
             conditions = factor(colData(sce_1)$HTO_classification),
              nknots = 5)

If you want I can share my file with you.

About the cell-level weights I just tried it because In your previous response you told that I was missing the slingshot object or the relevant pseudotimes and cell weights. 

Thanks so much,
Rodrigo

**Comment by HectorRDB** [comment]
Hi @Roedani 
First, I am unsure what is your experimental design but you are using the `HTO_classification` both as cluster inputs to slinghsot (suggesting they are related to classification) and as conditions. Are you sure about this part?
I am kind of puzzled as to why evaluateK is working but not fitGAM. Could you email me a subset of the data?
best,

**Comment by Roedani** [comment]
Oi @HectorRDB 
About your question, I was not totally sure. So, I tried this command using the Seurat clusters for classification 
sce_1 <- slingshot(deng_1, reducedDim = 'UMAP', clusterLabels = colData(deng_1)$seurat_clusters,
                   start.clus = 'inner', approx_points = 150)

then, I kept the HTO_classification as condition because in there I have all my samples. 

sce_1 <- fitGAM(counts = sce_1,
             conditions = factor(colData(sce_1)$HTO_classification),
              nknots = 5)

and running it as test, apparently is working because it started, however it is taking a lot of time to load. 

Fitting lineages with multiple conditions. This method has been tested on a couple of datasets, but is still in an experimental phase.
  |+                                                 | 1 % ~17h 31m 50s 

I would love to send a subset of my data, but I am beginner working with scRNAseq and I do not know exactly which type of file you want, if you tell me what and how I can get it, I send it to you right way.

Thanks so much,
Rodrigo

**Comment by Roedani** [comment]
Hi @HectorRDB 

The fitGAM took all the weekend to finish but it seems that worked.
# most significant gene
<img width="689" alt="Screen Shot 2021-02-08 at 10 32 31 AM" src="https://user-images.githubusercontent.com/74432483/107241474-0402d600-69f9-11eb-8d8b-032cc6d2660e.png">

<img width="689" alt="Screen Shot 2021-02-08 at 10 22 42 AM" src="https://user-images.githubusercontent.com/74432483/107241447-fcdbc800-69f8-11eb-9841-72e7c43d0319.png">

However, the last part I need to fix.
# Heatmaps of genes DE between conditions
<img width="692" alt="Screen Shot 2021-02-08 at 10 32 09 AM" src="https://user-images.githubusercontent.com/74432483/107241733-43312700-69f9-11eb-8a09-cbab844e3921.png">
 
Could you please let me know if everything looks okay for you? or if there is something wrong?
 
Thanks so much for all kind help,
Best wishes,
Rodrigo

**Comment by HectorRDB** [comment]
Hi @Roedani 
I would need the code that you used to generate those plots in order to help.
Best,

**Comment by Roedani** [comment]
Hi @HectorRDB 

Of course, and thanks again.

#Differential expression between conditions
plotSmoothers(sce_1, assays(sce_1)$counts, gene = "Sp110", alpha = 1, border = TRUE) + ggtitle("Fn1")

#Differential expression analysis
condRes <- conditionTest(sce_1, l2fc = log2(2))
condRes$padj <- p.adjust(condRes$pvalue, "fdr")
mean(condRes$padj <= 0.05, na.rm = TRUE)

sum(condRes$padj <= 0.05, na.rm = TRUE)

conditionGenes <- rownames(condRes)[condRes$padj <= 0.05]
conditionGenes <- conditionGenes[!is.na(conditionGenes)]

# plot genes
oo <- order(condRes$waldStat, decreasing = TRUE)

# most significant gene
plotSmoothers(sce_1, assays(sce_1)$counts,
              gene = rownames(assays(sce_1)$counts)[oo[1]],
              alpha = 1, border = TRUE)


# least significant gene
plotSmoothers(sce_1, assays(sce_1)$counts,
              gene = rownames(assays(sce_1)$counts)[oo[nrow(sce_1)]],
              alpha = 1, border = TRUE)


# Heatmaps of genes DE between conditions
### based on mean smoother
yhatSmooth <- predictSmooth(sce_1, gene = conditionGenes, nPoints = 50, tidy = FALSE)
yhatSmoothScaled <- t(scale(t(yhatSmooth)))
heatSmooth_tumor <- pheatmap(yhatSmoothScaled[, 51:100],
                             cluster_cols = FALSE,
                             show_rownames = TRUE, show_colnames = FALSE, main = "Tumor", legend = FALSE,
                             silent = TRUE
)

matchingHeatmap_control <- pheatmap(yhatSmoothScaled[heatSmooth_tumor$tree_row$order],
                                    cluster_cols = FALSE, cluster_rows = FALSE,
                                    show_rownames = FALSE, show_colnames = FALSE, main = "Control",
                                    legend = FALSE, silent = TRUE
)

library(gridExtra)
grid.arrange(heatSmooth_tumor[[4]], matchingHeatmap_control[[4]], ncol = 2)

Best wishes,
Rodrigo

**Comment by HectorRDB** [comment]
Ok I am completely lost in what you are trying to do. 
It looks like you have two conditions, tumour and control, by the names you use, but the conditions vector has 4 levels (MTO02, MTO04, MTO06, MTO08). I don't think the code is doing what you think it is.

Furthermore, I would be careful in general when copy-pasting code. Here you wrote
```
matchingHeatmap_control <- pheatmap(yhatSmoothScaled[heatSmooth_tumor$tree_row$order],
```
instead of
```
matchingHeatmap_control <- pheatmap(yhatSmoothScaled[heatSmooth_tumor$tree_row$order, 51:100],
```

**Comment by HectorRDB** [comment]
Closed for inactivity after one month. Feel free to reopen if need be.
