### ISSUE TITLE
conditionTest - provide l2fc in output

### ISSUE THREAD

**Issue by kmshort** [statOmics/tradeSeq#119]
At the moment, conditionTest outputs: gene, waldStat, df and pvalue.

The inclusion of the l2fc threshold argument in conditionTest enables condition testing of genes within a lineage that have a user defined log2FC.

against indicates that log2FC is somewhere used to prefilter the differences between conditions, but doesn't show the calculated values for the log2FC the genes that pass the l2fc threshold that is set.
Could these values please be included in the conditionTest output so we can use those values to rank the absolute differences between conditions within a single lineage? Even if it's a mean of means from each fitGAM knot or something like that (however it is used in the filtering step of the function).

best,
K

**Comment by koenvandenberge** [comment]
Discussion deferred to #104.
