### ISSUE TITLE
correlate pseudotime values with that of monocle

### ISSUE THREAD

**Issue by huanz4** [statOmics/tradeSeq#122]
Hi,

Thanks for providing this package. I am currently doing the gene expression pattern analysis with it. I plotted the graph according to the following code from tradeseq workflow:

nPointsClus <- 20
cUniq <- unique(clusterLabels)
cUniq <- cUniq[!cUniq == -1] # remove unclustered genes

for (xx in cUniq[1:4]) {
  cId <- which(clusterLabels == xx)
  p <- ggplot(data = data.frame(x = 1:nPointsClus,
                                y = rep(range(clusPat$yhatScaled[cId, ]),
                                        nPointsClus / 2)),
              aes(x = x, y = y)) +
    geom_point(alpha = 0) +
    labs(title = paste0("Cluster ", xx),  x = "Pseudotime", y = "Normalized expression") +
    theme_classic() +
    theme(plot.title = element_text(hjust = 0.5))
  for (ii in 1:length(cId)) {
    geneId <- rownames(clusPat$yhatScaled)[cId[ii]]
    p <- p +
      geom_line(data = data.frame(x = rep(1:nPointsClus, 2),
                                  y = clusPat$yhatScaled[geneId, ],
                                  lineage = rep(0:1, each = nPointsClus)),
                aes(col = as.character(lineage), group = lineage), lwd = 1.5)
  }
  p <- p + guides(color = FALSE) +
    scale_color_manual(values = c("orange", "darkseagreen3"),
                       breaks = c("0", "1"))  
  print(p)
}

I extracted pseudotime values from monocle. My question is that if I set the npoint to be the highest pseudotime value I got from monocle, will this correspond to the actual monocle pseudotime? I am asking this because I would like to find out in monocle on my umap where the gene expression change occurs.

**Comment by HectorRDB** [comment]
Hi @huanz4,
I assume you are referring to the `nPointsClus` option? This option is used to decide how many points to use to draw the curves, i.e. it is an integer values. It is independent of the range of pseudotimes. 
Those points are equally spaced along pseudotime value so the maximum value will match the maximum pseudotime in the longest lineage.

**Comment by huanz4** [comment]
Hi Hector,

Thanks for your quick reply. That was clear.

Best,
Huan
