### ISSUE TITLE
Allow plotSmoothers to plot specfic lineages only

### ISSUE THREAD

**Issue by ccasar** [statOmics/tradeSeq#124]
Hi,

I have not found a simple way to do this with the current functions in tradeSeq.

**Is your feature request related to a problem? Please describe.**

I have a dataset with two conditions and four lineages. I've run fitGAM on this dataset with the condition argument set and when I try to plot a gene with plotSmoothers it always plot all lineages and all conditions:

![plotsmoothers_all_lineages](https://user-images.githubusercontent.com/2711108/107945535-1304fd80-6f90-11eb-8eee-b94c3416ec61.png)

This is nice to get an overall overview, but pretty crowded if I just wanted to show this gene in lineage 1 between both conditions (BL,V2). 

**Describe the solution you'd like**
Maybe have additional arguments to plotSmoothers to allow for filtering on conditions/lineages OR describe how to filter the SCE object returned by fitGAM to keep only specific lineages/conditions.

**Describe alternatives you've considered**
I've tried manipulating the resulting ggplot object by adding a custom color scale  but this might not be the best way to go about it.

**Comment by koenvandenberge** [comment]
Hi @ccasar 

Thanks for the suggestion, we will look into it.

**Comment by HectorRDB** [comment]
Hi @ccasar 
Thanks for this and for opening a very clear issue. 
Unfortunately, filtering before feeding the object to plotSmoothers would only work to subset the points, not the curves since those are considered as rowData.
I will look into updating this.
In the meantime, you can use both the pointCols and curveCols arguments from the latest tradeSeq version. With those arguments, you will be able to specify the color of each point (i.e the count for eah cell) and each curve. 
Specifying some to 'transparent' should do what you want.
Best

**Comment by ccasar** [comment]
Hi,

thanks for the quick response. I've installed 1.5.7 from github to test the pointCols and curveCols arguments.
I've used this command:

```
plotSmoothers(trade_fit, assays(sce_rna)$counts, 
                                                gene = 'SELL', 
                                                pointCol = cell_condition_cols$color,
                                                curvesCol = curve_condition_colors)
```
The plot looks like this now:

![plotsmoothers_arguments](https://user-images.githubusercontent.com/2711108/107994413-d9a6af00-6fdc-11eb-8ae8-281311496288.png)


Setting curve colors worked. Here it was important to use '#FFFFFF00', i.e. adding the '00' for full transparency, otherwise the white curves were still noticeable due to overlaps with points/curves. 
But the color mapping for `pointCol` does not work as expected. The documentation reads: 

> Plotting colors for each cell. Can be either character vector of length 1, denoting a variable in the colData(models) to color cells by, or a vector of length equal to the number of cells. 

I would expect the points to take the colors of the vector I use for `pointCol`. It would be nice if `plotSmoothers` were 'intelligent' enough to use the given colors as the actual colors instead of using the default ggplot color scale. But it's easy enough to fix the plot by adding a new color scale manually:

```
plotSmoothers(trade_fit, assays(sce_rna)$counts, 
                                                gene = loop_gene , 
                                                alpha = 1, border = FALSE,
                                                pointCol = cell_condition_cols$color,
                                                curvesCol = curve_condition_colors) + 
          scale_color_manual(values = color_map, breaks = names(color_map)[1:2], labels = c('BL','V2'))

> color_map
$`#7fc97f`
[1] "#7fc97f"

$`#beaed4`
[1] "#beaed4"

$`#FFFFFF00`
[1] "#FFFFFF00"
```

**Comment by HectorRDB** [comment]
Hi @ccasar 
Thanks for this. I will add the scale_color_manual line to the code and your suggestion of having the extra `00` at the end in the examples.

**Comment by HectorRDB** [comment]
Actually, I will not add the scale_color_manual line since we want users to be able to pass a vector for `pointCols` that can represent something else (cluster labels for example). I don't know of a general way to distinguish between colors and not-colors in the code so I will keep it as it is.

**Comment by jeremymsimon** [comment]
Hey @HectorRDB I'm trying to make a plot similar to the one described in this issue (one lineage out of 8 total, 2 conditions), and am getting a ggplot warning that I'm not sure if it is safe to ignore:

Here is what I'm doing and the error I'm getting:
```
curvesCols <- c("#FFFFFF00", "#FFFFFF00","#FF0000FF","#0000FFFF","#FFFFFF00", "#FFFFFF00","#FFFFFF00", "#FFFFFF00","#FFFFFF00", "#FFFFFF00","#FFFFFF00", "#FFFFFF00","#FFFFFF00", "#FFFFFF00","#FFFFFF00", "#FFFFFF00")
plotSmoothers(sce, assays(sce)$counts, gene = "Fabp7", border = FALSE, curvesCols = curvesCols) +
+     ggplot2::scale_color_manual(values = curvesCols)

Scale for 'colour' is already present. Adding another scale for 'colour', which will replace the existing scale.
```

I understand this error gets thrown when there are multiple things setting the color scale, but I'm not familiar with what `plotSmoothers` is doing under the hood in this regard. Is this error/warning expected? Should I trust the plot that comes out despite the warning?

Thanks!

**Comment by HectorRDB** [comment]
Yes it is fine to ignore. By default, `plotSmoothers` will have a `scale_color_discrete` so it's giving the warning. You can safely ignore it.

**Comment by jeremymsimon** [comment]
Thanks!

**Comment by gabsax** [comment]
Hi @HectorRDB ,

Thank you for the amazing package it's very nice. I am also using TradeSeq to compare different conditions however I also have a visualization problem with plotSmoothers.

It seems like the curvesCols argument doesn't work for me. when I run:
curvesCols <- c("#339999", "#9E0142", "transparent")
plotSmoothers(sce, assays(sce)$counts, gene = "Bcl2", alpha = 0, border = F, curvesCols = curvesCols)

I get the Error:
Error in .local(models, ...) : 
  unused argument (curvesCols = c("#339999", "transparent", "transparent"))

Any thoughts? I have tried different colors, scale_color_manual, reinstall TradeSeq.

Thanks
