### ISSUE TITLE
Increase clusters using the code given in tradeseq tutorial

### ISSUE THREAD

**Issue by ammarsabircheema** [statOmics/tradeSeq#127]
Hi,

Can you please tell me how can I increase the number of clusters using this code? This code is taken from tradeseq tutorial, I tried to increase the number of clusters myself but it did not work, so Is there a way I can increase the number of clusters that are printed at the end?

```{r}
nPointsClus <- 45
clusPat <- clusterExpressionPatterns(sce, nPoints = nPointsClus,
                                     genes = rownames(expression_matrix_scapin@assays$RNA@data)[1:300])
clusterLabels <- primaryCluster(clusPat$rsec)

cUniq <- unique(clusterLabels)
cUniq <- cUniq[!cUniq == -1] # remove unclustered genes


plot_list = list()
for (xx in cUniq[1:18]) {
  cId <- which(clusterLabels == xx)
  p <- ggplot(data = data.frame(x = 1:nPointsClus,
                                y = rep(range(clusPat$yhatScaled[cId, ]),
                                        nPointsClus / 2)),
              aes(x = x, y = y)) +
    geom_point(alpha = 0) +
    labs(title = paste0("Cluster ", xx),  x = "Pseudotime", y = "Normalized expression") +
    theme_classic() +
    theme(plot.title = element_text(hjust = 0.5))
  for (ii in 1:length(cId)) {
    geneId <- rownames(clusPat$yhatScaled)[cId[ii]]
    p <- p +
      geom_line(data = data.frame(x = rep(1:nPointsClus, 2),
                                  y = clusPat$yhatScaled[geneId, ],
                                  lineage = rep(0:3, each = nPointsClus)),
                aes(col = as.character(lineage), group = lineage), lwd = 1.5)
  }
  p <- p + guides(color = FALSE) +
    scale_color_manual(values = c("orange", "darkseagreen3","red","blue"),
                       breaks = c("0", "1"))  
  plot_list[[i]] = p
   

}
```

**Comment by koenvandenberge** [comment]
Hi @ammarsabircheema 

The `clusterExpressionPatterns` function is basically a wrapper around the functionality provided by the Bioconductor `clusterExperiment` package, in particular the `RSEC` function. There are many arguments within `RSEC` that can be used to tweak the number of clusters, and these arguments can also be provided to `clusterExpressionPatterns`. I therefore suggest you take a look at the [corresponding section of the tradeSeq vignette](https://bioconductor.org/packages/release/bioc/vignettes/tradeSeq/inst/doc/tradeSeq.html#clustering-using-rsec-clusterexperiment) and also the [clusterExperiment vignette](https://www.bioconductor.org/packages/release/bioc/vignettes/clusterExperiment/inst/doc/clusterExperimentTutorial.html) to see what works for you. 

Alternatively you can also use another clustering method of your preference. See the [relevant section in the tradeSeq vignette](https://bioconductor.org/packages/release/bioc/vignettes/tradeSeq/inst/doc/tradeSeq.html#clustering-of-genes-according-to-their-expression-pattern) for that.

**Comment by ammarsabircheema** [comment]
Hi,

Thanks for your response, before posting here 

- I already looked at the clusterExperiment vignette and I was not able to find the solution, 

- I even tried to increase the number of clusters on my own by changing nPointsClus <- 45 and changing the gene number to 300 

- this did increase the number of clusters but when I tried to plot them I was getting errors, 
- the error was related to populating the dataframe which is saved in data. 
-  The error was due to unequal number of values for both columns which I was not able to solve. 

So Is there an easy way to just tweak the code given above to increase the number of clusters?

**Comment by koenvandenberge** [comment]
Hi @ammarsabircheema 

Please take a better look at the `clusterExperiment ` vignette and our help files. For example, the `ks` argument in `clusterMany` from `RSEC` lets you increase the number of clusters. You may also consider more principal component dimensions for the clustering.
The `nPointsClus` argument in `clusterExpressionPatterns` does not relate to the number of clusters, but it relates to the number of points for each lineage to use in the clustering. Please see the help file `?clusterExpressionPatterns`.

The plotting function in the vignette is indeed specific to the number of lineages in that example. We can look into generalizing that function to any number of lineages.

**Comment by HectorRDB** [comment]
Closed due to inactivity after one month. Feel free to reopen if the problem persists.
