### ISSUE TITLE
help with imbalance_score 

### ISSUE THREAD

**Issue by france-hub** [statOmics/tradeSeq#128]
Hi, 

Thank you for this wonderful package. 

I am reaching out to get some advices on how to proceed with my analysis. Briefly I am analyzing CD8+ T cells and I have 3 conditions: healthy controls, responders and non responders to treatment. 

I am following your bioc2020 workshop and after running your imbalance_score function I've obtained the following UMAP: 

![balance](https://user-images.githubusercontent.com/56587709/109170991-4cd3c200-774f-11eb-9786-46fb4333ec85.jpeg)

I can see more regions of unbalance compared to your data in your workshop. I am wondering if it's reasonable to infer across conditions or if you rather suggest to analyze the different conditions separately. 

Thank you very much

Best,

Francesco

**Comment by HectorRDB** [comment]
Hi Francesco,
Your question could not be better timed. We are releasing a new method specifically focused on this issue. The package and preprint should be out either later this week or early the next. You can follow my twitter account for updates but I'll also post the links here when it is out.

**Comment by france-hub** [comment]
Nice!
Thank you very much Hector!

**Comment by kmshort** [comment]
@HectorRDB what's your twitter account handle?

I'm using this Imbalance package from kstreet13/bioc2020trajectories too.

**Comment by HectorRDB** [comment]
hector_rdb

**Comment by kmshort** [comment]
> hector_rdb

thanks @HectorRDB , following now.

**Comment by HectorRDB** [comment]
Hi all,
it took a bit longer than expected but the paper is on [biorxiv](https://doi.org/10.1101/2021.03.09.433671) and you can go check out the new [R package called condiments](https://hectorrdb.github.io/condiments/). Feel free to open an issue over there if you still have a question

**Comment by france-hub** [comment]
Great!

**Comment by kmshort** [comment]
Fantastic @HectorRDB 
Where do you think you'll send the complete manuscript?
