### ISSUE TITLE
Question about parameter genes in fitGAM

### ISSUE THREAD

**Issue by s2hui** [statOmics/tradeSeq#129]
Hello, 

I just started using tradeSeq and I had a general question about selecting the number of genes for the parameter genes in fitGAM.  

In a posting for issue #64  it says to use the top 1k features as "top 1-2k features usually contain most of the signal."  What is the recommended way to select the top 1-2K features?  Is this based on variable expression?  The info [here](https://statomics.github.io/tradeSeq/articles/fitGAM.html#fitting-only-a-subset-of-genes) uses the first 25 rows of the counts matrix - is this recommended in practice?

I have >30K genes in my counts matrix and was hoping that filtering this set of genes down to the suggested range of 1-2k genes would help fitGAM run faster.  I have run it on 100-200 genes and it executes quickly.  I have two lineages and am using 6 knots.

Thanks alot for your help!

**Comment by HectorRDB** [comment]
Hi @s2hui 
The link to the vignette is definitely not what we recommend in practice, it is just a demo of how to use this argument. If you can run 200 genes quickly (which is not surprising if you are using only 6 knots and two lineages), you can probably go as high as 5k without it taking too long. 
To select the features, we generally use two options:
- Filter in the form: keep genes with at least x counts in k cells (with x between 5 or 10, k depending on the number of cells)
- Seurat's findVariableFeatures functions

Hope that helps

**Comment by s2hui** [comment]
Yes that helps alot, thank you!
