### ISSUE TITLE
look into updated parallelization 

### ISSUE THREAD

**Issue by koenvandenberge** [statOmics/tradeSeq#13]
We are currently using `BiocParallel::bpparam`, but seems like `DoparParam` might be a better choice, e.g. https://github.com/drisso/zinbwave/issues/38

**Comment by kmshort** [comment]
Hi @koenvandenberge 
I wonder if you could look into per-thread memory usage when running fitGam().
I don't know how memory is managed per-thread now, and if R garbage collection has any involvement however if you can reduce the per-thread ram usage.. it would be great if you could. That might mean that individual jobs are divided into smaller jobs/reduce scope, for example. I've experienced this wall for a long time, and for example, I'm current running a job right that is  using 15.5gb per thread. I only have 128gb ram, but a CPU that has 32 threads available. So it would be great if memory per thread could be significantly reduced/capped and thereby I could use a lot more threads. I don't know if that's possible, but it would seriously help throughput on "low" memory high thread count workstations/servers.
best
K
