### ISSUE TITLE
Getting different fitting curves for the same genes when tuning different# of genes as input for fitGAM.

### ISSUE THREAD

**Issue by ChenyiLyu** [statOmics/tradeSeq#130]
Hi tradeSeq Team,

Thanks for the wonderful package! I am benefited a lot from your bioc2020 workshop. Thanks a lot for the wonderful tutorial!

I am reaching out for a issue with fitGAM(). When I was running fitGAM using just a few marker genes (9 genes), for one of the genes, I had the following plot:

<img width="400" alt="Screen Shot 2021-02-26 at 20 26 15" src="https://user-images.githubusercontent.com/54817948/109371296-4e49db00-7872-11eb-931a-06fe7ef29b2b.png">

Then I used 2,000 variable genes from Seurat:::FindVariableFeatures() as input, and fit the curve for the same gene:
<img width="400" alt="Screen Shot 2021-02-26 at 20 42 17" src="https://user-images.githubusercontent.com/54817948/109371476-1ee79e00-7873-11eb-8f18-c05d3b541914.png">

The cell dots distributing in similar pattern; the curve disappeared(or smoothed away?) in the second plot. The same goes with my other 8 genes, here is another example:
<img width="400" alt="Screen Shot 2021-02-26 at 20 49 47" src="https://user-images.githubusercontent.com/54817948/109371730-3bd0a100-7874-11eb-9fed-cad75bca89e8.png">
^small gene set as input
<img width="400" alt="Screen Shot 2021-02-26 at 20 49 56" src="https://user-images.githubusercontent.com/54817948/109371747-50149e00-7874-11eb-8301-873f060dd04a.png">
^2,000 gene set as input

I have the following question: 
first, I was thinking the input gene number should not impact the estimated smoothers, at least shouldnt change too much? Because according to the tutorial, we are still using the information across all genes to perform the normalization even if we use subset of the genes to fit the model.
second, maybe this is trivia, but when I looked at the first graph and compared the dots with the fitting line, the trend of  curve went kinda of counterintuitive.. I have the same convergence issue with other genes. 

I am following through the code provided by the workshop. Below is the code for the above two tests. The only difference was the input gene set.
```r
crv <- SlingshotDataSet(sce)
pseudotime <- slingPseudotime(crv, na=FALSE)
cellWeights <- slingCurveWeights(crv)`

set.seed(3)
start_time <- Sys.time()
gam_sce <- fitGAM(counts = as.matrix(assays(sce)$counts), 
              pseudotime = pseudotime, 
              cellWeights = cellWeights,
              conditions = factor(colData(sce)$sample),
              genes = genes,
              nknots = 6, verbose = FALSE, parallel=TRUE, BPPARAM = BPPARAM)
end_time <- Sys.time()
start_time - end_time 
# Time difference of -1.852349 mins
# Time difference of -1.803964 hours
```
Attached knots selection plot here. I tried out 4:7 knots on the small set of genes, it turned out there was no big difference on the smoother plot, so I went with 6 knots in the end.
<img width="400" alt="Screen Shot 2021-02-26 at 21 18 40" src="https://user-images.githubusercontent.com/54817948/109372575-36755580-7878-11eb-8ed1-e1c3acd34dac.png">

SessionInfo
```r
R version 4.0.3 (2020-10-10)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS Big Sur 10.16

Matrix products: default
LAPACK: /Library/Frameworks/R.framework/Versions/4.0/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] parallel  stats4    stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] tradeSeq_1.5.07             gridExtra_2.3               ggplot2_3.3.3              
 [4] knitr_1.31                  fgsea_1.16.0                msigdbr_7.2.1              
 [7] pheatmap_1.0.12             UpSetR_1.4.0                viridis_0.5.1              
[10] viridisLite_0.3.0           scales_1.1.1                RColorBrewer_1.1-2         
[13] SeuratObject_4.0.0          Seurat_4.0.0                slingshot_1.8.0            
[16] princurve_2.1.6             SingleCellExperiment_1.12.0 SummarizedExperiment_1.20.0
[19] Biobase_2.50.0              GenomicRanges_1.42.0        GenomeInfoDb_1.26.2        
[22] IRanges_2.24.1              S4Vectors_0.28.1            BiocGenerics_0.36.0        
[25] MatrixGenerics_1.2.1        matrixStats_0.58.0         
```
Thank you so much for your help and time in advance!

**Comment by koenvandenberge** [comment]
Hi @ChenyiLyu 

We're glad you've benefited from the workshop!

Thank you for reporting this, this is indeed puzzling. A different number of genes would impact the normalization since sequencing depths would be different.
As a first step in diagnosing the problem, could you please check if the problem you're seeing persists if we do not normalize?
You can do that using the `offset = rep(0, ncol(sce))` argument to `fitGAM`.

**Comment by ChenyiLyu** [comment]
Hi @koenvandenberge,

Thanks a lot for the reply! 

I passed `offset = rep(0, ncol(sce))` into `fitGAM`, and ran again for gene subset and 2,000 genes. Turns out the plots remain the same under both situation.

**Comment by ChenyiLyu** [comment]
Hi @koenvandenberge,

I figured out the problem! If I pass the results from `slingshot()` directly into `fitGAM()` instead of manually separating out the data using `slingPseudotime()` and `slingCurveWeights()`, then the fitting becomes reasonable and the curves are independent from input gene numbers! So I modified my code into this:
```r
gam_sce <- fitGAM(counts = sce,
                   conditions = factor(colData(sce)$sample),
              genes = genes,
              nknots = 5, verbose = FALSE, parallel=TRUE, BPPARAM = BPPARAM)
```
<img width="415" alt="Screen Shot 2021-02-28 at 13 12 56" src="https://user-images.githubusercontent.com/54817948/109428800-ae519600-79c6-11eb-9db7-c398b98956ce.png">

But what is the difference between manually pass in counts, pt, cellWeights and a SingleCellExperiment object? In the workshop, when deciding nknots we are manually pass in the data, but for `fitGAM()` we are pass in sce object. I was wondering if I was using `fitGAM()` in an uncorrected way at the beginning or it is a bug?

Sorry for the redundant following up questions. Thanks a lot for your time and patience^^

**Comment by koenvandenberge** [comment]
Hi @ChenyiLyu 

> I am sort of confused: In a posting for issue #129 it mentioned top 1-2k should work, so I suspect the gene set input would not impact the curve fitting. While the curve changes as input gene# changes, just from observation view, in none of the cases the curve is a good fit?

I would be cautious here not to overinterpret. What was said there is that often the top 1-2k features contain a lot of the signal 
to recover the major structure(s) in your dataset. But that doesn't mean other features will not be differentially expressed. In DE analysis, we do recommend you to look at most of the genes in your dataset, after some filtering criterion to ensure they are at least expressed in some part of the data you're looking at.

Thank you for reporting these differences. It is not expected that the fits should be different between the two input types. Do you mind sharing (a subset of) the `sce` object you're using here so I can look into this? Feel free to post a link here or send an e-mail to koenvdberge@berkeley.edu. Thanks!

**Comment by ChenyiLyu** [comment]
Email sent out. Thanks again for the follow up!

**Comment by koenvandenberge** [comment]
Hi @ChenyiLyu 

This has been a combination of issues in `fitGAM` and `plotSmoothers` when using the different inputs, in particular in combination with a `genes` argument in `fitGAM`. I believe I have fixed these issues now and, on my machine, it seems to work as expected on your data. Feel free to check it out. 

Thanks again for your detailed report, this was very helpful to us!
Let us know if you encounter any further issues.
