### ISSUE TITLE
bisection in heatmap after predictSmooth

### ISSUE THREAD

**Issue by julicudini** [statOmics/tradeSeq#132]
Hello, 

Thanks for the great tool!

I am trying to plot a pheatmap of some genes over pseudotime time and I'm getting a little lost with the output of ```predictSmooth```. I have two lineages and, as expected, when choosing ```nPoints = 60``` I get back a dataset with 2x60 columns corresponding to the 2 lineages over 60 timepoints. The columns are arranged lineage_1, lineage_2 for each timepoint, so choosing ```df[,1:60]``` would not give me the values corresponding to just one lineage over time, but rather the first 30 timepoints alternating between lineage 1 and lineage 2 like so:
![image](https://user-images.githubusercontent.com/22456691/109846558-385b6200-7c46-11eb-853a-3f6d0a857f03.png)

I tried subsetting just the columns corresponding to lineage 1, but still found this bisection in my heatmap halfway through - and I'm not sure what it corresponds to? For example, using the same matrix as above, but subsetting on 'lineage_1':
![image](https://user-images.githubusercontent.com/22456691/109847264-e36c1b80-7c46-11eb-92eb-3421d8219801.png)

The```plotSmoothers``` of some of these genes suggest they all are 'turning on' in a window of ~ 3 pseudotime values, so I was expecting to see a gradual increase 'on', and I am struggling to interpret the bisection I see at timepoint 30. I have run ```tradeSeq``` without experimental conditions, so they do not correspond to that. I ran ```predictSmooth``` using the output of ```fitGAM``` on the whole dataset, with 60 points and ```tidy=FALSE```. The pseudotime was calculated using ```slingshot``` and ranges from 0-~6.5 in both lineages. The branching pattern is that of a pretty distinct Y shape. I'm using ```tradeSeq v1.5.06```. 

Am I missing something obvious?  Thanks for your help!

**Comment by julicudini** [comment]
To expand on this, using ```tidy=TRUE``` and subsetting the dataframe myself to isolate just lineage 1 and plotting gives this heatmap:
![image](https://user-images.githubusercontent.com/22456691/109934662-afcfd680-7cc4-11eb-80e0-b5189904deed.png)

which looks identical to the first heatmap, where the labels suggested alternated between lineage 1 and 2 per time point. Is it possible the non-tidy output of ```predictSmooth``` has mislabeled the columns and it should instead read lineage 1, 1:nPoints and then lineage 2, 1:nPoints?

**Comment by DustinSokolowski** [comment]
Hey!

I just wanted to mention that I have the exact same phenomena when I have 3 and 6 lineages respectively. I also came to the same conclusion as @julicudini. Unfortunately I'm having a somewhat tricky time telling when looking at the code directly.

**Comment by HectorRDB** [comment]
HI @DustinSokolowski @julicudini 
The latest commit should have fixed it. Let me know if it does not work. Thanks for sharing.
