### ISSUE TITLE
split plotGeneCount output plot by condition

### ISSUE THREAD

**Issue by JesseRop** [statOmics/tradeSeq#133]
Is it possible to split the plotGeneCount output by condition so as to get a clear visualization of gene expression per cell in different conditions?

**Comment by JesseRop** [comment]
Is it possible to split the plotGeneCount output by condition so as to get a clear visualization of gene expression per cell in different conditions?

**Comment by koenvandenberge** [comment]
Thanks for the suggestion @JesseRop, I will look into this.

**Comment by koenvandenberge** [comment]
I have transferred this issue to our visualization package, `traviz`, at https://github.com/koenvandenberge/traviz/issues/1
