### ISSUE TITLE
timecourse analysis on bulk RNA-seq

### ISSUE THREAD

**Issue by ikumar2000** [statOmics/tradeSeq#134]
Could you please provide detailed information on performing a time course analysis of bulk RNA-seq. A use case study in the manual/bioc would be super helpful too.  My setup involves 3 genotypes, 2 treatments and 3 timepoints with 3 replicates each.

**Comment by HectorRDB** [comment]
Hi @ikumar2000 
Writing a vignette on this topic would be a great idea. 
However, in your particular setting, using `tradeSeq` would be quite challenging. `tradeSeq` relies on smoothing splines and, although they have some regularisation, they do usually require much more data to properly fit. This is going to be even more dire with three time points since there will be exactly one knot per timepoint so the risk of overfitting is very high. 

I would recommend doing a more classic DE analysis, using edgeR or DESeq2 in this case, adding the time component as a variable with three levels.

**Comment by ikumar2000** [comment]
While going through the methodology, I did suspect that my dataset might be too small for model fitting. What would be good size of data for this? Would 7-8 time points suffice? Yes, I have already performed DE with edgeR however wanted to perform pattern DE testing. 
  In any case, I have much bigger dataset (bulk RNA-seq) incoming and would like to set up a pipeline so  a detailed example would help. I can build on it.

**Comment by HectorRDB** [comment]
I think anything more than 5 would work. In the case study for the paper, we had 6 time points and three replicates. The more time points you have, the more likely you are to detect subtle changes (such as temporary activation or repression). 
I'll let you know when I write the vignette.

**Comment by HectorRDB** [comment]
If you absolutely want to run the analysis, you can use the `fitGam` function, using the treatment assignments as lineages and the genotypes assignments as conditions.
Be sure to set `nknots` to 3 as well.  As usual, you should also filter the dataset before running `fitGam`

**Comment by ikumar2000** [comment]
Thanks, Hector. By filtering, do you refer to filtering out lowly expressed genes? How would the time series factor be entered?

Inder

**Comment by HectorRDB** [comment]
Yes 
The time can replace the usual pseudotime variable. You can find the bulk RNA seq case study code on our Github (https://github.com/statOmics/tradeSeqPaper/blob/master/case/bulkTimeCourse/20190619_caseKiselov.R), it should give you a good start. Feel free to comment if anything else is unclear.
Best

**Comment by ikumar2000** [comment]
Great. You are so helpful.

Thanks,
Inder

**Comment by ikumar2000** [comment]
Hi Hector,

 The part of determining the weight for the bulk RNA-seq wasn't very clear to me. Could you please explain. 

Thanks,
Inder     On Wednesday, March 24, 2021, 01:09:40 PM CDT, ***@***.***> wrote:  
 
 Great. You are so helpful.

Thanks,
InderOn Mar 24, 2021, 1:07 PM -0500, Hector Roux de Bézieux ***@***.***>, wrote:
Yes
The time can replace the usual pseudotime variable. You can find the bulk RNA seq case study code on our Github (https://github.com/statOmics/tradeSeqPaper/blob/master/case/bulkTimeCourse/20190619_caseKiselov.R), it should give you a good start. Feel free to comment if anything else is unclear.
Best

**Comment by HectorRDB** [comment]
Hi @ikumar2000 
If you have a time-course data (i.e all samples are progressing along the same axis), then you can just use a vector of 1, with one value per sample.
Best

**Comment by CWYuan08** [comment]
Hi @HectorRDB, is there a vignette on running bulk RNA-seq data now? I would greatly appreciate it if there is one. Many thanks.
