### ISSUE TITLE
output of predictCells

### ISSUE THREAD

**Issue by ella-beaumann** [statOmics/tradeSeq#135]
Hi all !

I used predictCells to produce two heatmaps: DE genes using the results of the association test, and some transcription factors. Because I have a number of genes present in both, I saw that the output of predictCells was different when I used it with different lists of genes.

Here's an example:

![image](https://user-images.githubusercontent.com/36297507/112659763-fdb7a480-8e54-11eb-8113-9692b74fa3f5.png)

Heatmaps were done using the results of predictCells on the same model using the genes with fdr<=0.05 for the association test (as shown in the vignette), some transcription factors, and finally the genes overlapping the first two sets.

I ordered the cells by pseudotime and put the results of predictCells for the same gene (ceh-6) in the following dataframe.
```{r}
        assoRes        tf overlapping
cell_1 1.020144 0.5152502    1.217132
cell_2 1.151130 0.5814080    1.373412
cell_3 1.505809 0.7605478    1.796578
cell_4 1.225308 0.6188732    1.461912
cell_5 1.460470 0.7376482    1.742485
cell_6 1.473234 0.7440947    1.757713
```

I was wondering if this was the intended behaviour of predictCells or a bug. I know predictSmooth is more adapted for this type of figures, but I wanted to be able to map my cell clusters at the top.

Thank you for your help, and for this great package !

**Comment by koenvandenberge** [comment]
Hi @ella-beaumann 

This indeed seems to have been a bug, thank you for reporting it! 
I believe it should now be fixed. Let me know if it isn't.

Best,
Koen
