### ISSUE TITLE
a question about  associationTest()

### ISSUE THREAD

**Issue by liuweihanty** [statOmics/tradeSeq#138]
Dear TradeSeq developers,
Thanks for the great tool! I have a question for the workflow Vignette:https://bioconductor.org/packages/release/bioc/vignettes/tradeSeq/inst/doc/tradeSeq.html
When you mention we can test whether genes are significantly associated a particular lineage, you used this functions:
assoRes <- associationTest(sce)

However, when I print the output assoRes, I cannot see which lineage the P value of each gene is correlated too(screenshot of the output table attached).Ideally I would like to see the p value for gene X for both lineage 1 and 2 in this case. Just would like to ask your opinion on this, is there any way to do this? Thanks very much!
![Screenshot 2021-04-02 at 11 01 23](https://user-images.githubusercontent.com/43444815/113432323-ce4bef00-93a2-11eb-9e06-7a83072fa42f.png)

**Comment by HectorRDB** [comment]
Hi @liuweihanty 
Thanks.  You can use the `lineages` argument to ask to lineage-level statistics. 
Specifically, setting `lineages=TRUE` will return what you want. 

If you multiply the number of comparisons, be sure to correct the p-values for proper multiple testing. 

Best

**Comment by liuweihanty** [comment]
Thanks @HectorRDB ! I see, because in the toturial it didn;t specify lineage = TRUE so it's testing for global, not lineage specific.
