### ISSUE TITLE
Inconsistency between scaled expression values from tradeSeq and normalised expression values

### ISSUE THREAD

**Issue by lucygarner** [statOmics/tradeSeq#142]
Hi,

I have a strange result that I am trying to figure out.  I have run fitGAM, followed by clusterExpression patterns to identify modules of genes showing similar patterns of expression over pseudotime. The input to `clusterExpressionPatterns` was the top 200 genes identified to vary over pseudotime using random forest regression.  I have then taken the gene expression values from `gene_clusters[["yhatScaled"]]`  to plot the expression of genes within different clusters over pseudotime.

I have a cluster of ribosomal genes that appears to increase in expression over pseudotime according to the yhatScaled expression values (cluster 9), however if I instead plot the original normalised expression values for these genes, they appear to decrease in expression over pseudotime.  The pattern of the other modules seems to fit fine so I am wondering what could be going on here?!

The expression matrix that I passed to `fitGAM` was normalised counts.

```
set.seed(7)
fit_gam <- fitGAM(counts = expression,
                  pseudotime = as.matrix(pseudotime_matrix),
                  cellWeights = as.matrix(cell_weights),
                  nknots = 6)

gene_clusters <- clusterExpressionPatterns(fit_gam, 
                                           nPoints = 100, 
                                           genes = top_200)
```

The heatmaps below contain the module expression values, which are just calculated as the average expression of the genes in the cluster at each timepoint.

Scaled values from `clusterExpressionPatterns` using fit_gam input:
![tradeseq_scaled_values](https://user-images.githubusercontent.com/22564745/116212321-9f742f00-a73c-11eb-9846-243a6c750c8c.jpeg)

Normalised expression values:
![normalised_expression_values](https://user-images.githubusercontent.com/22564745/116212510-cdf20a00-a73c-11eb-8cda-acc9c3f3e5e3.jpeg)

Any help would be greatly appreciated!

Best wishes,
Lucy

**Comment by koenvandenberge** [comment]
Hi @lucygarner,

Thank you for reaching out.

If I understand correctly, you are fitting the models using `tradeSeq`, are selecting a subset of 200 genes using some external method, and are then clustering these 200 genes using `clusterExpressionPatterns`. The first heatmap you show I assume is the average `gene_clusters[["yhatScaled"]]` for all genes in each of the clusters, where the across-gene average is increasing in cluster 9. When you plot the average of the "original normalised expression values" for these same genes it is, instead, decreasing for cluster 9.

Note that the `yhatScaled` values represent grid points along the fitted smoothers for each lineage, which are subsequently scaled separately for each gene to have zero mean and variance of 1. The fitted smoothers also rely on TMM normalization to account for differences in sequencing depth and RNA composition between cells. 

It is unclear to me, however, how your "original normalised expression values" have been derived. Could you tell us how you got these?
Depending on how these were calculated, it could be that, for example, a gene contributing high-count outliers (which is quite common common for ribosomal genes) may be driving the discrepancy, or, that one visualization corrects for sequencing depth while the other does not.

**Comment by lucygarner** [comment]
Thank you for the response.  Yes, I think you have understood it correctly.  The "original normalised expression values" are derived from Seurat (`NormalizeData()` function), so they should account for differences in sequencing depth between the samples. 

Before I send further information, can I just check, is it best to perform `fitGAM` on the raw or normalised data?

Best wishes,
Lucy

**Comment by koenvandenberge** [comment]
Thanks. I'll have to look at what Seurat's `NormalizeData` function does. What's the Seurat version you've been using?

`fitGAM` assumes a count model and therefore it is required to provide the raw data (i.e., the expression counts).

**Comment by lucygarner** [comment]
Thanks, that would be great - the Seurat version that I have been using is 3.2.3, but I am actually using the SCTransform normalised data for the figures above and the figures below.  

I have looked into this a bit more and I think it must be something to do with the normalisation strategies.  If I plot out the expression of the individual genes in the module using the tradeSeq scaled values (changed a bit from above so ignore those), I get the following:

![image](https://user-images.githubusercontent.com/22564745/116525342-52c15d00-a8d0-11eb-82d1-3f94ad4fc4b4.png)

However, if I use the SCTransform normalised expression values from Seurat, scaled to lie between 0 and 1, I get the following:

![image](https://user-images.githubusercontent.com/22564745/116525633-a03dca00-a8d0-11eb-9e45-966deced9174.png)

If I plot out the raw values of one of these genes (RPL30) using the plotSmoothers function, I get:

![image](https://user-images.githubusercontent.com/22564745/116526360-6de09c80-a8d1-11eb-9d99-089d507e95c1.png)

Can you think of a reason why this might be?  These genes have high raw counts - do you think this might be something to do with it?  The cells towards the end of my trajectory are the most activated ones, and therefore likely to be largest - this could explain why the raw counts for the ribosomal genes are increasing.

Does this suggest that the results from tradeSeq might be unreliable for high count genes?

Many thanks,
Lucy

**Comment by koenvandenberge** [comment]
Thanks for these visualizations, these are incredibly helpful! 

It seems to me that your pseudotime is associated with the sequencing depth (i.e., the total expression counts for each cell). Could you please provide an additional visualization where you plot the log sequencing as a function of pseudotime for that lineage?

This would explain the increasing raw gene expression values, but the estimated smoother that's flat / somewhat decreasing. `SCTransform` also relies on the sequencing depth to normalize (but in a different way as `tradeSeq`), which would explain this.

It does look like the scaling we are doing to cluster the smoothers is inflating the estimated expression patterns as, at least for the RPL30 gene, there is little variability in the estimated mean expression along pseudotime. You could also try clustering without scaling, by extracting the smoother using `predictSmooth` and using it with any clustering method, as described in the vignette [here](http://bioconductor.org/packages/devel/bioc/vignettes/tradeSeq/inst/doc/tradeSeq.html#extracting-fitted-values-to-use-with-any-clustering-method).

To me, it does not suggest that the results for `tradeSeq` are unreliable for high count genes, but that you'd have to think carefully about normalization. If there is indeed an association between sequencing depth and pseudotime, it will not be appropriate to plot the raw gene expression counts as a function of pseudotime to investigate the patterns as most will likely be increasing (if sequencing depth is positively correlated with pseudotime).

**Comment by lucygarner** [comment]
Yes, you are correct, the pseudotime trajectory is associated with sequencing depth.  However I don't think this is surprising in my case because it is an activation trajectory, so the cells will be getting larger and more transcriptionally active over pseudotime.  However, I would expect this to be largely dealt with in the count normalisation process?

![image](https://user-images.githubusercontent.com/22564745/116531193-cf573a00-a8d6-11eb-8f3e-f35ec6e9b2a1.png)

log1p depth:
![image](https://user-images.githubusercontent.com/22564745/116531686-5b696180-a8d7-11eb-9adb-2a8d0de52fe4.png)

Where in the tradeSeq process do you take into account the sequencing depth?

**Comment by koenvandenberge** [comment]
> Yes, you are correct, the pseudotime trajectory is associated with sequencing depth. However I don't think this is surprising in my case because it is an activation trajectory, so the cells will be getting larger and more transcriptionally active over pseudotime. However, I would expect this to be largely dealt with in the count normalisation process?

Yes, this is indeed being dealt with, which is in fact why the smoothers are flat but the marginal gene expression counts are increasing. In a typical RNA-seq experiment, we are interested in finding differences in the expected expression fractions (i.e., expected gene expression counts divided by a normalized sequencing depth or size factor). Indeed, since the data are compositional, we would expect that increases in the expected expression fraction correspond to increased concentration of the respective mRNA molecules in the cell. In your case, for example, the RPL30 gene's mRNA concentration doesn't seem to change a lot as a function of pseudotime, even though the total transcriptional output of your cells is changing.
This doesn't seem to be picked up by the random forest method you've used, possibly because you have provided the raw (or some transformed) gene expression values, while the expression fractions could be a better approach.

> Where in the tradeSeq process do you take into account the sequencing depth? I agree that calculations performed on the raw counts are unlikely to be meaningful in my case.

In `tradeSeq`, we rely on TMM normalization (see code [here](https://github.com/statOmics/tradeSeq/blob/master/R/fitGAM.R#L73)) from the `edgeR` package. You can override this by providing an offset yourself to `fitGAM`, using the `offset` argument.

**Comment by lucygarner** [comment]
Yes, I am confused as to why this gene was picked up by the random forest, as data normalised using the `NormalizeData` function (feature counts for each cell are divided by the total counts for that cell and multiplied by the scale.factor) from Seurat was used, so this should take into account the change in library size upon cell activation/over pseudotime.  This was the method that I used: https://github.com/rcannood/SCORPIUS/blob/master/R/gene_importances.R 

@rcannood, I was wondering whether you might have thoughts on why the `gene_importances` function is picking up these ribosomal genes, when they don't seem to really be changing in expression over pseudotime.

**Comment by koenvandenberge** [comment]
Did you check if other genes should be more prone to get picked up by any method, based on the normalized data? It seems to me that the (difference in) normalization is to blame, not necessarily the random forest.
If you'd like to avoid this inconsistency, you can also provide TMM-normalized counts as input to the random forest.

**Comment by lucygarner** [comment]
In the two methods of normalisation that I have used, these ribosomal genes seem to go down in the stimulated conditions.

`NormalizeData()`:
![image](https://user-images.githubusercontent.com/22564745/116734649-6dd1c100-a9e5-11eb-9291-c8db59ccb7cd.png)

`scTransform()`:
![image](https://user-images.githubusercontent.com/22564745/116734654-70341b00-a9e5-11eb-832e-695ab14e7202.png)

Is there any reason why you think TMM normalisation might be a better approach than these methods? I thought that `scTransform()` particularly might be better as it was designed specifically for normalisation of single-cell data?  I think one of the assumptions of TMM is that most genes are not differentially expressed which might not hold true for my stimulation data (~4,000 genes DE at FDR < 0.05 in both stimulation conditions).

**Comment by koenvandenberge** [comment]
The main reason to use TMM normalization here is that this aligns with how `tradeSeq` works. I am not trying to claim that TMM works better than other normalization methods. It is correct that TMM assumes most genes are not DE.
In `tradeSeq`, we cannot work with data normalized using either `NormalizeData` or `SCTransform` because these are not counts.  If you'd like to use these methods, I would suggest to use a different approach to fit the smoothers.

**Comment by lucygarner** [comment]
Thank you, so I can use the raw data as input for tradeSeq but I need to be aware that the normalisation using TMM might not be appropriate in my case?

**Comment by koenvandenberge** [comment]
Yes. In your case, I would generally recommend to explore which normalization works best for your dataset using, for example, known biology based on expected gene expression patterns, or a separation of the cells in a reduced dimensional space that reflects biological rather than technical variability.

Hope this was helpful, and let us know if you encounter any further issues.
