### ISSUE TITLE
Running tradeSeq on subset of curves of slingshot

### ISSUE THREAD

**Issue by eonurk** [statOmics/tradeSeq#144]
Hi,

Thanks for the package, it is really helpful!

I was wondering how to run `fitGAM` function on only for a subset of curves obtained from slingshot? Below, you can see the UMAP where I showed 6 different trajectories but I want to run fitGAM function for 3 of them which are the ones that goes towards the right side or ahead starting from the bottom.
<img width="613" alt="Screen Shot 2021-04-30 at 2 33 23 PM" src="https://user-images.githubusercontent.com/22842930/116695552-10c41400-a9c1-11eb-8448-0136b2f1a030.png">

Should I just start from beginning, subsetting the cells, running umap etc... or is there a way to select those curves from the slingshot object and run the function on those selected ones? 

And another question I have is that when you have more curves the temporal expression values which are plotted via `plotSmoothers` function will shrink, right? For instance, below I show CD34 expression levels, if I had 3 curves instead of 6, I would get higher expression levels at the start?

<img width="711" alt="resim" src="https://user-images.githubusercontent.com/22842930/116697044-f9862600-a9c2-11eb-9c17-90e9b943ee37.png">

Thank you very much!

**Comment by HectorRDB** [comment]
Hi @eonurk 
First up, I will trust that you have biological backing for those lineages. Just looking at reduced space, it looks like there is probably an over-fitting here. In particular, I would be hesitant to fit a full trajectory to your entire dataset since you seem to have distinct groups. However, it is hard to know without biological insight.

That being said, to run slingshot on just the three lineages, you will have to extract the need info and subset the columns. You can use the `slingPseudotime` and `slingCurveWeights` function from the slingshot package, and, after subsetting, use the `pseudotime` and `cellWeights` arguments for fitGam (as well as the counts argument).
Best

**Comment by eonurk** [comment]
Hi again, 

Thank you for the swift response! Yes, those lineages going left does not actually make a lot of sense, thus, I want to select the ones going towards the right side. 

When I extract pseudotime and weights there are NA values, which throws an error while running the fitgam function. 

> Error in .local(counts, ...) : 
>   The pseudotimes contain NA values, and these cannot be used for GAM fitting.

**Comment by HectorRDB** [comment]
Hi @eonurk 
A couple points:
First, be sure to have the `na = FALSE` argument for the `slingPseudotime` function.

Secondly, you can reduce the `resolution` parameter of the clustering step for Seurat, which will give you less clusters and is less likely to reflect in overfitting.

Hope that helps,
Best

**Comment by eonurk** [comment]
Hi @HectorRDB,

That solved the `NA` problem, however when I subset the curves, it gives me the following error:

```r
# you should make it a slingshot object otherwise, it won't work. 
pseudotimes <- slingPseudotime(SlingshotDataSet(sce), na = FALSE) [,c(3,4,6)]
cellweights <- slingCurveWeights(sce)[,c(3,4,6)] 

sce.gam2 <- fitGAM(counts = counts, pseudotime = pseudotimes, cellWeights = cellweights, 
                   nknots = 5, verbose = T, parallel=TRUE, BPPARAM = BPPARAM, genes =intersected.genes)
```

>  Error in .assignCells(cellWeights) : Some cells have no positive cell weights.

It is working as expected when I don't subset them though. 

Thank you for the Seurat trick by the way!

**Comment by HectorRDB** [comment]
Hi,
Some cells have zero weights in all three lineages you selected. You will need to filter them out before running tradeSeq (both the cellweights and pseudotime). 
Best

**Comment by eonurk** [comment]
That worked out pretty nice for me, thank you very much @HectorRDB. 
Closing this one.

**Comment by AndreaYCT** [comment]
Hi, @HectorRDB, 

I am trying to subset Slingshot by treatment group to run TradeSeq:
` subset_Slingshot <- Slingshot[Slingshot$Exp == "DMSO", ]
`
but it doesn't work. I would like to know what's the correct code for this! 

Many thanks!

> Hi @eonurk First up, I will trust that you have biological backing for those lineages. Just looking at reduced space, it looks like there is probably an over-fitting here. In particular, I would be hesitant to fit a full trajectory to your entire dataset since you seem to have distinct groups. However, it is hard to know without biological insight.
> 
> That being said, to run slingshot on just the three lineages, you will have to extract the need info and subset the columns. You can use the `slingPseudotime` and `slingCurveWeights` function from the slingshot package, and, after subsetting, use the `pseudotime` and `cellWeights` arguments for fitGam (as well as the counts argument). Best
