### ISSUE TITLE
tradeSeq crashing due to memory requirements

### ISSUE THREAD

**Issue by lucygarner** [statOmics/tradeSeq#145]
Hi,

I have tried running tradeSeq downstream of Slingshot, but it keeps crashing due to reaching memory limits.  I have been using 24 cores and 600 GB total memory, which already seems like a lot to me.

```
multicore <- MulticoreParam(workers = 24)

fit_gam <- fitGAM(counts = expression, sds = sample_sds, nknots = 6,
                  parallel = TRUE, BPPARAM = multicore)
```

`sample_sds` is my SlingshotDataSet object and `expression` is a matrix of raw expression counts (~17,000 genes, ~25,000 cells).  What sort of memory requirements would you expect for this?

Sorry if I have missed this in the paper or vignette, but do you perform filtering for highly expressed genes, or use another filtering strategy, to reduce the size of your count matrices?

Best wishes,
Lucy

**Comment by HectorRDB** [comment]
Hi @lucygarner 
Depending on how your cluster is configured, if the cores share the same RAM then increasing the number of cores will more likely flood the memory.
Instead, I would recommend you request a full node (i.e. all 24 cores) and only use a subset (let's say 6) for tradeSeq. Could you try this with a subset of the genes and let us know if it works, using the `fitGAM` argument `genes=1:100`.

We have indeed usually performed filtering for tradeSeq. Memory requirement is very hard to estimate in general but I am surprised that it flooded the memory if you have 600GB of RAM. We usually filter down to 10000 genes using either `Seurat::FindVariableFeatures` or removing the genes where there is less than x counts in y% of the samples.

**Comment by lucygarner** [comment]
Thank you, this worked fine, but it just keeps crashing when I include more cells.  What sort of memory requirements would normally see?

**Comment by HectorRDB** [comment]
Ok that is weird... The size of the stored info is not that great so if it works with 100, it should work with more. Did you try with the top 5000 genes or did that also crash?

**Comment by lucygarner** [comment]
Hi @HectorRDB,

Just to update on this - I managed to get the code to run in the end with 24 cores and 500 GB memory.  This is for ~25,000 cells.

Best wishes,
Lucy

**Comment by HectorRDB** [comment]
Thanks!
