### ISSUE TITLE
Setting number of cores

### ISSUE THREAD

**Issue by elPiac** [statOmics/tradeSeq#147]
Hi, I' m trying to run DE on pseudotime analysies with Tradeseq. 
I have a SingleCellExperiment object on which I run Slingshot for Pseudotime (5 lineges found, Description of the Object below).

My PROBLEM is that I'm using a shared server so i need to use only a limitated number of cores, but I can't set the number of cores to use.

Specifically I set Parallel = FALSE and set on 10 the number of cores  with command :

"BPPARAM <- BiocParallel::MulticoreParam(workers = 10)" 

When I run the function fitGAM(), I see with htop that it uses a number much  bigger than 10 cores to analysing, and the stimated time is like 7 hours.

Do you have any suggestions as to where this problem might come from?

Best wishes,
Gabriele

```
> Sling_obj
```

class: SingleCellExperiment 
dim: 15652 568 
metadata(0):
assays(2): counts logcounts
rownames(15652): Dusp16 Olfr366 ... Nrg1-II 1700030J22Rik
rowData names(5): vst.mean vst.variance vst.variance.expected vst.variance.standardized vst.variable
colnames(568): C55_A3_L1_8w_RepB_Batch1 C55_A4_L1_8w_RepB_Batch1 ... C82_H8_L1_1w_RepG_Batch2
  C82_H9_L1_1w_RepG_Batch2
colData names(18): orig.ident nCount_RNA ... slingPseudotime_4 slingPseudotime_5
reducedDimNames(4): PCA CSS TSNE UMAP
altExpNames(0):

```
countMatrix <- as.matrix(assay(Sling_obj, "counts"))
slingshot <- SlingshotDataSet(Sling_obj)
genes <- L1_final@assays$RNA@var.features

BPPARAM <- BiocParallel::MulticoreParam(workers = 10)

```

class: MulticoreParam
  bpisup: FALSE; bpnworkers: 10; bptasks: 0; bpjobname: BPJOB
  bplog: FALSE; bpthreshold: INFO; bpstopOnError: TRUE
  bpRNGseed: ; bptimeout: 2592000; bpprogressbar: FALSE
  bpexportglobals: TRUE
  bplogdir: NA
  bpresultdir: NA
  cluster type: FORK

```
GAM <- fitGAM(counts = countMatrix,
              sds = slingshot, 
              nknots = 6,
              genes = genes,
              parallel = FALSE,
              BPPARAM = BPPARAM,
              verbose = TRUE)
```

**Comment by koenvandenberge** [comment]
Hi @elPiac,

If you set `parallel = FALSE`, then the `BPPARAM` argument is actually ignored in `fitGAM` and by default it only uses one core (it will just use a basic `lapply` loop). It should not be happening that you are using such a high number of cores with the arguments you're providing.
These high number of cores should therefore not be coming from `fitGAM`, maybe they could be coming from previous functions where you are allowing parallelization?

**Comment by dfermin** [comment]
I can verify @elPiac  experience.
I'm using fitGAM in a multi-core machine and it is not adhering to the requested CPU limits.

Here is my sample code
```
Dataset <- readRDS("cellStateData.rds")
Dataset <- as.SingleCellExperiment(Dataset, assay = "RNA")

Dataset <- slingshot(Dataset, reducedDim = 'UMAP', clusterLabels = colData(Dataset)$celltype, approx_points = FALSE)

workers <- BiocParallel::MulticoreParam(workers=16)
Dataset1 <- fitGAM(Dataset, verbose=TRUE, parallel=TRUE, BPPARAM=workers)
```

I'm running this on a 64 core RHEL server.
I'm trying to restrict it to just 16 cores so other users in our group can continue to work.

When it gets to the `fitGAM` line the  command uses all 64 cores. 
There are no previous commands that might use multiple cores.

I've tried different renditions of the BPPARAM argument all to no avail.
The fitGAM function is definitely the culprit and it is ignoring the `BPPARAM` argument and consuming all available cores.

Do you have any suggestions for fixing this?
