### ISSUE TITLE
a question on setting knots for bifurcation analysis

### ISSUE THREAD

**Issue by liuweihanty** [statOmics/tradeSeq#148]
Hi There, may I ask a clarification question on this part of the Vignette(screenshot attached). Here the tutorial selected knot 1 and 2, but I'm a bit confused of which knots on the graph are 1 and 2 in this case.(I labeled the three early knots as a,b, and c), would you mind clarify? Thank you so much in advance!

![Screenshot 2021-05-19 at 23 52 35](https://user-images.githubusercontent.com/43444815/118921509-e7cadb00-b8fd-11eb-9250-c0d92e4a93a9.png)

**Comment by koenvandenberge** [comment]
Hi,

In this trajectory, knot b is the starting point so it is what we refer to as knot 1. 
Both knots a and c in your scheme are referred to as knot 2 in lineage 1 and 2, respectively. Note that lineage 2 has 5 knots while lineage 1 has 6 knots. While different lineages may have different number of knots, the position of the knots will be identical in terms of pseudotime, so knot 2 could be at a pseudotime value of, say, `0.25`, for both lineage 1 and 2.

The `earlyDETest` then assesses differential expression patterns between lineage 1 and 2 for each gene, using only the smooth functions between knots 1 and 2.

Hope this helps and feel free to let me know if anything isn't clear.

**Comment by liuweihanty** [comment]
Hi @koenvandenberge , thank you so much for your explanation, that's very clear!
