### ISSUE TITLE
Slingshot and tradeSeq incompatibility 

### ISSUE THREAD

**Issue by HectorRDB** [statOmics/tradeSeq#149]
With the new slingshot version, a `pseudoTimeOrdering` object called `slingshot` is added to the colData. However, when running `fitGam` on a `singlecellExperiment` object, we replace that `slingshot` object, which is not ok.

Lots of functions we need to replace, I'll replace the slinghsot column by a crv column! 

But we may have some issues of backward compatibilites. Should we add a silent converter at the beginning of each of the functions?

**Comment by HectorRDB** [comment]
I'll rename the `slingshot` DFrame by `crv`, it might also be more generalizable for the future...

**Comment by kmshort** [comment]
I've had problems already and rolled back to earlier Slingshot and tradeSeq; sticking with that for now.

**Comment by HectorRDB** [comment]
Hi @kmshort 
That should be solved now with the latest versions of tradeSeq. If you have time to beta test at some point, it would be greatly appreciated!

**Comment by kmshort** [comment]
Hi @HectorRDB 
Unfortunately, I'm trying to wrap up a large body of work - using Slingshot and tradeSeq (last biocondutor versions). I don't really want to start delving into it just now. But I will soon enough.
regards.

**Comment by HectorRDB** [comment]
Thanks @kmshort 
Users like you really help us make a better tool out of tradeSeq

**Comment by Erinke89** [comment]
Hello, thanks for this update. I unfortunately have this same issue on tradeSeq 1.4.0, is this too old to have the issue fixed? It seems the most uptodate version for my setting (R 4.0.0, Bioconductor 3.12), I can't install the development version because of the dependency on TrajectoryUtils. Does this mean I can only circumvent the issue by updating R?
