### ISSUE TITLE
too many clusters for gene expression pattern clustering

### ISSUE THREAD

**Issue by lixin4306ren** [statOmics/tradeSeq#15]
Hi, thanks for providing such a useful package. I have run `tradeseq` on my data and got 60 clusters for primary clustering results. How can I reduce this number by just some parameters? I prefer a relatively small clusters number for my downstream analysis. Thank you.

Xin

**Comment by HectorRDB** [comment]
Hi,
There are two things you could do:
1/ Only cluster on a set of significant genes (like the top 200 from one of `tradeSeq`'s test)
2/ The clustering function is just a wrapper around `clusterExperiment::RSEC` and you can pass options to this function. You can refer to the help file or the [clusterExperiment vignette](https://bioconductor.org/packages/release/bioc/vignettes/clusterExperiment/inst/doc/clusterExperimentTutorial.html) for more information. You can for example decrease the `consensusProportion` parameter.

**Comment by lixin4306ren** [comment]
Thank you for your quick reply. I tried to pass `clusterFunction="kmeans"` to `clusterExpressionPatterns`, but it didn't work and still performed default `hierarchical01` method. I checked the code in file `clusterExpressionPatterns.R`. It seems missing the `...` in line 87-91.
