### ISSUE TITLE
evaluateK failed

### ISSUE THREAD

**Issue by Tianran1** [statOmics/tradeSeq#153]
Error in quantile.default(tAll, probs = (0:(nknots - 1))/(nknots - 1)): missing values and NaN's not allowed if 'na.rm' is FALSE
Traceback:

1. evaluateK(counts = counts, pseudotime = pseudotime, cellWeights = cellWeights, 
 .     conditions = factor(df$tissue), nGenes = 300, k = 3:7, parallel = TRUE, 
 .     BPPARAM = BPPARAM)
2. evaluateK(counts = counts, pseudotime = pseudotime, cellWeights = cellWeights, 
 .     conditions = factor(df$tissue), nGenes = 300, k = 3:7, parallel = TRUE, 
 .     BPPARAM = BPPARAM)
3. .local(counts, ...)
4. .evaluateK(counts = counts, k = k, U = U, pseudotime = pseudotime, 
 .     cellWeights = cellWeights, plot = plot, nGenes = nGenes, 
 .     weights = weights, offset = offset, verbose = verbose, conditions = conditions, 
 .     parallel = parallel, BPPARAM = BPPARAM, control = control, 
 .     family = family, gcv = gcv, ...)
5. lapply(kList, function(currK) {
 .     gamAIC <- .fitGAM(counts = countSub, U = U, pseudotime = pseudotime, 
 .         cellWeights = cellWeights, conditions = conditions, nknots = currK, 
 .         verbose = verbose, sce = FALSE, parallel = parallel, 
 .         BPPARAM = BPPARAM, weights = weightSub, offset = offset, 
 .         aic = TRUE, family = family, gcv = gcv, ...)
 . })
6. FUN(X[[i]], ...)
7. .fitGAM(counts = countSub, U = U, pseudotime = pseudotime, cellWeights = cellWeights, 
 .     conditions = conditions, nknots = currK, verbose = verbose, 
 .     sce = FALSE, parallel = parallel, BPPARAM = BPPARAM, weights = weightSub, 
 .     offset = offset, aic = TRUE, family = family, gcv = gcv, 
 .     ...)
8. .findKnots(nknots, pseudotime, wSamp)
9. stats::quantile(tAll, probs = (0:(nknots - 1))/(nknots - 1))
10. quantile.default(tAll, probs = (0:(nknots - 1))/(nknots - 1))
11. stop("missing values and NaN's not allowed if 'na.rm' is FALSE")

Do you know what is wrong here?
Thanks

**Comment by Tianran1** [comment]
Sorry, I know the reason and it now runs successfully. But the results are not expected. I got all NAs for all K. And I don't know what happens since it doesn't report any errors, just a warning message:

Warning message in .findKnots(nknots, pseudotime, wSamp):
“Impossible to place a knot at all endpoints.Increase the number of knots to avoid this issue.”

**Comment by koenvandenberge** [comment]
Hi @Tianran1 

The first error seems to stem from `NA` values in the pseudotime.

For the second error, without knowing any details about the data that is provided as input, we cannot diagnose why you'd get `NA` values. The warning message should be unrelated to the `NA` values. 
Please make sure that there are no `NA` or `NaN` values in the input (counts, pseudotime and cellWeights), and I'd also recommend working with the latest version of `tradeSeq` if you are not doing so.

If the problem still persists, it would be great if you could share some more details about the data you're working with, or share a working reproducible example.

Best,
Koen
