### ISSUE TITLE
startVsEndTest, diffEndTest, patternTest seperate condition

### ISSUE THREAD

**Issue by Tianran1** [statOmics/tradeSeq#154]
Hi,

My data contains two conditions and the lineages were separately constructed. But I found for startVsEndTest, diffEndTest and patternTest these three tests, the results are not separated by conditions. So Must I separate the data and use the test independently? Maybe you could consider adding this key to the test.

Best,
Tianran

**Comment by HectorRDB** [comment]
Hi @Tianran1,
I think there is some misunderstanding regarding what is a lineage or a condition. A lineage might or might not be shared between conditions. 
As such that tests you listed above will look at DE for genes along or between lineages. If more than one condition is present, then we perform an omnibus test across conditions. 
If you want to compare conditions, I would refer to the `conditionTest` which you can perform either in each lineage or between lineages. 
Hope this helps
Best

**Comment by Tianran1** [comment]
Hi,

Yes. I know what is lineage or condition. I mean, for example, the startVsEndTest, it just gives the result for each lineage from all cells, which is different from the result of associationTest. The associationTest gives the result of each lineage by each condition, so I got *_lineage1_condition1, *_lineage1_condition2, *_lineage2_condition1, *_lineage2_condition2.

Best,
Tianran
