### ISSUE TITLE
pairwise =TRUE in conditionTest

### ISSUE THREAD

**Issue by FADHLyemen** [statOmics/tradeSeq#165]
If you'd like to request new features or changes, please fill in relevant sections in the template below.

**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

This is the output from conditionTest
![image](https://user-images.githubusercontent.com/23288387/129794215-1138e28b-2554-48d7-9ab2-af371eb65562.png)

how did you compute:
<html>
<body>

waldStat | df | pvalue
-- | -- | --

<br class="Apple-interchange-newline">
</body>
</html>

second, how could I know my 1 vs 2, 2 vs 3 in my data set?

**Comment by FADHLyemen** [comment]
@koenvandenberge 
I am totally confused about the difference between conditionTest and associationTest they have same output:
![image](https://user-images.githubusercontent.com/23288387/131254222-82ba1a32-c211-4cdd-b42f-c90501f04989.png)


![image](https://user-images.githubusercontent.com/23288387/131255100-387fa10b-228a-434c-bda4-de900ae1fc9e.png)


so what is the difference between these two functions?

**Comment by koenvandenberge** [comment]
> which means condition 1 is HC, condition 2 is T2D_NO and condition 3 is T2D_YES. Am I correct?

Yes, this is correct.
