### ISSUE TITLE
how to plot cell type as column annotation

### ISSUE THREAD

**Issue by FADHLyemen** [statOmics/tradeSeq#166]
If you'd like to request new features or changes, please fill in relevant sections in the template below.

**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
how to edit the below code to get something like the below:
```
yhatSmooth <- predictSmooth(sce, gene = mockGenes, nPoints = 50, tidy = FALSE)
heatSmooth <- pheatmap(t(scale(t(yhatSmooth[, 1:50]))),
                       cluster_cols = FALSE,
                       show_rownames = FALSE, 
                       show_colnames = FALSE)
```
I mean how to plot cell types in the column annotations?
![image](https://user-images.githubusercontent.com/23288387/131037712-901d7a33-6174-43aa-a0ca-538ece341725.png)

**Comment by FADHLyemen** [comment]
@koenvandenberge 
the problem is not with pheatmap, the problem is with the structure of the data from predcitSmoth function:
![image](https://user-images.githubusercontent.com/23288387/131253925-11368605-ca97-41be-aa2f-372e56ff063b.png)


imagine, I only interested on only lineage 1 and one condition and I select 50 points so the dim of my matrix is number of genes x 50.  How to map these 50 points to the cell type. this is my problem. is the npoint is similar to pesudotime or sampling of it? 
if the columns are pesudotime, I can plot celltype as column annotation, but her column are npoints which 50 points.

I hope you have solution for it.

**Comment by koenvandenberge** [comment]
If you would like to use `predictSmooth` for this, you should decide on a reasonable pseudotime boundary where one cell type starts and the previous one stops, and use that to implement the column annotations. 
If you set the `tidy=TRUE` argument in `predictSmooth`, you will be given a pseudotime value accompanying each estimate you could use for that.

Alternatively, `preditCells` returns the fitted value for each cell. However, this will be noisier to plot the average gene expression effects and thus less amenable to visualization.
