### ISSUE TITLE
Error in result[[njob]] <- value :    attempt to select less than one element in OneIndex

### ISSUE THREAD

**Issue by FADHLyemen** [statOmics/tradeSeq#171]
Before you submit this issue it may be worth updating `tradeSeq` to the latest version to make sure that your issue has not already been fixed in the latest release. To update to the latest development version, please run:

```
devtools::install_github("statOmics/tradeSeq")
```

If your issue persists, then please submit this bug report.

**Describe the bug**

**To Reproduce**
If possible, describe steps to reproduce the bug you are facing by, e.g., providing a minimal working example. Feel free to share (a subset of) your data that reproduces the error.

**Session info**
Provide your the output of `sessionInfo()`, if possible.
Hi, 
I got the below error when I run
appreciate your help
```
library(tradeSeq)
BPPARAM <- BiocParallel::bpparam()
BPPARAM 
BPPARAM$workers <- 10 # use 10 cores
BPPARAM 
library(SingleCellExperiment)
sce_subset <- fitGAM(counts=sce_subset@assays@data$counts,pseudotime =t,cellWeights=w, 
                     conditions = factor(colData(sce_subset)$sampletype),
      genes = rownames(sce_subset)[rownames(sce_subset) %in% hvg_genes_Tcells[1:100] ],
               BPPARAM = BPPARAM,nknots=20,parallel = TRUE)


```

I got 

```
Error in result[[njob]] <- value : 
  attempt to select less than one element in OneIndex
In addition: Warning messages:
1: In .findKnots(nknots, pseudotime, wSamp) :
  Impossible to place a knot at all endpoints.Increase the number of knots to avoid this issue.
2: In parallel::mccollect(wait = FALSE, timeout = 1) :
  1 parallel job did not deliver a result
```

**Comment by HectorRDB** [comment]
Hi @FADHLyemen 
The parallelization can sometimes fail, and it is very hard to diagnose. I can only suggest re-trying and seeing if the problem persits, or running without parallelization.
