### ISSUE TITLE
Testing for the expression of isoforms over pseudotime

### ISSUE THREAD

**Issue by Haikelnb** [statOmics/tradeSeq#172]
Hello and thanks for developing tradeSeq!

We have been using tradeSeq for our scRNA-seq data but would now like to expand our analyses to testing whether two isoforms of the same gene are expressed similarly throughout pseudotime (i.e., do they covary). Is there a simple way to implement such a test in tradeSeq?

Thanks for you help!

**Comment by Haikelnb** [comment]
Thanks for your response @koenvandenberge! 

I believe we are more interested in the first; to test for similar “timing” of expression (regardless of the absolute value of expression).

**Comment by koenvandenberge** [comment]
Thanks! So you're interested in finding two/multiple isoforms from the same gene that may have any expression pattern, as long as the expression pattern is the same, right? Or are you more specifically interested in specific patterns?

This doesn't sound like an easy question to me. First of all, we would have to define what it means for two isoforms to be 'expressed similarly', which would likely reduce to finding a region of fold changes that are deemed 'irrelevant'. 
Once we have such an equivalence region, we might have to test for equivalence using the two-one sided tests (TOST) principle, where we test if the observed fold-change is significantly lower than the upper bound of our equivalence region, and significantly higher than the lower bound of our equivalence region. If the result is yes to both of these questions, across all pseudotimes we are looking at, we may consider the isoforms to be equivalently expressed.

**Comment by koenvandenberge** [comment]
Closing after a month of inactivity, please feel free to comment and reopen if you are still working on this or if what I said was not what you're looking for.
