### ISSUE TITLE
Error in matrix(pseudotime, ncol = 1) when running plotSmoothers 

### ISSUE THREAD

**Issue by ylxing001** [statOmics/tradeSeq#173]
**plotSmoothers - Error in matrix(pseudotime, ncol = 1) : 'data' must be of a vector type, was 'NULL'**

I used plotSmoothers to plot gene expression along the pseudotime from "sce1" as the object containing all genes after using fitGAM function. 

plotSmoothers(sce1, assays(sce1)$counts,
              gene = "Gene",
              alpha = 1, border = TRUE)

However, it returned with the following error:
Error in matrix(pseudotime, ncol = 1) : 
  'data' must be of a vector type, was 'NULL'

All the counts, pseudotime and cellWeights matrices have matched dimensions. I also tried to use plotSmoothers with previous smaller "sce" object which contains only 300 genes and it worked. But not for the larger "sce1" object. 

> dim(counts)
[1] 8934  652
> dim(pseudotime)
[1] 652   4
> dim(cellWeights)
[1] 652   4
> dim(sce)
[1] 300 652
> dim(sce1)
[1] 8934  652

Could you please help me with this? 

Thanks for your help in advance.

**Comment by ylxing001** [comment]
Hi @HectorRDB 
You are absolutely right. I rerun the codes using the latest version of TradeSeq and it worked. Thank you!

**Comment by rmenafra** [comment]
Hi @HectorRDB 
I'm having the same issue, specifically I saved the results of fitGAM in a .RDS file and reload that in my .Rmd (to reduce computing time), but this is the error I get.
I'm using the latest Tradeseq and already tried the suggestion above. The dataset is not the one from the tutorial but my own. Would there be a reason not to save the result of fitGAM and then reload it? Thank you

**Comment by HectorRDB** [comment]
Hi @rmenafra 
Just to be sure: you used the most recent version of tradeSeq both to generate the object and to then analyze it? 
In general, there should be no issue to saving the FitGam object and then re-loading it. 
Do you have an issue just with plotSmoothers or also with other functions.

**Comment by rmenafra** [comment]
Hi Hector, thanks for the quick reply, yes I recreated the object after the update, and the first function that gave me issues is plotSmoothers. Is there a way to verify which version was used from the RDS object?

**Comment by HectorRDB** [comment]
No unfortunalty that is not something that we store (also maybe we should @koenvandenberge ).
Is the gene that poses an issue the same with `sce` and `sce1`. If so, I am unsure what is going on. Could you send me the object at hector dot rouxdebezieux at gmail dot com ? Thanks

**Comment by rmenafra** [comment]
Hi @HectorRDB, I believe my issue was related to my .rmd and not directly to the package version, I was creating a slingshot object with the same name prior to loading the result of FitGam in the .rmd. I sent you the RDS but I solved the issue anyway by assigning a different name to the object.
Thanks for your time, you can close the issue.

**Comment by HectorRDB** [comment]
Thanks got it
