### ISSUE TITLE
conditionTest using pseudotime other than slingshot

### ISSUE THREAD

**Issue by zji90** [statOmics/tradeSeq#174]
Hi, 

I wonder if there are any means to run conditionTest if we have pseudotime constructed using software other than slingshot. From the manual, it seems that running slingshot is a prerequisite of running tradeSeq functions such as conditionTest, but we happen to have pseudotime that is not obtained using slingshot.

Thanks a lot!

**Comment by koenvandenberge** [comment]
Closing after a month of inactivity, please feel free to comment and reopen if you encounter any issues.
