### ISSUE TITLE
how to fitGAM for genes between lineages?

### ISSUE THREAD

**Issue by FADHLyemen** [statOmics/tradeSeq#175]
Slingshoot inferred two lineages, how to use fitGAM to identify genes that differ between lineages?
How to justify why we have two lineages? any ideas?

**Comment by koenvandenberge** [comment]
Hi @FADHLyemen 

We have [a vignette](https://bioconductor.org/packages/release/bioc/vignettes/tradeSeq/inst/doc/tradeSeq.html) that you can follow to assess differential expression between lineages. There is also [a vignette on fitGAM](https://bioconductor.org/packages/release/bioc/vignettes/tradeSeq/inst/doc/fitGAM.html).

Justifying whether you have two lineages usually requires domain knowledge to make sure that these lineages make biological sense. It usually helps visualizing the trajectory in reduced dimension and visually check if it makes sense. If you have known marker genes that might highlight starting, intermediate, or ending positions, that could be helpful, too.

Hop this helps.
