### ISSUE TITLE
patternTest(sce, pairwise = T) with error

### ISSUE THREAD

**Issue by pchiang5** [statOmics/tradeSeq#177]
Hello,

When I use `patternRes <- patternTest(sce)`, the code ran fine. However, an error below showed up when I included `pairwise` in the code  as `patternRes <- patternTest(sce, pairwise = T)` with the same sce object (4 lineages in the object). Did it mean I have to specify the lineages to compare? Thank you. 

> Error in t(L) %*% Sigma :
>   requires numeric/complex matrix/vector arguments

**Comment by koenvandenberge** [comment]
Hi @pchiang5 ,

Thanks for reporting this issue.
What version of `tradeSeq` are you using? 
Do you mind trying again with the latest version by installing it from GitHub? 
If the error still persists then, we will take a look to resolve this.

**Comment by pchiang5** [comment]
Hi @koenvandenberge,

Thank you for the prompt response.

I update the package to 1.8.0. The identical issue remains. 

Besides, I wonder if the `'global'` output also includes the `'pairwise'` comparison, which means the positive ones with the `'pairwise'` comparison will also be positive with the `'global'` comparison? If yes, maybe I can check the positive one by one if the number is not too large.

BTW, I encountered another issue with the` plotSmoothers()` function. For some genes, the curves showed properly (left) but for the others, no curves showed up at all even with apparent dots of expression (right). Could you help me address the issue?  Thank you.


![tradeseq](https://user-images.githubusercontent.com/29170925/144534446-1ed2fbf8-fdeb-48c8-b937-37bb2fa77b74.png)

**Comment by koenvandenberge** [comment]
Thank you for checking this.

The `global` comparison performs an omnibus test that includes all pairwise comparisons. In your case, you have five different lineages and significance of the global test means that **at least** one of the pairwise comparisons is showing evidence for DE as defined by the `patternTest`.

We have not implemented flexibility to only focus on a subset of the pairwise comparisons as you mention; we always return results for all pairwise comparisons.

I will look into this, but just to be sure: You are not working with different conditions, right? i.e. you did not provide the `conditions` argument to `fitGAM`.

Concerning `plotSmoothers`: the warnings are suggesting that there are missing values in the fitted smoother estimate. Is it possible that for example some cells have a sequencing depth of zero in the data you're providing to `fitGAM`?

**Comment by pchiang5** [comment]
Hello @koenvandenberge

The input below returned the error (no `conditions` argument). I did not include all genes in the sce object for figGAM (only the subset in GOI). 
`sce <- fitGAM(sce,  parallel = TRUE,  verbose = TRUE, genes = GOI,  nknots = 12, BPPARAM = BiocParallel::bpparam())`
`patternRes <- patternTest(sce, pairwise = TRUE)`

Regarding `plotSmoothers`, I found the lost curve was caused by not including that particular gene in fitGAM() analysis. Thank you.

**Comment by koenvandenberge** [comment]
Thanks for clarifying. Just to be sure, what is the output from `range(colSums(counts(sce)[GOI,]))`?

**Comment by pchiang5** [comment]
Please see the output below:

`range(colSums(counts(sce)[GOI,]))`

> [1]   29 3201

`patternRes <- patternTest(sce, pairwise = T)`

> Error in t(L) %*% Sigma :
>   requires numeric/complex matrix/vector arguments

**Comment by koenvandenberge** [comment]
Hi @pchiang5, I'm unable to reproduce this error; do you mind sharing a subset of your data I can work with, resulting in the error?

**Comment by pchiang5** [comment]
Hi @koenvandenberge

Thank you for trying to reproduce the error. 

After comparing the my data with the reference data in your tutorial https://bioconductor.org/packages/devel/bioc/vignettes/tradeSeq/inst/doc/tradeSeq.html[], I found the error was the result of the NA values in the slingshot pseudotime. The error could be corrected by the following input (an = FLASE while extracting pseudotime):

`sce <- fitGAM(assays(sce)$counts,  parallel = TRUE,  pseudotime = slingPseudotime(sce, na = FALSE),  cellWeights = slingCurveWeights(sce),   verbose = TRUE, genes = GOI,  nknots = 6, BPPARAM = BiocParallel::bpparam())`

However, `patternRes <- patternTest(sce, pairwise = TRUE)` produced another error:

> Error in t(L) %*% Sigma : non-conformable arguments

Based on issue 56 "Error in patternTest #56', I guess this was caused by 'This gene only has XXX non-null values and should be fitered before running fitGam'. Is it possible to locate the source of the error by looking into `rowData(sce)$tradeSeq$Sigma` or the gene counts in the sce object and filter the genes out by myself?

**Comment by koenvandenberge** [comment]
Hi @pchiang5,

Thanks for the info. 
I have just updated `tradeSeq` to return `NA` values in the `patternTest` pairwise comparison results whenever we have been unable to fit the data for a gene. Could you restart your R session, re-install `tradeSeq` from the repository (e.g. using `devtools::install_github`), and check if this resolves your issue?

**Comment by pchiang5** [comment]
The update worked. Thank you @koenvandenberge.

**Comment by koenvandenberge** [comment]
Thank you for reporting and your patience in finding a solution, which has helped us in improving the package!
