### ISSUE TITLE
New to single cell analysis, don't know how to save tradseq object

### ISSUE THREAD

**Issue by Matthew1309** [statOmics/tradeSeq#179]
I am fairly new to single cell analysis, and I have been following along with various tutorials (seurat, monocle, and your vignette). From the seurat tutorial, they have a saveRDS function that lets me save my object whenever I want, but I can't seem to find a similar function for TradeSeq or Slingshot.

If you could point me in the right direction on how to save my work, I would really appreciate it. Thank you for your time and wonderful tool!

**Comment by HectorRDB** [comment]
hi @Matthew1309 
saveRDS is not a Seurat function but exists with the default R and work with any object. In the future, you can find help on function by typing `?function_name` into R
