### ISSUE TITLE
clusterExpressionPattern producing 'spiky' output

### ISSUE THREAD

**Issue by Graham-Magor** [statOmics/tradeSeq#18]
Hi,

I've been working through your vignette using my own data and have come to the clusterExpressionPattern section which is producing some odd looking graphs.

![Capture](https://user-images.githubusercontent.com/54785385/67258023-72f1ae00-f4da-11e9-9130-f052081c7649.PNG)

Any idea on  why they are so spiky / what I might be doing wrong?

Thanks

**Comment by HectorRDB** [comment]
Hi @Graham-Magor,
Thanks for raising that issue. There is indeed something weird happening. Would you mind sharing the code you used? Either here if you do not mind or at hector dot rouxdebezieux at berkeley dot edu.

**Comment by Graham-Magor** [comment]
Here is the output of plotSmoothers:

plotSmoothers(sce, counts = as.matrix(Y), gene = "E2f2

![Capture](https://user-images.githubusercontent.com/54785385/67441356-3e036980-f648-11e9-9b1c-1b1cb750c7b0.PNG)
")

**Comment by HectorRDB** [comment]
Hi @Graham-Magor 
Thanks for that issue. It is related to #14. The code in the vignette is designed to work for two lineages. You need to update some lines:
I think replacing 
```
geom_line(data = data.frame(x = rep(1:nPointsClus, 2),
                                  y = clusPat$yhatScaled[geneId, ],
                                  lineage = rep(0:1, each = nPointsClus)),
                aes(col = as.character(lineage), group = lineage), lwd = 1.5)
``` 

with 

```
geom_line(data = data.frame(x = rep(1:nPointsClus, 4),
                                  y = clusPat$yhatScaled[geneId, ],
                                  lineage = rep(0:3, each = nPointsClus)),
                aes(col = as.character(lineage), group = lineage), lwd = 1.5)
``` 

should work

**Comment by Graham-Magor** [comment]
I feel like we're getting close!

Just getting this error now:

Error: Insufficient values in manual scale. 4 needed but only 2 provided.

**Comment by HectorRDB** [comment]
Thanks for the help. We modified the vignette to make it clearer for users
