### ISSUE TITLE
patternTest() failed to detect significant genes

### ISSUE THREAD

**Issue by pchiang5** [statOmics/tradeSeq#180]
Hello,

I tried to detect differential gene expression patterns between 2 lineages with the following input:

```
gamList <- fitGAM(sce, verbose = TRUE, genes = GOI,  nknots = 6, ,  control = control)
patternRes <- patternTest(gamList)
```

With a particular gene_X, I got the following output:

> waldStat  df   pvalue     fcMedian  
> 3.591829  3   0.309046  1.838684

However, the expression curves by the code below showed a clear difference between the expression patterns(figure below).
`plotSmoothers(gamList, assays(gamList)$counts, gene = c('gene_X'))`

![Untitled](https://user-images.githubusercontent.com/29170925/146625661-20aa606a-80ac-483d-8db0-d2c029550d20.jpg)

How shall I modify the parameters to fix the missed detection? Thank you.

**Comment by koenvandenberge** [comment]
Hi @pchiang5,

Thank you for reporting this. The `patternTest` will compare a number of points along pseudotime between the two lineages. By default, it will compare `2k` points, with `k` the number of knots, and so 12 points will be compared in your case. 
However, a comparison of some of these points will be linearly related to other points, and according to the design matrix and fit for that gene will not contribute additional information. We thus remove these points in the comparison, which also helps us in inverting the variance-covariance matrix of the points we'd like to compare. 
In your case, it looks like three points were compared for this specific gene as there are three degrees of freedom. It is possible that these points do not pick up the difference at pseudotime ~35.
Even if one of the points is around there, it is also possible that the signal picked up there is diluted in the non-DE signal of the other points being compared, e.g., comparisons in pseudotime range of [0, 25].

It may or may not help to increase the number of points you use to compare expression patterns, which you can do using the `nPoints` argument. Alternatively, you can focus on discovering differential expression patterns near the end of the lineages, for example, between knots 4 and 6, using the `earlyDETest`.

Let us know if that helps.

**Comment by pchiang5** [comment]
Hi @koenvandenberge,

The `patternTest(nPoint = 12)` or even `patternTest(nPoint = 200)` did not help. (the df of this gene remained 2 even the others got larger values).

The `earlyRes(knots = c(4, 6))` worked. Thank you.
