### ISSUE TITLE
Condition argument with design matrix

### ISSUE THREAD

**Issue by cohenp05** [statOmics/tradeSeq#184]
Hello,

I'm using tradeSeq on a data set with 2 infection conditions each at 2 time points, plus a mock with each sample having 2-3 replicates and all samples split over 3 batches. I've prepared a design matrix to compare across infections (irrespective of timepoint) and model the batch effect as well (hopefully thereby making some use of the replicates also). My question is when I run fitGAM should I include the design matrix with the `U` argument and infection labels with the `condition` argument or is that unnecessary? 

As an example: 
`set.seed(123456)
data(countMatrix, package = "tradeSeq")
data(crv, package = "tradeSeq")

batch_infection <- DataFrame(
  Infection = sample(x = c("Mock", "Infection1", "Infection2"), size = ncol(countMatrix), replace = TRUE),
  Batch = sample(x = c("A", "B", "C"), size = ncol(countMatrix), replace = TRUE)
)

rownames(batch_infection) <- colnames(countMatrix)

design <- model.matrix(~Infection + Batch, batch_infection)`

Which way should I then run `fitGAM`? Option 1:
`sce <- fitGAM(
  counts = countMatrix,
  sds = crv,
  U = design,
  nknots = 6
)`
or option 2:
`sce2 <- fitGAM(
  counts = countMatrix,
  sds = crv,
  U = design,
  conditions = factor(batch_infection$Batch),
  nknots = 6)`

**Comment by koenvandenberge** [comment]
Hi @cohenp05,

If you are interested in comparing gene expression between conditions, we suggest adding the conditions through the `conditions` argument (as in option 2), but leaving it out of your design matrix you are providing through the `U` argument.

Hope this helps.

**Comment by cohenp05** [comment]
That's perfect. Thank you!
