### ISSUE TITLE
How are trajectory numbers assigned?

### ISSUE THREAD

**Issue by haerin0106** [statOmics/tradeSeq#185]
Hi, I have a slingshot output from single cell data with 3 trajectories that converge into one. 

![image](https://user-images.githubusercontent.com/92518297/153874542-b96501ce-c77c-4862-a800-51c69d6cfae4.png)

I would like to find out differentially expressed genes that are associated with only the trajectory on the right. 
I figured that I should use associationTest or startVsEndTest with the lineages option to TRUE. 
From doing 
`associationTest(gam,global=F,lineages=T)`
I got the following. 
![Screenshot 2022-02-14 at 13 41 35](https://user-images.githubusercontent.com/92518297/153875038-954a3d8a-c532-4c92-a005-4fabb63e4317.png)
How do I know which is associated with the trajectory of interest (the right one)?
Is using [plotGeneCount] with some of the significant genes the only way to find this?
Also, what is the last column of the associationTest results? It seems like it doesn't have a column title.

**Comment by koenvandenberge** [comment]
Hi @haerin0106,

Apologies for my late response. We use the lineage names provided by Slingshot. You are able to check which lineage number corresponds to which in the plot using `lines.SlingshotDataSet`. Please see the `linInd` argument in that function. 

For example:

```
library(slingshot)
data("slingshotExample")
rd <- slingshotExample$rd
cl <- slingshotExample$cl

sce <- slingshot(rd, cl)

plot(rd)
# only plot first lineage
lines(SlingshotDataSet(sce), linInd=1)
# only plot second lineage
lines(SlingshotDataSet(sce), linInd=2)
# plot both lineages
lines(SlingshotDataSet(sce))
```


Hope this helps.
