### ISSUE TITLE
Question about fitGAM function 

### ISSUE THREAD

**Issue by apekshasingh** [statOmics/tradeSeq#190]
Hi there and thanks for your package.  In your manuscript it says, "the cubic basis functions bk(t) are enforced to be the same for all genes and lineages".  I was wondering if you could share a bit more about how this is implemented in your code.  Under the fit models section, it appears that the counts_to_Gam function is called for each gene.  Is it the id variable passed to the smoother or some other step that enforces the common bk(t)?  Thanks so much again!

**Comment by koenvandenberge** [comment]
Hi @apekshasingh ,

Thanks for your question. 
First, we enforce the same knot points for all lineages by providing these along in the `mgcv::gam` function. This happens [here](https://github.com/statOmics/tradeSeq/blob/master/R/fitGAM.R#L295).
The `id` variable indeed enforces the same smoothness (the same penalty parameter) and basis for all lineages. From `?mgcv::s`:

> A label or integer identifying this term in order to link its
          smoothing parameters to others of the same type. If two or
          more terms have the same ‘id’ then they will have the same
          smoothing paramsters, and, by default, the same bases (first
          occurance defines basis type, but data from all terms used in
          basis construction). An ‘id’ with a factor ‘by’ variable
          causes the smooths at each factor level to have the same
          smoothing parameter.

**Comment by apekshasingh** [comment]
Thank you for your response!
