### ISSUE TITLE
function of extract_monocle_info

### ISSUE THREAD

**Issue by lihong911002** [statOmics/tradeSeq#193]
hi,
      Now, I can't find the function of extract_monocle_info. Can you tell me how to get it?

Li Hong
best wishes

**Comment by koenvandenberge** [comment]
Hi @lihong911002 

We have removed that function from the package, since the installation of `Monocle` was consistently having errors. Therefore, the Bioconductor builds were also failing to install `tradeSeq`.

**Comment by HectorRDB** [comment]
Hi,
You can find the function here
<https://github.com/statOmics/tradeSeq/blob/2c4358b5f72fa1c04140c2773ff975ff7f7ce329/R/extract_monocle_info.R>
on previous versions if you want.
Best
