### ISSUE TITLE
plotSmoothers for the Condition Test - plotting conditions instead of lineages.

### ISSUE THREAD

**Issue by DustinSokolowski** [statOmics/tradeSeq#195]
Hey!

Thank you for the amazing tool. I have been using tradeSeq to both trace lineages as well as look at differences in conditions within a lineage using the ConditionTest. I was wondering if you've considered adding a function that produces the output of plotSmoothers but instead of plotting lineage 1 and 2 for a specific gene or cluster it would plot condition 1 or 2 for a lineage. I'm sorry if you've done this and I've missed it. If not, please let me know if you're interested and/or have any suggestions.

Best,
Dustin

**Comment by koenvandenberge** [comment]
Hi @DustinSokolowski,

My apologies for being so slow in responding and thank you for the suggestion - we have not implemented this. By default we plot all lineages and conditions. 
Feel free to create a pull request if you have developed this. Alternatively, if you need a quick hack, you can always play around with the ggplot2 object that is returned when running `plotSmoothers` and only plotting the smoothers of interest.

**Comment by DustinSokolowski** [comment]
Hey!

Thank you so much for your help! I ended up having few enough lineages that I could plot both conditions so the below code did the trick assuming the fitGam function had both conditions. Again, thank you again for the wonderful tool, it made a big difference in multiple projects.

`plotSmoothers(sce, assays(sce)$counts, gene = "myGene", alpha = 1, border = TRUE) + ggtitle("myGene")`
