### ISSUE TITLE
Wald statistics problem with associationTest

### ISSUE THREAD

**Issue by irenerh** [statOmics/tradeSeq#199]
Hello,

I’m running `associationTest` using default settings but applying a l2fc cut-off:
`ATres <- associationTest(models = sce, global=TRUE, lineages = TRUE, l2fc = log2(1.3))`
The results show extremely high Wald statistics values for the significant genes. However this issue is not happening when I remove the l2fc argument.
I was using the version 1.8.0. I just updated it to the most recent version of the package (1.10.0) but I’m still having the same problem.

Thank you!

**Comment by koenvandenberge** [comment]
Hi @irenerh ,

This is a valid concern and it is a known issue. Due to our implementation, it can be difficult to invert the variance-covariance matrix for the `associationTest` when a fold-change cut-off is used. We hope, however, that the gene ranking is still useful.
