### ISSUE TITLE
Comparing trajectories of different cell types to same stimulus

### ISSUE THREAD

**Issue by dpcook** [statOmics/tradeSeq#2]
Hey @HectorRDB, fantastic work on this--it looks great! I'm just getting some trajectories prepared to try this out. I'm wondering if you had any thoughts about how best to approach a situation where, for example, you have separate trajectories for Cell Type A and Cell Type B (and perhaps more) exposed to some experimental condition and you want to do tests for differential responses. The key thing here I suppose would be to ignore baseline differences at pseudotime=0 and just test for changes relative to that starting point. 

Would it make sense to include cell type as a covariate? For other models, I could imagine centring the data on the values at pseudotime=0, but given that the model takes counts as input, I don't think that would work. 

Any thoughts? Looking forward to trying this out!

**Comment by HectorRDB** [comment]
Hey,
glad you like it. Just to be clear, cell types A and B refer to different progenitors for different developmental trajectories? You have something like this?

|                        	| Condition 1 	| Condition 2 	|
|:----------------------:	|:-----------:	|:-----------:	|
| Progenitor cell type A 	| trajectory 1A 	| trajectory 2A 	|
| Progenitor cell type B 	| trajectory 1B 	| trajectory 2B 	|
|           ...          	|     ...     	|     ...     	|

Or do they refer to end points of separate lineages from the same trajectory and you have something like this

|                        	|       Condition 1       	|       Condition 2       	|
|:----------------------:	|:-----------------------:	|:-----------------------:	|
|                        	| Topology 1              	| Topology 2              	|
| Progenitor cell type A 	| Lineage A in trajectory 1 	| Lineage A in trajectory 2 	|
| Progenitor cell type B 	| Lineage B in trajectory 1 	| Lineage B in trajectory 2 	|
|           ...          	|           ...           	|           ...           	|


?

**Comment by dpcook** [comment]
Yeah, sorry--I should have been more clear! Experimental condition can actually be ignored in this context I think, because the purpose of the experimental condition was simply to create the trajectory itself (in this case, it was a time course experiment). So it's really just Trajectory 1A (Cell Type A) vs. Trajectory 1B (Cell Type B)

For more details, I have time course data for multiple cell types with the same treatment (here's two for example) and I want to see how similar the transcriptional response is--ignoring the baseline differences between cell types:
**Cell Type A (A549 cells treated with TGFB1)**
![image](https://user-images.githubusercontent.com/18197806/57110875-19b57880-6d08-11e9-9adb-14560ceb6dc4.png)
Pseudotime:
![image](https://user-images.githubusercontent.com/18197806/57110957-6bf69980-6d08-11e9-9209-2e9f40cb0205.png)

**Cell Type B (DU145 cells treated with TGFB1)**
![image](https://user-images.githubusercontent.com/18197806/57110986-8af52b80-6d08-11e9-929f-597f8445b630.png)
Pseudotime:
![image](https://user-images.githubusercontent.com/18197806/57111001-92b4d000-6d08-11e9-9214-eab0bd7bc5c6.png)


Hope that helps!

David

**Comment by HectorRDB** [comment]
So, since it's not really a software issue, I'm going to close this but you can email me (hector.rouxdebezieux@berkeley.edu) and we can keep chatting on that to help you
