### ISSUE TITLE
Error with slingshot slingPseudotime and slingCurveWeights after using fitGAM from tradeSeq

### ISSUE THREAD

**Issue by e-manduchi** [statOmics/tradeSeq#202]
Hello,
I reported this issue on the Bioconductor forum and was advised to submit it here. A detailed description is at
https://support.bioconductor.org/p/9145680/#9145699, but in a nutshell what I have happening is that, for a SCE col.sce, the class of col.sce$slingshot appears to be changed from PseudotimeOrder (before application of fitGAM) to DataFrame (after application of fitGAM).
Thanks for your attention

**Comment by e-manduchi** [comment]
This seems to be resolved after an update of the package versions for slinghot and tradeSeq as indicated here https://support.bioconductor.org/p/9145680/#9145778.

**Comment by koenvandenberge** [comment]
Thank you @e-manduchi for letting us know, let us know if you would encounter any further issues.
