### ISSUE TITLE
can tradeSeq be applied to identify dynamic motifs in scATAC data?

### ISSUE THREAD

**Issue by wangmhan** [statOmics/tradeSeq#204]
Thank you for develop the software!

I'm working on scATAC-seq data. It would be interested to identify dynamic motifs along development trajectory.

But for motif data, I don't have raw count. What I have is scaled motif activity matrix generated by chromVAR (Signac::RunChromVAR).
I wonder if it is ok to use this matrix as input counts for function fitGAM, or I need to first log transfered? If yes, as the motif activity matrix have negative value, is it proper if I do like this: log2(mtx+1-min(mtx))?

I also want to ask if I only have one lineage, is it ok to use default nknots:6?

Thanks a lot!

**Comment by koenvandenberge** [comment]
Hi @wangmhan 

I have no real experience working with motif activity matrices, so I am not sure how much I can comment on this.
That said, if you think that assuming a Gaussian distribution on the motif activities (or that the central limit theorem could hold), you could run `fitGAM` and set `family = "gaussian"`.

Hope this helps.
