### ISSUE TITLE
consecutive contrast gives p values either 0 or 1

### ISSUE THREAD

**Issue by JuanXie19** [statOmics/tradeSeq#205]
Dear tradeSeq development team,

I am using tradeSeq for DE analysis. I have just one lineage and I tried the associationTest function. However, it is found that when contrastType='consecutive', the resulting p values are either 0 or 1, which I think is weird (when I use contrastType='start', the p values range from 0 to 1, not just 0 or 1). Could you help and check what's wrong?

Here is my code:
##
sce <- fitGAM(DATA.sub,pseudotime = pseudotime,cellWeights = weights,nknots=6,verbose=FALSE,parallel = TRUE)   # takes a long time
assoRes1 <- round(associationTest(sce,contrastType = "consecutive"))

And here is the distribution of p values:
![image](https://user-images.githubusercontent.com/98572468/184963720-33582e36-c290-4f41-8b10-4e46cdfd549c.png)

Thanks!

**Comment by koenvandenberge** [comment]
Hi @JuanXie19 

Note that you are rounding all results of the `associationTest` with the `round` function, which explains the distribution you are observing. You probably do not want to do that.
