### ISSUE TITLE
can TradeSeq be use to fit GAMs on Regulon Activity scores (scenic output)and pseudo time ?

### ISSUE THREAD

**Issue by dcruz5h** [statOmics/tradeSeq#208]
I recently used scenic to quantify regulon activity in my single cell RNAseq data ( patters of co expression between a transcription factor and its putative targets). The single cell scores (AUCell) from this analysis run between 0 to 1. 

I would like to use TradeSeq to fit GAMs on each of my regulons (~300) on 10 pseudotime lineages obtained from slingshot between two conditions (control and test) as in the picture attached. 

Can TradeSeq be use to fit GAMS on this type of data or does it expect a gene expression count matrix?
I will really appreciate your feedback 

<img width="932" alt="image" src="https://user-images.githubusercontent.com/47330637/186647470-d6224eeb-b534-4c7c-a2ce-7bbbdfc080a3.png">

**Comment by koenvandenberge** [comment]
Hi @dcruz5h 

In principle you can do this. However, note that the SCENIC regulon activity scores are based on `AUCell` and are basically AUC values ranging between 0 and 1. A count distribution will therefore not be appropriate and you would want to consider using other parametric distributions to model these scores. You can change distribution in `fitGAM` using the `family` argument.

Hope this helps.

**Comment by dcruz5h** [comment]
Thank you !! I will consider this !
