### ISSUE TITLE
Error running evaluateK

### ISSUE THREAD

**Issue by AnnaLaddach** [statOmics/tradeSeq#21]
Hi,

I'm getting an error running evaluateK on my data:

"Fitting terminated with step failure - check results carefully"

I believe it's because my data is zero inflated, if I add a pseudocount of one to the count matrix it runs without problems, however I'm not convinced this is a sensible thing to do.

I've tried calculating weights using the zinbwave package, however even when setting the weights parameter of evaluateK I receive the same error message.

Many thanks for your help!

**Comment by koenvandenberge** [comment]
Hi,

This is an error from `mgcv`, i.e. the code used internally by `evaluateK`, but this error should get caught and not result in an error of `evaluateK`. Probably you did get an output (and plot)?
If so, you can continue with your workflow.

**Comment by AnnaLaddach** [comment]
Hi, 

I do get output but not the plot.
![image](https://user-images.githubusercontent.com/8480634/69563823-b93e9f00-0fa9-11ea-929e-8560aa21b44e.png)

![image](https://user-images.githubusercontent.com/8480634/69563281-b7281080-0fa8-11ea-8c0b-4fa21fedcb8c.png)


This is in comparison to the output after adding 1 to the matrix and running without weights, where I get both output and a plot.

![image](https://user-images.githubusercontent.com/8480634/69562241-a4144100-0fa6-11ea-92b4-ec64e7ed23c6.png)

![image](https://user-images.githubusercontent.com/8480634/69564052-2baf7f00-0faa-11ea-8840-5b4427b2541f.png)
 
Thanks again!

**Comment by HectorRDB** [comment]
Ok, so the error you see (fitting terminated with step failure, check result carefully) means that for each gene, the `mgcv` package failed to converge. However, this should result in a warning, not an error.
Did you change your settings so that warnings are reported as errors? If you are not sure, try running `options(warn = 0)` before your code and that should hopefully fix the issue

**Comment by AnnaLaddach** [comment]
If I do that I get this:

![image](https://user-images.githubusercontent.com/8480634/69567146-a2e81180-0fb0-11ea-8d52-792111555392.png)

I guess I am still getting output, and I can see the code for the plot is within the evaluateK function so I could try stepping through that to see why it doesn't give me a plot.

**Comment by HectorRDB** [comment]
Just to clarify, with the latest iteration, the code continues to run and finishes? And you do see a similar plot as the one above? It will take a while to run (you can try setting `k=3:4` to start to make sure there are no errors) but it should give you some info of the number of knots to pick. 
To see previous discussion of this error message, you can look at @koenvandenberge  [previous comment](https://github.com/statOmics/tradeSeq/issues/14#issuecomment-549875615)

**Comment by AnnaLaddach** [comment]
Thank you! With the latest iteration it does finish and produces the plot :)

**Comment by balthasar0810** [comment]
What is the solution? I am also running evaluateK, it finishes but doesn't show the plots?!

**Comment by HectorRDB** [comment]
Hi @balthasar0810 
Can you please clarify a bit more (i.e. version of tradeSeq that you are using, OS and such)
Best,

**Comment by balthasar0810** [comment]
Hi,

I downloaded the Github version of tradeSeq yesterday. I am using a Macbook with Catalina 10.15.4. Please find below the complete session info from RStudio below.

Chris

─ Session info ──────────────────────────────────────────────────────────────────────────────────
 setting  value                       
 version  R version 4.0.2 (2020-06-22)
 os       macOS Catalina 10.15.4      
 system   x86_64, darwin17.0          
 ui       RStudio                     
 language (EN)                        
 collate  en_US.UTF-8                 
 ctype    en_US.UTF-8                 
 tz       Europe/Berlin               
 date     2021-01-28                  

─ Packages ──────────────────────────────────────────────────────────────────────────────────────
 ! package              * version  date       lib source                             
   abind                  1.4-5    2016-07-21 [1] CRAN (R 4.0.2)                     
   ade4                   1.7-16   2020-10-28 [1] CRAN (R 4.0.2)                     
   annotate               1.66.0   2020-04-28 [1] Bioconductor                       
   AnnotationDbi          1.50.3   2020-07-25 [1] Bioconductor                       
   ape                    5.4      2020-06-03 [1] CRAN (R 4.0.1)                     
   assertthat             0.2.1    2019-03-21 [1] CRAN (R 4.0.1)                     
   backports              1.1.8    2020-06-17 [1] CRAN (R 4.0.1)                     
   Biobase              * 2.48.0   2020-04-27 [1] Bioconductor                       
   BiocGenerics         * 0.34.0   2020-04-27 [1] Bioconductor                       
   BiocManager            1.30.10  2019-11-16 [1] CRAN (R 4.0.2)                     
   BiocParallel           1.22.0   2020-04-27 [1] Bioconductor                       
   bit                    4.0.4    2020-08-04 [1] CRAN (R 4.0.2)                     
   bit64                  4.0.5    2020-08-30 [1] CRAN (R 4.0.2)                     
   bitops                 1.0-6    2013-08-17 [1] CRAN (R 4.0.1)                     
   blob                   1.2.1    2020-01-20 [1] CRAN (R 4.0.2)                     
   callr                  3.5.1    2020-10-13 [1] CRAN (R 4.0.2)                     
   cli                    2.0.2    2020-02-28 [1] CRAN (R 4.0.1)                     
   cluster                2.1.0    2019-06-19 [1] CRAN (R 4.0.2)                     
   clusterExperiment      2.8.0    2020-04-27 [1] Bioconductor                       
   codetools              0.2-16   2018-12-24 [1] CRAN (R 4.0.2)                     
   colorspace             1.4-1    2019-03-18 [1] CRAN (R 4.0.1)                     
   combinat               0.0-8    2012-10-29 [1] CRAN (R 4.0.2)                     
   cowplot                1.0.0    2019-07-11 [1] CRAN (R 4.0.1)                     
   crayon                 1.3.4    2017-09-16 [1] CRAN (R 4.0.1)                     
   curl                   4.3      2019-12-02 [1] CRAN (R 4.0.1)                     
   data.table             1.12.8   2019-12-09 [1] CRAN (R 4.0.1)                     
   DBI                    1.1.0    2019-12-15 [1] CRAN (R 4.0.2)                     
   DDRTree                0.1.5    2017-04-30 [1] CRAN (R 4.0.2)                     
   DelayedArray         * 0.14.1   2020-07-14 [1] Bioconductor                       
   deldir                 0.2-9    2021-01-16 [1] CRAN (R 4.0.2)                     
   densityClust           0.3      2017-10-24 [1] CRAN (R 4.0.2)                     
   desc                   1.2.0    2018-05-01 [1] CRAN (R 4.0.1)                     
   devtools             * 2.3.2    2020-09-18 [1] CRAN (R 4.0.2)                     
   digest                 0.6.25   2020-02-23 [1] CRAN (R 4.0.1)                     
   docopt                 0.7.1    2020-06-24 [1] CRAN (R 4.0.2)                     
   doParallel             1.0.16   2020-10-16 [1] CRAN (R 4.0.2)                     
   dplyr                * 1.0.0    2020-05-29 [1] CRAN (R 4.0.1)                     
   edgeR                  3.30.3   2020-06-02 [1] Bioconductor                       
   ellipsis               0.3.1    2020-05-15 [1] CRAN (R 4.0.1)                     
   fansi                  0.4.1    2020-01-08 [1] CRAN (R 4.0.1)                     
   fastICA                1.2-2    2019-07-08 [1] CRAN (R 4.0.2)                     
   fastmap                1.0.1    2019-10-08 [1] CRAN (R 4.0.2)                     
   fitdistrplus           1.1-1    2020-05-19 [1] CRAN (R 4.0.1)                     
   FNN                    1.1.3    2019-02-15 [1] CRAN (R 4.0.1)                     
   foreach                1.5.1    2020-10-15 [1] CRAN (R 4.0.2)                     
   fs                     1.4.2    2020-06-30 [1] CRAN (R 4.0.2)                     
   furrr                  0.2.1    2020-10-21 [1] CRAN (R 4.0.2)                     
   future                 1.21.0   2020-12-10 [1] CRAN (R 4.0.2)                     
   future.apply           1.6.0    2020-07-01 [1] CRAN (R 4.0.1)                     
   genefilter             1.70.0   2020-04-27 [1] Bioconductor                       
   generics               0.1.0    2020-10-31 [1] CRAN (R 4.0.2)                     
   GenomeInfoDb         * 1.24.2   2020-06-15 [1] Bioconductor                       
   GenomeInfoDbData       1.2.3    2020-11-23 [1] Bioconductor                       
   GenomicRanges        * 1.40.0   2020-04-27 [1] Bioconductor                       
   ggplot2                3.3.2    2020-06-19 [1] CRAN (R 4.0.1)                     
   ggrepel                0.8.2    2020-03-08 [1] CRAN (R 4.0.1)                     
   ggridges               0.5.2    2020-01-12 [1] CRAN (R 4.0.1)                     
   globals                0.14.0   2020-11-22 [1] CRAN (R 4.0.2)                     
   glue                   1.4.1    2020-05-13 [1] CRAN (R 4.0.1)                     
   goftest                1.2-2    2019-12-02 [1] CRAN (R 4.0.2)                     
   gridBase               0.4-7    2014-02-24 [1] CRAN (R 4.0.2)                     
   gridExtra              2.3      2017-09-09 [1] CRAN (R 4.0.1)                     
   gtable                 0.3.0    2019-03-25 [1] CRAN (R 4.0.1)                     
   HDF5Array              1.16.1   2020-06-16 [1] Bioconductor                       
   hms                    0.5.3    2020-01-08 [1] CRAN (R 4.0.2)                     
   howmany                0.3-1    2012-06-01 [1] CRAN (R 4.0.2)                     
   HSMMSingleCell         1.8.0    2020-05-07 [1] Bioconductor                       
   htmltools              0.5.0    2020-06-16 [1] CRAN (R 4.0.1)                     
   htmlwidgets            1.5.1    2019-10-08 [1] CRAN (R 4.0.1)                     
   httpuv                 1.5.4    2020-06-06 [1] CRAN (R 4.0.2)                     
   httr                   1.4.2    2020-07-20 [1] CRAN (R 4.0.2)                     
   ica                    1.0-2    2018-05-24 [1] CRAN (R 4.0.1)                     
   igraph                 1.2.5    2020-03-19 [1] CRAN (R 4.0.1)                     
   IRanges              * 2.22.2   2020-05-21 [1] Bioconductor                       
   irlba                  2.3.3    2019-02-05 [1] CRAN (R 4.0.1)                     
   iterators              1.0.13   2020-10-15 [1] CRAN (R 4.0.2)                     
   jsonlite               1.7.2    2020-12-09 [1] CRAN (R 4.0.2)                     
   kernlab                0.9-29   2019-11-12 [1] CRAN (R 4.0.2)                     
   KernSmooth             2.23-17  2020-04-26 [1] CRAN (R 4.0.2)                     
   later                  1.1.0.1  2020-06-05 [1] CRAN (R 4.0.1)                     
   lattice                0.20-41  2020-04-02 [1] CRAN (R 4.0.2)                     
   lazyeval               0.2.2    2019-03-15 [1] CRAN (R 4.0.1)                     
   leiden                 0.3.3    2020-02-04 [1] CRAN (R 4.0.1)                     
   lifecycle              0.2.0    2020-03-06 [1] CRAN (R 4.0.1)                     
   limma                  3.44.3   2020-06-12 [1] Bioconductor                       
   listenv                0.8.0    2019-12-05 [1] CRAN (R 4.0.1)                     
   lmtest                 0.9-37   2019-04-30 [1] CRAN (R 4.0.1)                     
   locfdr                 1.1-8    2015-07-15 [1] CRAN (R 4.0.2)                     
   locfit                 1.5-9.4  2020-03-25 [1] CRAN (R 4.0.2)                     
   magrittr               1.5      2014-11-22 [1] CRAN (R 4.0.1)                     
   MASS                   7.3-51.6 2020-04-26 [1] CRAN (R 4.0.2)                     
   Matrix                 1.2-18   2019-11-27 [1] CRAN (R 4.0.2)                     
 V matrixStats          * 0.56.0   2020-09-25 [1] CRAN (R 4.0.2)                     
   memoise                1.1.0    2017-04-21 [1] CRAN (R 4.0.2)                     
   mgcv                   1.8-31   2019-11-09 [1] CRAN (R 4.0.2)                     
   mime                   0.9      2020-02-04 [1] CRAN (R 4.0.1)                     
   miniUI                 0.1.1.1  2018-05-18 [1] CRAN (R 4.0.2)                     
   monocle                2.16.0   2020-04-27 [1] Bioconductor                       
   munsell                0.5.0    2018-06-12 [1] CRAN (R 4.0.1)                     
   nlme                   3.1-148  2020-05-24 [1] CRAN (R 4.0.2)                     
   NMF                    0.23.0   2020-08-01 [1] CRAN (R 4.0.2)                     
   parallelly             1.23.0   2021-01-04 [1] CRAN (R 4.0.2)                     
   parsnip              * 0.1.5    2021-01-19 [1] CRAN (R 4.0.2)                     
   patchwork              1.0.1    2020-06-22 [1] CRAN (R 4.0.1)                     
   pbapply                1.4-2    2019-08-31 [1] CRAN (R 4.0.1)                     
   pheatmap               1.0.12   2019-01-04 [1] CRAN (R 4.0.2)                     
   phylobase              0.8.10   2020-03-01 [1] CRAN (R 4.0.2)                     
   pillar                 1.4.6    2020-07-10 [1] CRAN (R 4.0.2)                     
   pkgbuild               1.1.0    2020-07-13 [1] CRAN (R 4.0.2)                     
   pkgconfig              2.0.3    2019-09-22 [1] CRAN (R 4.0.1)                     
   pkgload                1.1.0    2020-05-29 [1] CRAN (R 4.0.1)                     
   pkgmaker               0.32.2   2020-10-20 [1] CRAN (R 4.0.2)                     
   plotly                 4.9.2.1  2020-04-04 [1] CRAN (R 4.0.1)                     
   plyr                   1.8.6    2020-03-03 [1] CRAN (R 4.0.1)                     
   png                    0.1-7    2013-12-03 [1] CRAN (R 4.0.1)                     
   polyclip               1.10-0   2019-03-14 [1] CRAN (R 4.0.2)                     
   prettyunits            1.1.1    2020-01-24 [1] CRAN (R 4.0.1)                     
   princurve            * 2.1.6    2021-01-18 [1] CRAN (R 4.0.2)                     
   processx               3.4.5    2020-11-30 [1] CRAN (R 4.0.2)                     
   progress               1.2.2    2019-05-16 [1] CRAN (R 4.0.2)                     
   promises               1.1.1    2020-06-09 [1] CRAN (R 4.0.1)                     
   ps                     1.3.3    2020-05-08 [1] CRAN (R 4.0.1)                     
   purrr                  0.3.4    2020-04-17 [1] CRAN (R 4.0.1)                     
   qlcMatrix              0.9.7    2018-04-20 [1] CRAN (R 4.0.2)                     
   R6                     2.5.0    2020-10-28 [1] CRAN (R 4.0.2)                     
   ranger                 0.12.1   2020-01-10 [1] CRAN (R 4.0.2)                     
   RANN                   2.6.1    2019-01-08 [1] CRAN (R 4.0.1)                     
   rappdirs               0.3.1    2016-03-28 [1] CRAN (R 4.0.1)                     
   RColorBrewer           1.1-2    2014-12-07 [1] CRAN (R 4.0.1)                     
   Rcpp                   1.0.6    2021-01-15 [1] CRAN (R 4.0.2)                     
   RcppAnnoy              0.0.18   2020-12-15 [1] CRAN (R 4.0.2)                     
   RCurl                  1.98-1.2 2020-04-18 [1] CRAN (R 4.0.2)                     
   registry               0.5-1    2019-03-05 [1] CRAN (R 4.0.2)                     
   remotes                2.2.0    2020-07-21 [1] CRAN (R 4.0.2)                     
   reshape2               1.4.4    2020-04-09 [1] CRAN (R 4.0.1)                     
   reticulate             1.16     2020-05-27 [1] CRAN (R 4.0.1)                     
   rhdf5                  2.32.4   2020-10-05 [1] Bioconductor                       
   Rhdf5lib               1.10.1   2020-07-09 [1] Bioconductor                       
   rlang                  0.4.7    2020-07-09 [1] CRAN (R 4.0.2)                     
   rncl                   0.8.4    2020-02-10 [1] CRAN (R 4.0.2)                     
   RNeXML                 2.4.5    2020-06-18 [1] CRAN (R 4.0.2)                     
   rngtools               1.5      2020-01-23 [1] CRAN (R 4.0.2)                     
   ROCR                   1.0-11   2020-05-02 [1] CRAN (R 4.0.1)                     
   rpart                  4.1-15   2019-04-12 [1] CRAN (R 4.0.2)                     
   rprojroot              1.3-2    2018-01-03 [1] CRAN (R 4.0.1)                     
   rsample              * 0.0.8    2020-09-23 [1] CRAN (R 4.0.2)                     
   RSpectra               0.16-0   2019-12-01 [1] CRAN (R 4.0.1)                     
   RSQLite                2.2.0    2020-01-07 [1] CRAN (R 4.0.2)                     
   rstudioapi             0.11     2020-02-07 [1] CRAN (R 4.0.1)                     
   rsvd                   1.0.3    2020-02-17 [1] CRAN (R 4.0.1)                     
   Rtsne                  0.15     2018-11-10 [1] CRAN (R 4.0.1)                     
   S4Vectors            * 0.26.1   2020-05-16 [1] Bioconductor                       
   scales                 1.1.1    2020-05-11 [1] CRAN (R 4.0.1)                     
   scattermore            0.7      2020-11-24 [1] CRAN (R 4.0.2)                     
   sctransform            0.3.2    2020-12-16 [1] CRAN (R 4.0.2)                     
   sessioninfo            1.1.1    2018-11-05 [1] CRAN (R 4.0.2)                     
   Seurat               * 3.2.3    2020-12-15 [1] CRAN (R 4.0.2)                     
   shiny                  1.5.0    2020-06-23 [1] CRAN (R 4.0.2)                     
   SingleCellExperiment * 1.10.1   2020-04-28 [1] Bioconductor                       
   slam                   0.1-48   2020-12-03 [1] CRAN (R 4.0.2)                     
   slingshot            * 1.6.1    2020-06-30 [1] Bioconductor                       
   softImpute             1.4      2015-04-08 [1] CRAN (R 4.0.2)                     
   sparsesvd              0.2      2019-07-15 [1] CRAN (R 4.0.2)                     
   spatstat               1.64-1   2020-05-12 [1] CRAN (R 4.0.2)                     
   spatstat.data          1.7-0    2020-12-16 [1] CRAN (R 4.0.2)                     
   spatstat.utils         1.20-2   2021-01-07 [1] CRAN (R 4.0.2)                     
   stringi                1.4.6    2020-02-17 [1] CRAN (R 4.0.1)                     
   stringr                1.4.0    2019-02-10 [1] CRAN (R 4.0.1)                     
   SummarizedExperiment * 1.18.2   2020-07-14 [1] Bioconductor                       
   survival               3.1-12   2020-04-10 [1] CRAN (R 4.0.2)                     
   tensor                 1.5      2012-05-05 [1] CRAN (R 4.0.2)                     
   testthat               2.3.2    2020-03-02 [1] CRAN (R 4.0.1)                     
   tibble                 3.0.3    2020-07-10 [1] CRAN (R 4.0.2)                     
   tidyr                  1.1.0    2020-05-20 [1] CRAN (R 4.0.1)                     
   tidyselect             1.1.0    2020-05-11 [1] CRAN (R 4.0.1)                     
   tradeSeq             * 1.5.03   2021-01-27 [1] Github (statOmics/tradeSeq@f936938)
   usethis              * 2.0.0    2020-12-10 [1] CRAN (R 4.0.2)                     
   uuid                   0.1-4    2020-02-26 [1] CRAN (R 4.0.2)                     
   uwot                   0.1.10   2021-01-25 [1] Github (jlmelville/uwot@f98c96a)   
   vctrs                  0.3.6    2020-12-17 [1] CRAN (R 4.0.2)                     
   VGAM                   1.1-5    2021-01-14 [1] CRAN (R 4.0.2)                     
   viridis                0.5.1    2018-03-29 [1] CRAN (R 4.0.2)                     
   viridisLite            0.3.0    2018-02-01 [1] CRAN (R 4.0.1)                     
   withr                  2.4.0    2021-01-16 [1] CRAN (R 4.0.2)                     
   XML                    3.99-0.5 2020-07-23 [1] CRAN (R 4.0.2)                     
   xml2                   1.3.2    2020-04-23 [1] CRAN (R 4.0.2)                     
   xtable                 1.8-4    2019-04-21 [1] CRAN (R 4.0.2)                     
   XVector                0.28.0   2020-04-27 [1] Bioconductor                       
   zinbwave               1.10.1   2020-10-02 [1] Bioconductor                       
   zlibbioc               1.34.0   2020-04-27 [1] Bioconductor                       
   zoo                    1.8-8    2020-05-02 [1] CRAN (R 4.0.1)                     

[1] /Library/Frameworks/R.framework/Versions/4.0/Resources/library

 V ── Loaded and on-disk version mismatch.

**Comment by HectorRDB** [comment]
HI @balthasar0810 ,
The very latest tradeSeq commit adds a new function named `plot_evalutateK_results` that takes the output from `evaluateK` as input. This should generate the plots. If it does not, it means that there is something weird with your graphic device process.
Do you see a plot when you do
```
plot_test <- function() {
  graphics::plot(1:10, 1:10)
return()
}
plot_test()
```
Best

**Comment by balthasar0810** [comment]
Thanks. I just installed again from GitHub with install_github (tradeSeq_1.5.03) but it does not seem to contain such a function.

**Comment by HectorRDB** [comment]
My bad, I forgot to change the version number... This should work now.

**Comment by balthasar0810** [comment]
The plots are there, thanks! But, they look different from the vignette. Don't know if this has sth to do with my data or code-related stuff. 
<img width="900" alt="Screen Shot 2021-01-28 at 7 41 16 PM" src="https://user-images.githubusercontent.com/10234124/106183711-dddf6980-61a0-11eb-81fe-3c1b0951a929.png">

**Comment by HectorRDB** [comment]
Are you using the data from the vignette? If not, then it is expected. Otherwise, I will check this

**Comment by balthasar0810** [comment]
It is my own data. How is this expected? For instance, I thought the second plot is supposed to decline...

**Comment by HectorRDB** [comment]
Hi,
It is in theory but as you will see here, the variations on the y-axis are very small in magnitude so those types of plots are not surprising

**Comment by HectorRDB** [comment]
Closed for inactivity after one month. Feel free to reopen if need be.
