### ISSUE TITLE
Question about the number of converged genes

### ISSUE THREAD

**Issue by Evenlyeven** [statOmics/tradeSeq#210]
Thanks for developing the wonderful package!

I am checking how many genes in my dataset are converged after GAM fitting. By using the command `table(rowData(sce.epi)$tradeSeq$converged)`, I got 
`FALSE  TRUE `
` 3898 20718 `
I wonder if the unconverged gene rate shown above is acceptable. Any suggestion about cutoff value of converged gene number or rate?

Thank you in advance!

**Comment by koenvandenberge** [comment]
Hi @Evenlyeven 

We do not really have cut-offs for this. What we have seen is that it may be that many of the genes that do not converge are lowly expressed in general, having zero expression in most cells and higher expression in a few others.  You may want to check this out.

Hope this helps.
