### ISSUE TITLE
Tradeseq with custom Gene x Pseudotime matrices

### ISSUE THREAD

**Issue by jblich870** [statOmics/tradeSeq#214]
Hi,

I have a single cell multiomics (RNA + ATAC seq) dataset, and have used another programme (ArchR) to generate pseudotime trajectories. I have 2 trajectories of interest - for each I have a matrix with genes in rows and pseudotime (1 to 100) in columns. The values in the matrix reflect expression of the gene at each point along pseudotime (scaled to -1.5 to 1.5). I also have motif x pseudotime matrices for each trajectory.

Is there a way to plug these matrices into Tradeseq? Is there any other information I would need? 

I also have pseudotime values for cells along each trajectory (ie distance along pseudotime) - but not cell weights (is this critical?).

I have count matrix (gene expression x cell, or motif deviations x cell), UMAP embedding co-ordinates for each cell, and cluster information and any other metadata for each cell if needed.

I searched but had difficulty finding out how to input trajectory data that wasn't generated in either Slingshot or Monocle.
Would be grateful for any help!
Best wishes,
J

**Comment by jpblich** [comment]
Just to add: the trajectory function implemented within ArchR has been adjusted so that it now provides 1) each cell's position along a given trajectory, and 2) a distance value for each cell to the trajectory. It should therefore be possible to calculate cell weights using these distance values.

**Comment by koenvandenberge** [comment]
Hi @jpblich 

It's certainly possible to use custom pseudotime and cell-level weights matrices as input. Please see the `pseudotime` and `cellWeights` argument in `fitGAM`. This is also done in our tradeSeq vignette which you can find on the Bioconductor website of our package.

You may want to think about the parametric assumption that you will be making on your response variable. For example, the motif data are not counts and you may consider a Gaussian or other distribution to model these. This is possible in `fitGAM` using the `family` argument.

Hope this answers your question.

**Comment by jpblich** [comment]
Hi,

Many thanks for the reply, that's really helpful.

Please could you advise on the best way to calculate cell weights with the distance values output by ArchR? The distances are "Euclidean distance of each cell to the nearest point along the manifold" (from: https://www.archrproject.com/bookdown/trajectory-analysis-with-archr.html). 

I thought perhaps to assign a weight between 0 and 1 based on the relative distance to each trajectory (e.g. if distance of cell to traj A is 1 and to traj B is 4, to assign 0.25 for traj A and 0.75 for traj B). Would that work for Tradeseq?

Many thanks,
J

**Comment by jpblich** [comment]
Answered here:
https://github.com/kstreet13/slingshot/issues/205

**Comment by koenvandenberge** [comment]
Hi @saum-kmr,

Thank you for reporting. This was an oversight on our end and was a check that all values should be non-negative when modeling counts. This should now be fixed when installing the latest version from GitHub.
