### ISSUE TITLE
Remove spurious rowData calls in hypothesis tests.

### ISSUE THREAD

**Issue by jgilis** [statOmics/tradeSeq#216]
At the moment, the different hypothesis tests run slower on GAM object than on SCE objects.
This is because of spurious `rowData`  calls, which are required for obtaining the betas and sigmas, inside a `lapply` loop.
For example in `diffEndtest`: https://github.com/statOmics/tradeSeq/blob/84ab467c80d53b0b92094aa3014e67495f7fe08d/R/diffEndTest.R#L87

Suggested enhancement: move the `rowData` call upstream of the loop and call only once.

**Comment by koenvandenberge** [comment]
This has now been adapted, thanks!
