### ISSUE TITLE
Error when trying to install tradeSeq - related to predictSmooth.R

### ISSUE THREAD

**Issue by lc822** [statOmics/tradeSeq#22]
Hi,

I am getting the following error when I try to install tradeSeq from GitHub.

> Error in .install_package_code_files(".", instdir) : 
> files in '/tmp/Rtmp53eb56/R.INSTALL3afa38d2d837/tradeSeq/R' missing from 'Collate' field:
>   predictSmooth.R
> ERROR: unable to collate and parse R files for package 'tradeSeq'
> \* removing '/t1-data/user/lgarner/py36-v1/conda-install/envs/tradeseq/lib/R/library/tradeSeq'

I can see that predictSmooth was added in a recent commit.  It appears to be missing in the Collate section of the DESCRIPTION file.

Best wishes,
Lucy

**Comment by koenvandenberge** [comment]
Hi Lucy

Thanks for letting us know! Should be fixed now.

Best,
Koen
