### ISSUE TITLE
associationTest for multiple conditions

### ISSUE THREAD

**Issue by flde** [statOmics/tradeSeq#227]
Dear TradeSeq Team, 

many thanks for the great tool! I was wondering about the best practice for using the associationTest with multiple conditions? I have only one lineage and two conditions. When I run associationTest with lineage=FALSE the results have no condition information attached. When I run associationTest with lineage=TRUE the results are split by condition. 

However, using lineage=TRUE only yields one log2FC for both conditions but I thought the log2FC should also be per condition/smoother. 

Highly appreciate your help!

Best, 
Florian

**Comment by koenvandenberge** [comment]
Hi @flde,

You should indeed set `lineages=TRUE`. The log2FC is just a median log2FC across all points being compared in the trajectory. We do not provide one per condition separately.

**Comment by flde** [comment]
Dear @koenvandenberge, 

Now I see it. With lineages=TRUE and global=FALSE there is still an log2FC column attached but that is just the log2FC from the global test. 

Many thanks for taking the time helping me out with that. 

https://github.com/statOmics/tradeSeq/blob/b467a59152ae46c15e2430ce0672665bb15a950b/R/associationTest.R#L402-L411
