### ISSUE TITLE
about the relative levels between 2 lineages of interest

### ISSUE THREAD

**Issue by pchiang5** [statOmics/tradeSeq#229]
Hello,

When I run `DD = earlyDETest(gamList,  knots = c(2,3 ),  pairwise = TRUE,  global = T )`, how do I know if GAP in lineage 1 is higher or lower compared with lineage 2? If I am only interested in the difference between lineages 1 and 2, how to compare these 2 lineages alone? 

Thank you.

> 
>  head(DD, 1)
>     waldStat df pvalue waldStat_1vs2 df_1vs2  pvalue_1vs2 waldStat_1vs3 df_1vs3
> GAP 143.6421  8      0      39.25156       4 6.180775e-08      76.66353       4
>      pvalue_1vs3 waldStat_1vs4 df_1vs4  pvalue_1vs4 waldStat_2vs3 df_2vs3
> GAP 8.881784e-16      58.38188       4 6.344703e-12      100.2394       4
>     pvalue_2vs3 waldStat_2vs4 df_2vs4 pvalue_2vs4 waldStat_3vs4 df_3vs4
> GAP           0       5.84513       4   0.2110164      87.05488       4
>     pvalue_3vs4  fcMedian
> GAP           0 0.7729633

**Comment by koenvandenberge** [comment]
Hi @pchiang5 ,

I would recommend using visualization to check the direction of the difference using, e.g., `plotSmoothers`.
