### ISSUE TITLE
Error running plotSmoothers with one lineage sce object

### ISSUE THREAD

**Issue by Jon-bioinfo** [statOmics/tradeSeq#23]
I'm getting an error running plotSmoothers: 
`> plotSmoothers(sce, counts, gene = 'Fasn')`
`Error in pseudotime[lineageID == ii, ii] : incorrect number of dimensions`

The counts, pca and clusters are from Seurat:
`counts <- as.matrix(so@assays$RNA@counts)` 
`lin <- getLineages(so@reductions$pca@cell.embeddings[, 1:10], clusterLabels = cl, start.clus = 4, end.clus=2)`
`crv <- getCurves(lin)`
`sce <- fitGAM(counts = counts[id, ],
              sds = crv,
              nknots = 7
              )`

![image](https://user-images.githubusercontent.com/40158588/70708641-59bcef00-1d1e-11ea-84c2-aabc4f90ec3b.png)

I think this is due to having only one lineage and an sce object:

In the `.plotSmoothers_sce` function the code `pseudotime <- slingshotColData[,grep(x = colnames(slingshotColData), pattern = "pseudotime")]` returns a vector not a data frame when there is just one curve.

Thanks,

**Comment by HectorRDB** [comment]
Hey,
Thanks for pointing this out, this was indeed the issue. It should be fixed now, you can install the newest devel version of tradeSeq with 
```
devtools::install_github("statOmics/tradeSeq")
```
Let me know if anything else is unclear. There should not be any other issues for the one lineage case but this situations has been less thoroughly benchmarked so there might be some more bugs.

**Comment by Jon-bioinfo** [comment]
Thanks,

The same problem exists in the `.clusterExpressionPatterns` function.

**Comment by HectorRDB** [comment]
Hi,
Thanks for being so thorough, it really help us a lot.
