### ISSUE TITLE
Plotting own trajectories to use with tradeSeq [Question]

### ISSUE THREAD

**Issue by Tommy0398** [statOmics/tradeSeq#236]
Hi TradeSeq team, 

This is a bit of a odd question but I was wondering if there was a way to manually define trajectories and then use these with tradeSeq, to identify genes that are different along these self-defined trajectories and to observe them with plotSmoothers. The reason for wanting this is because for very similar cell types that don't have alot of well defined structure in the UMAP, I'm not confident in the trajectories that I've defined by slingshot or monocle and it would be a nice way to explore the expression of genes within the UMAP space. This is with the caveat that these might not be real trajectories but it would be useful to investigate this regardless if there is a simple way to do this.  

Regards,
Tom

**Comment by koenvandenberge** [comment]
Hi @Tommy0398 

I am unaware of a simple way of doing this. I see you have been discussing with Kelly, so I'll close this thread; feel free to reopen if relevant.
