### ISSUE TITLE
Pseudotime values and clustering

### ISSUE THREAD

**Issue by Jon-bioinfo** [statOmics/tradeSeq#24]
In the vignette there are two different values called 'Pseudotime'. 0 to ~1 based on the curve, and then after the clustering analysis 1-20 based on the nPoints used.

For easier interpretation could those points based on nPoints be labeled with the corresponding pseudotime value from above?

Also this code is not fixed in the other function i mentioned? https://github.com/statOmics/tradeSeq/issues/23#issuecomment-565271735

**Comment by HectorRDB** [comment]
Thanks for that, 
The columns of the output are now named. For example, the first column is `l1:t0`, the second is `l1:t0.0586970433725466`. 
Let me know if this is not clear.
