### ISSUE TITLE
evaluatek never completes

### ISSUE THREAD

**Issue by eblchen** [statOmics/tradeSeq#240]
Hi, I've been testing out tradeSeq on a subset of my data and can't seem to get evaluateK to finish running. Even testing on only 10 genes it doesn't finish running after 24 hours.
My counts matrix is 17550 x 5977.
and I've been running this code:
multicore <- BiocParallel::MulticoreParam(workers = 4)
rd <- reducedDim(sce, "PCA")
cl <- kmeans(rd, centers = 4)$cluster
sce$Cluster_Num <- cl
sce <- slingshot(sce, clusterLabels = "Cluster_Num", reducedDim = "PCA", start.clus = 3)
sds <- SlingshotDataSet(sce)
counts <- counts(sce)
aic.mat <- evaluateK(counts = counts, sds = sds, k = 3:10, nGenes = 200, verbose = FALSE, plot = TRUE, parallel = TRUE, BPPARAM = multicore)
Is there anything I can do to try and resolve this or anything I've missed?

**Comment by koenvandenberge** [comment]
Hi @eblchen 

In some cases, when using parallelization, it seems like the code never finishes, for some obscure reason I do not understand. 
You may want to try running it without parallelization, just to check if that is causing the issue. 

Best,
Koen
