### ISSUE TITLE
running fitGAM on Single cell expt object for multiple lineages

### ISSUE THREAD

**Issue by klai001** [statOmics/tradeSeq#242]
Hi, i have gotten ~3 different lineages through slingshot, and im interested in within lineage comparison.
i am abit confused if i have to subset the individual lineages to run the fitGAM()
or am i able to run fitGAM() to the entire single cell expt object, which would allow processing of each lineage independently.

**Comment by koenvandenberge** [comment]
Hi @klai001 

There is no need to subset cells or lineages, we fit the GAMs for all lineages in the trajectory simultaneously (on the entire `SingleCellExperiment` object indeed).
Please see [our vignette](https://www.bioconductor.org/packages/release/bioc/vignettes/tradeSeq/inst/doc/tradeSeq.html) for details.
