### ISSUE TITLE
choosing knot

### ISSUE THREAD

**Issue by AndreaYCT** [statOmics/tradeSeq#244]
Hi, 

I have an integrated Seurat dataset and analyzed evaluateK() as attached pdf. I would like to know how to determine k in my case.

Many thanks

[k result.pdf](https://github.com/statOmics/tradeSeq/files/13263982/k.result.pdf)

**Comment by koenvandenberge** [comment]
Hi @AndreaYCT 

In cases like this, where it is not consistent across the different visualizations, I often fall back to the first and third plot in your figure. Base on this, I would probably go for 6 knots as the AIC decrease after that becomes much smaller.

**Comment by AndreaYCT** [comment]
Thank you so much! I’m ready to proceed! 


> Hi @AndreaYCT
> 
> In cases like this, where it is not consistent across the different visualizations, I often fall back to the first and third plot in your figure. Base on this, I would probably go for 6 knots as the AIC decrease after that becomes much smaller.
