### ISSUE TITLE
problem output assoress lineage = TRUE which column correspond to what

### ISSUE THREAD

**Issue by A-legac45** [statOmics/tradeSeq#248]
![Capture d’écran 2024-01-08 à 18 38 20](https://github.com/statOmics/tradeSeq/assets/101135798/9f4e0a62-754e-4d7f-a5d2-781165eb7024)

The p-value go until -6

Hello, 
I would like to have some explanation 

I run fitgam and assoress  as followed on a data set containing 
class: SlingshotDataSet 
lineages: 6 
curves: 6 

assocRes <- associationTest(sce, lineages = TRUE, l2fc = log2(2))

I do not get the output of assores which column correspond to which lineage?

Thanks for your help

**Comment by A-legac45** [comment]
> I believe columns containing '_1' in their names correspond to lineage 1, and '_2' lineage 2, and so on.

So what are the 3 first columns containing no _number?

thanks

**Comment by koenvandenberge** [comment]
Hi @A-legac45 

The first three columns containing no number are tests performed across all lineages, so-called global or omnibus tests. We describe this in detail in our manuscript as well.
