### ISSUE TITLE
Can we implement more efficient plotting?

### ISSUE THREAD

**Issue by koenvandenberge** [statOmics/tradeSeq#25]
On large datasets, `plotSmoothers` takes relatively long and consumes a lot of memory. Can we do better?

**Comment by koenvandenberge** [comment]
Similar for `predictSmooth`

**Comment by HectorRDB** [comment]
Have you benchmarked the code? My guess is that the plotting itself is slow, not the rest of the code. If that is the case, we could try to sample cells and only show a subset?
