### ISSUE TITLE
plotSmoothers curves seem to contradict startVsEndTest logFC

### ISSUE THREAD

**Issue by Dazcam** [statOmics/tradeSeq#255]
Hello tradeSequers,

I'm a bit stumped with the correspondence between the `startVsEndTest()` output and the `plotSmothers()` output. 

I've run `startVsEndTest()` on a trajectory with 3 lineages. 

```r
startRes <- startVsEndTest(sce_ts, lineages = TRUE, l2fc = 0.5)
```

I'm interested in pulling out genes that are more highly expressed at the end point the lineages / pseudotime, so I use the following code to select genes with a `logFC < 0` in each lineage (one lineage shown):

```r
lin1_up <- startRes %>%
  as_tibble(rownames = 'genes') %>%
  select(genes, waldStat_lineage1, df_lineage1, pvalue_lineage1, logFClineage1) %>%
  filter(logFClineage1 < 0) %>%
  arrange(pvalue_lineage1) %>%
  filter(pvalue_lineage1 < 0.05) 
```

<details>

<summary>Here are the `startVsEndTest()` results for 4 genes of interest across the 3 lineages:</summary>

```r
> lin1_up %>% filter(genes %in% c("NXPH1", "FAM83D", "KLF6", "GPR98"))

# A tibble: 2 × 5
  genes  waldStat_lineage1 df_lineage1 pvalue_lineage1 logFClineage1
  <chr>              <dbl>       <dbl>           <dbl>         <dbl>
1 NXPH1               48.6           1        3.15e-12         -4.63
2 FAM83D              18.8           1        1.49e- 5         -6.50

> lin2_wald_up %>% filter(genes %in% c("NXPH1", "FAM83D", "KLF6", "GPR98"))

# A tibble: 3 × 5
  genes  waldStat_lineage2 df_lineage2 pvalue_lineage2 logFClineage2
  <chr>              <dbl>       <dbl>           <dbl>         <dbl>
1 KLF6               123.            1     0                   -1.87
2 GPR98               25.1           1     0.000000534         -2.00
3 FAM83D             146.            1     0                   -5.46

> lin3_up %>% filter(genes %in% c("NXPH1", "FAM83D", "KLF6", "GPR98"))

# A tibble: 1 × 5
  genes  waldStat_lineage3 df_lineage3 pvalue_lineage3 logFClineage3
  <chr>              <dbl>       <dbl>           <dbl>         <dbl>
1 FAM83D              83.1           1               0         -5.11
```

</details>

Perhaps my understanding is incorrect, but as I'm selecting `logFC values < 0`, and the `logFC` results for all 4 genes are indeed negative, when plotting the smoothers for these genes I would expect the curve to be rising later in pseudotime and for all curves to be 'generally' similar. The results for NXPH1 in lineage 1 is what I'd expect, i.e. the curve rising later in pseudotime, but for FAM83D and GPR98, the opposite is true, expression is higher at the start of the corresponding lineages rather than at the end.

<img width="704" alt="Screenshot 2024-03-05 at 10 58 27" src="https://github.com/statOmics/tradeSeq/assets/22788904/54f9f798-afe6-4427-8d64-04c361bc2927">

Is my understanding of the directionality of `logFC` correct in this context, or is there a flaw in how I'm interpreting the relationship between the `startVsEndTest()` and`plotSmothers()` outputs? I understand that curves may not always be ideal, but the fact curves rise in opposite directions when selecting for a particular direction is disconcerting.

Any advice you could offer here would be most welcome.

Many Thanks,

Darren

**Comment by pansika** [comment]
I have a similar issue. Genes that were highly expressed in `plotSmoothers` plot were basically absent in the heatmap from `predictSmooth`.
I am seeing similarities to this issue from last year: https://github.com/statOmics/tradeSeq/issues/237
When I set `tidy = FALSE `I get indeed different values than when I set it to `tidy = TRUE`.

**Comment by koenvandenberge** [comment]
Hi @Dazcam 

Apologies for the delay on responding to this. 

The logFC values are comparing the end point with the start point (end - start; see [here](https://github.com/statOmics/tradeSeq/blob/master/R/startVsEndTest.R#L39)). If the logFC is negative, the starting point should hence be higher in estimated average expression than the end point. 

What are the log fold changes for the four genes you are plotting?

**Comment by ayyildizd** [comment]
I have the same issue, I calculate the genes with startVsEndTest and logFC>0 genes appear to be high at the end of the trajectory when I plot heatmap using predictSmooth.

**Comment by Dazcam** [comment]
> Hi @Dazcam
> 
> Apologies for the delay on responding to this.
> 
> The logFC values are comparing the end point with the start point (end - start; see [here](https://github.com/statOmics/tradeSeq/blob/master/R/startVsEndTest.R#L39)). If the logFC is negative, the starting point should hence be higher in estimated average expression than the end point.
> 
> What are the log fold changes returned by `startVsEndTest` for the four genes you are plotting?

Hi [koenvandenberge](https://github.com/koenvandenberge),

No probs. 
I understand your point regarding start - end. Thanks for the clarification.



For FAM83D the logFC results and the curves in the plots correspond nicely as you describe, starting point of the curve **is** higher in estimated average expression than the end point and there is a negative logFC.

But compare that to the results for NXPH1, there is a

**Comment by koenvandenberge** [comment]
Thanks for following up, @Dazcam.

I suggest calculating the fitted values at the minimum and maximum pseudotime to check the numbers. It is hard from the visualizations provided to confirm indeed whether start or end is higher for the NXPH1 gene; it's just very low for both start and end points.

**Comment by Dazcam** [comment]
No probs. Thank you for your insight.
