### ISSUE TITLE
cluster gene expression patterns within a lineage

### ISSUE THREAD

**Issue by shokohirosue** [statOmics/tradeSeq#26]
Thank you for developing/maintaining a great package.

Would it be possible to cluster different expression pattern within a single lineage? 

I am interested in which genes' expression show the same pattern as my gene of interest along a specific lineage.

What do you think is the best way to do this?

Please let me know if anything's unclear.
Thank you so much for your help.

**Comment by HectorRDB** [comment]
Thanks for your interest. It's a good idea but it might take a little time to implement.
In the meantime, a short quick would be:
- run the full clustering with `clusterExpressionPatterns`. 
- Extract the `yhatScaled` object from the result and subset to the lineage of interest.
- Run 
```
rsec <- clusterExperiment::RSEC(t(yhatPatScaled_filtered),
                                  isCount = FALSE, "PCA", nReducedDims = 10, minSizes = 6, ncores = 1,
                                  random.seed = 176201, verbose = TRUE)
```
You can of course tweak the parameters from RSEC, I'll refer you to the clusterExperiment package

Let me know if this is clear.
Best

**Comment by shokohirosue** [comment]
Thank you so much for your reply!

May I ask how you would subset `clusPat$yhatScaled` to the lineage of interest? I have not been able to figure out where the information re. lineage is stored in this object. Would you mind telling me how the clusPad (`clusterExpressionPatterns` output) is structured?

Thank you very much for your help!

Best,
Shoko

**Comment by koenvandenberge** [comment]
Since you mentioned there was only a single lineage it seems unneccesary

**Comment by koenvandenberge** [comment]
Hi, 

We have recently added a new section to the vignette to extract fitted values you can use as input to any clustering algorithm of interest, please see https://github.com/statOmics/tradeSeq/blob/master/vignettes/tradeSeq.Rmd#L357-L371

The `clusPat` object is a list with 2 elements, the RSEC object (`clusPat$rsec`) and the scaled fitted values (`clusPat$yhatScaled `). The latter is obtained through `predictSmooth` and scaling each gene to have zero mean and unit variance.
Note that `predictSmooth` (and thus also `clusterExpressionPatterns`) have an argument `nPoints` argument. This specifies how many points you'd like to use in the clustering. If, for example, you have two lineages and set `nPoints=40`, then the first 40 elements will correspond to the fitted values of the first lineage on a grid of 40 points equally spaced from start to the end. Elements 41 to 80 will correspond to the second lineage.

We have added names to the output to specify this, e.g.: 
```
> predictSmooth(models = sce, counts = counts, gene = "Irf8", nPoints = 10)
      lineage1_1 lineage1_2 lineage1_3 lineage1_4 lineage1_5 lineage1_6 lineage1_7 lineage1_8 lineage1_9
Irf8 0.001905777 0.02084079  0.1604907  0.6130321   1.060506   1.595464     2.7232   2.615385  0.6884649
     lineage1_10 lineage2_1 lineage2_2 lineage2_3 lineage2_4 lineage2_5 lineage2_6 lineage2_7 lineage2_8
Irf8  0.06614376  0.1347597  0.1136166 0.09456779 0.07671556  0.0599924 0.04697778 0.04030393 0.03805659
     lineage2_9 lineage2_10
Irf8 0.03339763  0.02717615
```
If you'd like to find genes that behave similarly as your gene of interest I'd recommend the following workflow:

 1. Extract fitted values for the lineage of interest for all genes you'd like to cluster
 2. Use these fitted values to cluster all genes using your preferred clustering method
 3. Check which cluster your gene of interest is clustered in and extract all other genes that are also in that cluster, which should behave similarly as your gene of interest.
