### ISSUE TITLE
unable to find an inherited method for function ‘fitGAM’ for signature ‘"CellDataSet"’

### ISSUE THREAD

**Issue by rahulnutron** [statOmics/tradeSeq#32]
Dear Tradeseq team,

Thanks for the tool.
I am working on scRNA-seq data. I installed tradeSeq and loaded it. I followed the vignette online that uses monocle. However the function fitGAM is not working. Thanks for any help in advance!

Regards,
Rahul

library(Seurat)
library(monocle)
library(tradeSeq)
library(RColorBrewer)
library(SingleCellExperiment)
library(dplyr)
library(tidyr)
set.seed(42)

omd.data <- Read10X(data.dir = "D:/plant_new/outs/filtered_feature_bc_matrix/",gene.column = 1)
omd.dataset <- CreateSeuratObject(counts = omd.data,  min.cells = 2, min.features = 200, project = "OMD")
data <- as(as.matrix(omd.dataset@assays$RNA@counts), 'sparseMatrix')

pd <- new('AnnotatedDataFrame', data = omd.dataset@meta.data)

fData <- data.frame(gene_short_name = row.names(data), row.names = row.names(data))
fd <- new('AnnotatedDataFrame', data = fData)
cds <- newCellDataSet(data,
                          phenoData = pd,
                          featureData = fd)

cds <- estimateSizeFactors(cds)
cds <- reduceDimension(cds)

cds <- orderCells(cds)
cds <- orderCells(cds, root_state = 5)
sce <- fitGAM(cds, verbose = TRUE)
Error in (function (classes, fdef, mtable)  : 
  unable to find an inherited method for function ‘fitGAM’ for signature ‘"CellDataSet"’

**Comment by HectorRDB** [comment]
Hi,
Please ensure that you installed the devel version of `tradeSeq`, either from Bioconductor  with `BiocManager::install("tradeSeq", version = "devel")` of from Github `devtools::install_github("statOmics/tradeSeq")`.

**Comment by rahulnutron** [comment]
Thanks! I installed from github and the error is gone but this time it brings a new error. However, it might be related to monocle.

> sce <- fitGAM(cds, verbose = TRUE)
Error in rename(., Y = V1) : 
  arguments in '...' must be character and not NA

**Comment by HectorRDB** [comment]
Thanks a lot for testing `tradeSeq` for us. We just installed a `monocle` option for the functions so it is expected that we have some bugs and we really appreciate you testing it.
I have just push a minor update to the github repo which should fix what I suspect the issue is (I was using rename without specifying that it was dplyr::rename so it might have been using a different function depending on the order in which you loaded your packages)
Would you please re-install tradeSeq form Github and check it it works?
Thanks

**Comment by rahulnutron** [comment]
Thank you! I installed from github again. This time gives a message ('tradeSeq has been updated to accommodate...') when I load the package, meaning its the latest one. However, unfortunately another error appears. I need to check with other data though to make sure its not for my data. But my monocle trajectory and pseudotime plots are fine.

> sce <- fitGAM(cds, verbose = TRUE)
Error in (function (classes, fdef, mtable)  : 
  unable to find an inherited method for function ‘fitGAM’ for signature ‘"dgCMatrix"’
>

**Comment by HectorRDB** [comment]
Hi,
This comes from constructing the `cds` object with a sparse matrix. For now, tradeSeq does not accomodate those. Please change this line
`data <- as(as.matrix(omd.dataset@assays$RNA@counts), 'sparseMatrix')` to 
`data <- as.matrix(omd.dataset@assays$RNA@counts)` when constructing your object.
