### ISSUE TITLE
Transferring data from Seurat and general question about test to use

### ISSUE THREAD

**Issue by s849** [statOmics/tradeSeq#45]
Hi,

Thank you for developing tradeseq. I want to try tradeseq to calculate differential gene expression in a time series data. For example, I have data sets from four different time points. I integrated the data sets with Seurat to find common cells across the four time points. Now, I want to identify gene changes across time in "cluster 1" for example. That is, I want to see genes that are uniquely expressed in early, mid, or late time point for this particular cell type. Is it possible to use Tradeseq to accomplish this? If so, what test will be best to implement?

Lastly, how can I transfer input data from Seurat to Tradeseq?

Thank you.

**Comment by koenvandenberge** [comment]
Hi,

Thanks for your interest in tradeSeq.
If your variable of interest consists of the 4 discrete time points, then it seems like a standard differential expression analysis with those 4 factor levels would be what you're interested in, e.g. using edgeR or DESeq2 packages and testing for DE within/between time points.

If, instead, you expect a continuous trajectory across these four timepoints, then you can take a look whether fitting a trajectory using methods like Slingshot would make sense. In that case, yes, you can use tradeSeq to discover genes that have different expression over time.

There is no special procedure (needed) to transfer data from Seurat to tradeSeq. tradeSeq only needs the gene expression counts, and the estimated pseudotime for each cell.

**Comment by s849** [comment]
Hi,

Thank you for your response. I think I would like to give both a try.

BTW, Do you know of any good resources/examples of how to perform edgeR/DESeq2 on more than 2 data sets with single cell data?I have never done this this way, only with bulk RNA-seq data sets.

**Comment by koenvandenberge** [comment]
I have no real experience with Seurat integration, but I'd think that if you've properly integrated and normalized the datasets, analysis could proceed as usual, in similar vein as a bulk RNA-seq datasets, so I'd refer to the Seurat and edgeR/DESeq2 manuals. If you're working with Smart-Seq2 data you may consider taking into account zero inflation.
