### ISSUE TITLE
evaluateK to estimate nknots necessary when using Monocle to generate pseudotime?

### ISSUE THREAD

**Issue by BrianLohman** [statOmics/tradeSeq#46]
Hello,

I am using tradeSeq downstream of calculating pseudotime with Monocle. The Monocle vignette ends with the construction of ```sce``` 

```
sce <- fitGAM(counts = counts,
       pseudotime = pseudotime,
       cellWeights = cellWeights)
```

and links back to the main vignette. However, in the main vignette the construction of ```sce``` by fitGAM follows the nknots estimation procedure with evaluateK. 

```
set.seed(5)
icMat <- evaluateK(counts = counts, sds = crv, k = 3:10, 
                   nGenes = 200, verbose = T)
set.seed(7)
pseudotime <- slingPseudotime(crv, na = FALSE)
cellWeights <- slingCurveWeights(crv)
sce <- fitGAM(counts = counts, pseudotime = pseudotime, cellWeights = cellWeights,
                 nknots = 6, verbose = FALSE)
```

Does this mean that the evaluateK step is unnecessary when fitGAM is applied to the output from Monocle? 

Thanks for you help,

Brian

**Comment by HectorRDB** [comment]
Hi,
Thanks a lot for this comment. We have not yet developed a functionality so that `evaluateK` works with a `monocle` input and I had forgotten to add it to the TODO list. I'll work on adding it and will update you when it is done

**Comment by BrianLohman** [comment]
Hi Hector,

Okay, thanks for your continued effort. I see that when passed a ```CellDataSet``` the ```fitGAM``` function uses the default of ```nknots = 6```. I'll stick with that for now. 

Cheers,

Brian

**Comment by HectorRDB** [comment]
Hi Brian,
Thanks for those issues, they are very helpful. 
While I am working on this (and #4), you can see how we extract cellWeights and pseudotime for use in `fitGAM` when the input is a monocle object.  You can see the code with `getMethod("fitGAM","CellDataSet")`. 
This will be a bit hacky but if you are in a hurry, it might be your best shot

**Comment by HectorRDB** [comment]
Hi,
The latest commit should make evaluateK work with a `CellDataSet` input. I also added an `extract_monocle_info` function which should help you check out the weights and pseudotime of each cell.
Best,

**Comment by BrianLohman** [comment]
Hi @HectorRDB,

Awesome! Thanks. I'll pull the latest version and give this a try as soon as I can. 

Cheers,

Brian
