### ISSUE TITLE
predictSmooth

### ISSUE THREAD

**Issue by evgeniilobzaev** [statOmics/tradeSeq#48]
Hello!

When I am trying to run "predictSmooth" function (either for my data or as in example provided: https://statomics.github.io/tradeSeq/reference/predictSmooth.html) I got an error: **could not find function "predictSmooth"**. Is there something wrong I am doing?

Thank you.

Evgenii

**Comment by HectorRDB** [comment]
Hi,
I think you are using the previous version of tradeSeq (versions < 1.1). You can update from bioconductor or get the latest version from github. 
If you want us to be better able to diagnostic the issue, please provide your session info.

**Comment by koenvandenberge** [comment]
Hi @evgeniilobzaev 
We recently discovered a bug in `predictSmooth` where the gene names got mixed up, so please install the latest `tradeSeq` version from GitHub.

**Comment by evgeniilobzaev** [comment]
Hi,
Yeah, that worked! Thank you.
One more question. How exactly can I obtain the points that are used as the mean trajectory in the `plotSmoothers`?  By default it uses 100 points, but my pseudotime input can be of arbitrary length and not necessarily uniformly distributed along [0,1]. I wanted to get the predicted(smoothed) estimates at the pseudotime points. I thought that `predictSmooth` function serves for this purpose.

**Comment by koenvandenberge** [comment]
I'm not sure if I fully understand your question above, but `predictSmooth` does give you the fitted smooth line that is also shown in `plotSmoothers`. The 100 points is just an arbitrary number and can be varied as you'd like. If you are rather interested in obtaining the fitted value for each cell, you can use the `predictCells` function.

**Comment by HectorRDB** [comment]
Hi,

**Comment by HectorRDB** [comment]
Hi,
The `nPoints` values are equally spaced in pseudotime along each lineage. So for example, if your pseudotime goes from zero to `x`, then you can can get the pseudotime values on the original time scale with `seq(from = 0, to = x, length.out = nPoints)`

**Comment by evgeniilobzaev** [comment]
Hi,
 
I understand. Thank you for your help!

Evgenii
