### ISSUE TITLE
install_github error (Error: object ‘as.phylo.dendrogram’ is not exported by 'namespace:dendextend')

### ISSUE THREAD

**Issue by zhangjiaobxy** [statOmics/tradeSeq#5]
Hello tradeSeq team,
I am trying to install tradeSeq, but got the following error. I am not sure if this is caused by some dependency packages or not. Could you please have a look? Thanks.

1. installation error:
> devtools::install_github("statOmics/tradeSeq")
Downloading GitHub repo statOmics/tradeSeq@master
Skipping 2 packages ahead of CRAN: Biobase, BiocGenerics
✔  checking for file ‘/private/var/folders/x9/m8c7s8ms3dl8m7wnl60hc3fw0000gn/T/RtmpU98tv9/remotesa9fd5959d33a/statOmics-tradeSeq-46836ab/DESCRIPTION’ ...
─  preparing ‘tradeSeq’: (418ms)
✔  checking DESCRIPTION meta-information ...
─  checking for LF line-endings in source and make files and shell scripts
─  checking for empty or unneeded directories
─  looking to see if a ‘data/datalist’ file should be added
─  building ‘tradeSeq_0.9.0.tar.gz’
   
* installing *source* package ‘tradeSeq’ ...
** using staged installation
** R
** data
*** moving datasets to lazyload DB
** byte-compile and prepare package for lazy loading
Warning: multiple methods tables found for ‘rowSums’
Warning: multiple methods tables found for ‘colSums’
Warning: multiple methods tables found for ‘rowMeans’
Warning: multiple methods tables found for ‘colMeans’
Error: object ‘as.phylo.dendrogram’ is not exported by 'namespace:dendextend'
Execution halted
ERROR: lazy loading failed for package ‘tradeSeq’
* removing ‘/Library/Frameworks/R.framework/Versions/3.6/Resources/library/tradeSeq’
Error in i.p(...) : 
  (converted from warning) installation of package ‘/var/folders/x9/m8c7s8ms3dl8m7wnl60hc3fw0000gn/T//RtmpU98tv9/filea9fd183ab2aa/tradeSeq_0.9.0.tar.gz’ had non-zero exit status

2. 
> sessionInfo()
R version 3.6.0 (2019-04-26)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS Mojave 10.14.4

Matrix products: default
BLAS:   /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/3.6/Resources/lib/libRlapack.dylib

locale:
[1] en_CA.UTF-8/en_CA.UTF-8/en_CA.UTF-8/C/en_CA.UTF-8/en_CA.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] usethis_1.5.0  devtools_2.0.2

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.1        ps_1.3.0          prettyunits_1.0.2 rprojroot_1.3-2   withr_2.1.2       digest_0.6.18     crayon_1.3.4     
 [8] assertthat_0.2.1  R6_2.4.0          backports_1.1.4   magrittr_1.5      rlang_0.3.4       cli_1.1.0         curl_3.3         
[15] fs_1.3.1          remotes_2.0.4     rstudioapi_0.10   callr_3.2.0       desc_1.2.0        tools_3.6.0       glue_1.3.1       
[22] pkgload_1.0.2     compiler_3.6.0    processx_3.3.1    pkgbuild_1.0.3    sessioninfo_1.1.1 memoise_1.1.0

**Comment by kstreet13** [comment]
Hello!

I've encountered this error [recently](https://github.com/kstreet13/slingshot/issues/34) and it is originating from the `clusterExperiment` package. I have been told that if you update to the latest version of that package, it should be resolved. Otherwise, in the linked issue, we found a way to work around it by modifying the `dendextend` package.

**Comment by koenvandenberge** [comment]
I have now also moved clusterExperiment to the Suggested packages in the DESCRIPTION file, since it is not essential for the main analyses of tradeSeq.

**Comment by zhangjiaobxy** [comment]
Hi @kstreet13 and @koenvandenberge, 
Thank you very much for your help! After upgraded clusterExperiment package to version2.4.2, I have installed tradeSeq successfully! The two steps are as below:

1. install the latest clusterExperiment package:
if (!requireNamespace("BiocManager", quietly = TRUE))
    install.packages("BiocManager")
BiocManager::install("clusterExperiment")

2. install tradeSeq:
devtools::install_github("statOmics/tradeSeq")

Thanks again for your great help! Please feel free to close this issue. =)

**Comment by HectorRDB** [comment]
@koenvandenberge re-added clusterExperiment as a dependency, otherwise, it fails on R CMD Check.
