### ISSUE TITLE
Travis CI errors due to time limit

### ISSUE THREAD

**Issue by koenvandenberge** [statOmics/tradeSeq#50]
It seems to run out of time limit when running the tests.
Not sure if this is because the tests take too long or the upstream checks are taking too long.

https://travis-ci.com/github/statOmics/tradeSeq/builds/167128665

**Comment by HectorRDB** [comment]
It looks like the timeout happens even before the vignette are run. And the tests are quite fast I think. 
My guess is that installing 175 packages is far too long. I think we should discuss plans to reduce monocle dependencies...

**Comment by koenvandenberge** [comment]
Yeah you're right. I've been tracking the progress right now and installing dependencies finishes only after ~ 35 minutes, which is already the majority of our 50min time window.
I've tried moving `clusterExperiment` which has 140+ dependencies. Let's try to move Monocle and igraph too and see where that gets us.

**Comment by HectorRDB** [comment]
According to [this](https://stackoverflow.com/questions/29178171/travis-ci-r-suggested-package), travis will always install the packages from `suggests`... 
I will work on an idea from [this](https://docs.travis-ci.com/user/build-stages/warm-cache/) , using travis caches
