### ISSUE TITLE
"tidy" output for predictSmooth

### ISSUE THREAD

**Issue by mikelove** [statOmics/tradeSeq#51]
If I am interpreting correctly, `predictSmooth` returns a matrix with y-hat values ~for each cell~ along the pseudotime grid with lineages as concurrent sets of columns, and genes on rows. It would be useful to also provide optional "tidy" output with gene, lineage, time and y-hat as columns of a data.frame. I started to work this up using your `plotSmoothers` code which works for one gene but maybe an integrated solution would be a nice feature.

https://gist.github.com/mikelove/c91d293312b1cd2f9d71657819dc41a9

**Comment by koenvandenberge** [comment]
Hi Mike,

Thank you for the suggestion!
`predictSmooth` does not actually return fitted values for each cell (`predictCells` does that), it rather returns the estimated smoother over a uniform grid of pseudotime values, for each lineage. If lineage 1 ranges from pseudotime 0 to 20, then it will return a uniform grid of the estimated smoother at pseudotimes `seq(0,20,length.out=nPoints)`. If a second lineage ranges from pseudotime 0 to 18 it returns a grid along pseudotimes `seq(0,18,length.out=nPoints)`. Each column will be one of those grid points for a lineage, and the number of columns will be `nLineages * nPoints`.

But you make a very good point that the output would be easier to understand if it were tidy as in the code you suggest, thanks for that! I will work on adapting `predictSmooth` and `predictCells` to provide tidy output soon and ping you here.

**Comment by mikelove** [comment]
That's great.  Oops, I was typing faster than I was thinking, right, not along cells but along the pseudotime value grid. No rush on my end, just a thought I had after hacking the function to output a `df` instead of a plot.

Thanks! We've been trying it out on data in the group. Looks good!

**Comment by koenvandenberge** [comment]
The default output for `predictSmooth` is now a data frame with columns `lineage`, `time`,  `gene` and `yhat`. The original implementation that returns a matrix, which might be useful for quickly clustering genes, can be retrieved by setting `tidy=FALSE` in `predictSmooth`.

`predictCells` still returns a matrix; I think here it makes sense for it to have the same dimensions as the count matrix.

**Comment by mikelove** [comment]
Great! Agree. Thanks for the quick implementation!
