### ISSUE TITLE
Missing column name in associationTest result

### ISSUE THREAD

**Issue by asenabouth** [statOmics/tradeSeq#52]
Hello,

I ran the associationTest function on one lineage and noticed it returned the following table with a missing column name:

```csv
       waldStat_1 df_1     pvalue_1          
TTR   11536.81065    2 0.000000e+00 2.2708376
TAGLN   423.05309    2 0.000000e+00 0.9756171
GNRH1    97.19210    2 0.000000e+00 0.5709685
NTS      71.20226    2 3.330669e-16 0.7065319
SST      22.60593    2 1.233632e-05 0.1513369
ACTA2   147.81038    2 0.000000e+00 0.6753302
GAL      82.52678    2 0.000000e+00 0.5958516
PMCH    939.41146    2 0.000000e+00 4.9916745
MGP      25.07521    2 3.589123e-06 0.7239459
CRYAB  3319.44534    2 0.000000e+00 3.6121236
```

I assume the last column is supposed to be foldChange. Is this correct?
I am running tradeSeq_1.2.01.
Thanks!

**Comment by koenvandenberge** [comment]
Hi, 

Thank you for your interest in using `tradeSeq`.
Yes, those should be averages of the absolute values of the log fold changes. The missing column name was a bug that's fixed in more recent versions.
