### ISSUE TITLE
Error in fitGAM: can't correct step size

### ISSUE THREAD

**Issue by dakotakatz** [statOmics/tradeSeq#53]
Hi,

I am trying to run the fitGAM function on SlingshotDataSet and I keep getting the error: 

![Screen Shot 2020-05-29 at 10 19 58 AM](https://user-images.githubusercontent.com/65964066/83276286-ff153380-a195-11ea-8a4b-831c4ee0c55d.png)

When I tried running it by extracting the pseudotime and cellWeights from a SingleCellExperiment instead, I got an error that the pseudotime had NA values even though I had set na = FALSE in slingPseudotime.

Do you have any idea what is causing this error?

**Comment by koenvandenberge** [comment]
Hi,

Thank you for your interest in using `tradeSeq`.
This is an `mgcv` error which we did not catch, but we should have fixed that in recent versions of `tradeSeq`.
Could you please try re-installing the latest version of `tradeSeq` from GitHub and check whether the error persists?

**Comment by HectorRDB** [comment]
Closed after #57
