### ISSUE TITLE
evaluateK() error: promise already under evaluation

### ISSUE THREAD

**Issue by liuyigh** [statOmics/tradeSeq#54]
Dear developer,

I installed the "conditions" branch. I ran `slingshot` with `seurat` object and got nice trajectories. Then I would like to use `tradeseq` to find differentially expressed genes between wild type and mutant conditions.

I encountered the following error running evaluateK() with this code:

```
set.seed(6)
icMat <- evaluateK(counts = dcSubReg[['RNA']]@scale.data, sds = sds, k = 3:7, nGenes = 100,
                   verbose = FALSE, plot = TRUE)
```

Error traceback:
```
Error in .checks(pseudotime, cellWeights, U, counts, conditions) : promise already under evaluation: recursive default argument reference or earlier problems?
8. .checks(pseudotime, cellWeights, U, counts, conditions)
7. .fitGAM(counts = countSub, U = U, pseudotime = pseudotime, cellWeights = cellWeights, nknots = currK, verbose = verbose, sce = FALSE, weights = weightSub, offset = offset, aic = TRUE)
6. FUN(X[[i]], ...)
5. lapply(kList, function(currK) { gamAIC <- .fitGAM(counts = countSub, U = U, pseudotime = pseudotime, cellWeights = cellWeights, nknots = currK, verbose = verbose, sce = FALSE, weights = weightSub, offset = offset, aic = TRUE) ...
4. .evaluateK(counts = counts, k = k, U = U, pseudotime = pseudotime, cellWeights = cellWeights, plot = plot, nGenes = nGenes, weights = weights, offset = offset, verbose = verbose, control = control, sce = sce, ...)
3. .local(counts, ...)
2. evaluateK(counts = dcSubReg[["RNA"]]@scale.data, sds = sds, k = 3:7, nGenes = 100, verbose = FALSE, plot = TRUE)
1. evaluateK(counts = dcSubReg[["RNA"]]@scale.data, sds = sds, k = 3:7, nGenes = 100, verbose = FALSE, plot = TRUE)
```

I already restarted R and reinstalled `stringr` as a Google search suggested.

Update:
I also tried:
`counts <- as.matrix(dcSubReg[['RNA']]@counts)` or `counts <- as.matrix(dcSubReg[['RNA']]@scale.data)` 

same error.

Thanks for any advice!

**Comment by koenvandenberge** [comment]
Hi @liuyigh 

Thanks for your interest in using `tradeSeq`. 
The `conditions` branch is very recent and is still in development. We need more time to finish it completely. The `evaluateK` function has not been extended yet to handle multiple conditions and is therefore currently not expected to work. We can work on that but it may take some time.

**Comment by liuyigh** [comment]
Thanks for your reply on a Saturday! So I should arbitrarily choose a knot counts, say 6, and proceed?

**Comment by koenvandenberge** [comment]
It is hard to say, as the number of knots often depends on how large your dataset is, and how complex the gene expression patterns are along the lineage(s). In the datasets we have looked at, we have found a range of knots between 4 and 7 to work well for most.

**Comment by koenvandenberge** [comment]
Hi @liuyigh 

I pushed a commit to the `conditions` branch, and `evaluateK` works for me now, also when including conditions. Please re-install that branch and let me know if it works.
