### ISSUE TITLE
Identifying which are progenitor and which are differentiatied markers

### ISSUE THREAD

**Issue by satkins1** [statOmics/tradeSeq#55]
Hi

Tradeseq is a really interesting package and I have found it easy to get up and running using your tutorial - thank you.

I am interested in how to effectively use the output of some of the test that can be run. In particular the startVsEndTest. As the null hypothesis here is that expression is the same at the start and end of pseudotime it may be rejected because expression at the start exceeds the end (progenitor marker) or expression at the end exceeds the start (differentiated cells type marker). Ranking of the output by the Wald statistic simply orders results by the degree of difference but no the direction - is there a way to separate or annotate the results to identify which are higher to start with and which are lower? I presume there must be a way by accessing the coeffeicients?

Your input would be most helpful

Steve

**Comment by HectorRDB** [comment]
Hi @satkins1 ,
Thanks for your interest in `tradeSeq`. 

The latest version of the package, which can be installed from Github, now includes a logFC column in the result. With this, you will be able to sort genes into the two categories of interest. 

Best
