### ISSUE TITLE
Option to merge lineages?

### ISSUE THREAD

**Issue by cnk113** [statOmics/tradeSeq#61]
Hello,

I was wondering if you were planning on adding an option to merge lineages?
I'm using monocle3 and there are a lot of spurious lineages with end points that should be merged.
If you perhaps have a quick hack to merge them, it would be greatly appreciated.

**Comment by HectorRDB** [comment]
Hi,
Thanks for your interest in `tradeSeq`. Indeed, we have also found that monocle3 can tend to create spurious lineages. However, this question is outside the scope of `tradeSeq`. This tool is meant to be used downstream of trajectory inference, not replace it.

For a quick hack, you might be able to manually merge lineages though. Using the code from the [Monocle + tradeSeq](https://statomics.github.io/tradeSeq/articles/Monocle.html) vignette, you should be able to create a `pseudotime` and `cellWeights` matrix. Then, you can merge the columns corresponding to the merge you want to do and use it as input to the `fitGAM` function.

Note however that the code in the vignette works only for a trajectory with one root. If you have several roots, you should adjust the code accordingly.

Best
