### ISSUE TITLE
Change warning to message in .findKnots

### ISSUE THREAD

**Issue by HectorRDB** [statOmics/tradeSeq#63]
Many users are confused by the warning and end up trying ridiculously high values of k to get rid of it. To my mind, it should be a message since I don't think it has much impact on the downstream results. 
@koenvandenberge Any thoughts?

**Comment by HectorRDB** [comment]
Actually, I don't even think we should return a message. This made sense when we returned the full gam models but now we only return the coefficients as rowData, I dont' think users are likely to try and interpret individual coefficients. 
So I'd be in favor of removing it altogether

**Comment by koenvandenberge** [comment]
Good point, agreed! I just removed the warning in master and conditions branch.
