### ISSUE TITLE
fitGAM run times

### ISSUE THREAD

**Issue by rpolicastro** [statOmics/tradeSeq#64]
Hi all,

With the evaluateK questions out of the way, I have run into a new hurdle. After about 8 hours of running, fitGAM is still at 0% with no estimated time. There ~13K cells, ~30k features, and 10 lineages, This is with 6 cores and 128GB of memory using tradeSeq v1.3.13 from the 'conditions' branch. 

```
BPPARAM <- BiocParallel::bpparam()
BPPARAM$workers <- 6

nbm <- fitGAM(
  counts = as.matrix(x[["RNA"]]@counts), sds = y,
  conditions = factor(x$orig.ident), nknots = 6,
  parallel = TRUE, BPPARAM = BPPARAM, sce = TRUE
)
```

What would you suggest is the best way to reduce the runtime to something more manageable?

Thanks!

**Comment by HectorRDB** [comment]
Hi,
Thanks for opening a new issue. First a question. How many conditions do you have? 

Just to make sure it is indeed the fitting that is slow, could you try running `tradeSeq` on a couple of genes? You can use the `genes` argument. For example, just add `genes = 1:10` without parallelization and let me know.
Best

**Comment by rpolicastro** [comment]
Hector,

I have 2 conditions for this data. It looks like it took about 7 minutes to fit on 10 genes.

```
> nb_model <- map2(seurat_obj[1], trajectory[1], function(x, y) {
+   nbm <- fitGAM(
+     counts = as.matrix(x[["RNA"]]@counts), sds = y,
+     conditions = factor(x$orig.ident), nknots = 6,
+     genes = seq_len(10), sce = TRUE
+   )
+   return(nbm)
+ })
  |++++++++++++++++++++++++++++++++++++++++++++++++++| 100% elapsed=07m 30s
Warning message:
In .findKnots(nknots, pseudotime, wSamp) :
  Impossible to place a knot at all endpoints.Increase the number of knots to avoid this issue.
```

**Comment by HectorRDB** [comment]
Hi @rpolicastro 
Thanks for running this experiment. With two conditions, 10 lineages and 6 knots, this means you need to estimate 120 parameters per gene. We have not yet thoroughly benchmarked how much time the fitting would take in such settings but I would expect runtime is at least linear in the number of parameters.

Under the hood, `tradeSeq` is relying on the `mgcv` package and you can pass options to `mgcv` from `tradeSeq`. You could try digging into this, and I will look on my end as well.

As an aside, 30k features is probably way too much to try. I would look into filtering the dataset more aggressively. In my experience, anything above 10k feature does not add more information, and the top 1-2k features usually contain most of the signal.

**Comment by koenvandenberge** [comment]
Hi @rpolicastro 

Thank you for making this issue, and sorry to hear that you're experiencing these long runtimes. 
Fitting 120 parameters for each gene is not an easy feat, especially given how correlated the predictors are, given the multiple conditions. However, I do think that you may want to look into optimizing your code for these long runtimes.

 - The `as.matrix` code you have in your loop typically takes a long time. I don't know enough about the internals of `map2`, but you may want to do this outside of the loop, and provide the matrix as input.
 - Do you really need the `map2` function? Why not simply do 
```
counts <- seurat_obj[["RNA"]]@counts
cond <- factor(seurat_obj$orig.ident)
nbm <- fitGAM(
     counts = counts, sds = trajectory[1],
     conditions =cond, nknots = 6,
     genes = seq_len(10), sce = TRUE
   )
```
 - Finally, the parallelization may unfortunately get stuck sometimes. There is an [ongoing discussion](https://github.com/drisso/zinbwave/issues/38) on how this can be resolved, and we will be working on also updating `tradeSeq` to accommodate that. You may want to look into simply trying again, for now.

**Comment by rpolicastro** [comment]
Hi,

The map2 function is because I have a list of 2 experiments I'm processing at the same time. For the sake of troubleshooting though I'm just running one of them for the time being.

I wasn't aware that I could pass the sparse matrix from Seurat directly into fitGAM, in which case I can just remove the as.matrix function. It usually takes a few minutes for that to run so it will save a bit of time.

Ultimately it seems the number of parameters that it needs to fit per gene is the biggest problem. I might go ahead and just fit on 2k genes, and pick just a few of the best candidate lineages. Once I get a chance to try this I'll report back for posterity.

Thanks!

**Comment by HectorRDB** [comment]
Closing after inactivity

**Comment by ATpoint** [comment]
Hello, just wanted to ask whether by now you have maybe some estimates on runtime.
I am running evaluateK on 15.000 cells which consist of two treatment groups and have two lineages.
Running on a HPC with 16 BPPARAM workers and a multithreaded BLAS library...and the progress bar is sitting at 0% for several minutes now. Maybe some crude estimate of anticipated runtime?

```
ek <- evaluateK(counts = assay(sce[keep,], "counts"),
                k = 3:10,
                sds = crv,
                condition = factor(sce[keep,]$genotype),
                offset = log(Matrix::colSums(assay(sce[keep,], "counts")) * sce[keep,]$sizeFactor), # sizeFactors from scran
                parallel = TRUE,
                BPPARAM = MulticoreParam(workers = 16),
                verbose = TRUE)
```
The `keep` is just keeping genes that are expressed in at least 20% of cells in one of the six clusters that the dataset was clustered into, reducing it to ~8300 genes, probably not relevant in evaluateK but might makes sense for the DE testing later.

**Comment by s2hui** [comment]
Hello, I just started using the tradeSeq package and I had a question about selecting the number of genes for the parameter genes in fitGAM.  In this posting it says to use the top 1k features as "top 1-2k features usually contain most of the signal."  What is the recommended way to select the top 1-2K features?  Is this based on variable expression?  I have >30K genes in my counts matrix and was hoping that filtering this set of genes down will help fitGAM run faster.  I have run it on 100-200genes and it executes quickly (less than a min).  I have two lineages and am using 6 knots. Thanks alot for your help!

**Comment by liuweihanty** [comment]
Hi @HectorRDB , just a follow up on this issue because I encounter similar slow run time problem.. I have 6 cores and 128 GM memory, using the latest version of tradeSeq by running devtools::install_github("statOmics/tradeSeq"). I ran 10 genes, 5 lineages , 6 conditions and 6 knots, so that's 180 parameters per gene right? Even only 10 genes it still takes forever(3 hours only finish 10%). Is there anyway to optimize the algorithm for this function and speed it up? This is such a great tool and I imagine common applications of scRNA seq data could involve similar number of parameters on 2000-3000 genes on a desktop computer. Sorry if I missed any update. Thanks in advance!
