### ISSUE TITLE
"no positive cell weights" in fitGAM

### ISSUE THREAD

**Issue by yu-tong-wang** [statOmics/tradeSeq#67]
Hi there, 

I am doing downstream differential expression analysis using `tradeSeq` based on the `monocle` object [(vignette).](https://statomics.github.io/tradeSeq/articles/Monocle.html) However, while there is only one trajectory detected, some cell weights are zero. I suspect that those cells with zero weights are outliers along the trajectory. 

Using the cellWeights vector with zeros, `fitGAM` function returns error: 
> Error in .assignCells(cellWeights) : 
>   Some cells have no positive cell weights.

How should I solve such problem? I am currently manually assigning the zero weights to 0.01 so that `fitGAM` could run, but does such result make actual sense? Or should I delete the cells with zero weights instead? Thanks!

**Comment by HectorRDB** [comment]
Hi @yu-tong-wang 

I am unsure how you would get cells with no weights but the code used to assign weights to  cells downstream of monocle might not be 100% reliable.

Therefore, could you:
+ Plot the cells in reducedDim colored by whether the weights are zero or not to check if they are indeed outliers. If you could share that plot, it would be helpful
+ Check the pseudotime values of those cells. Pseudotime should be the distance along the tree structure so those cells might have weird pseudotime values.

Just to clarify, when you mean one trajectory, you mean one lineage (that is a trajectory with one branch?). If you only have one lineage, then you can just use a `cellWeight` vector of ones (all cell weights are normalized anyway). That would be my preferred solution, to avoid needlessly discarding the data

**Comment by yu-tong-wang** [comment]
Thank you @HectorRDB, and really sorry about the slow reply!! I was using the self-defined function in the [vignette](https://statomics.github.io/tradeSeq/articles/Monocle.html) to extract cells that map along the lineage from Monocle to get cell weights. I look into the data more closely, and a lot of cells with a zero cell weights are not expected outliers, and most of them have pseudotime smaller than 0.02. 

And thanks for the clarification - I meant one lineage by one trajectory. 

I think for any other users who have similar questions or issues, the weirdness in the derived cell weights could potentially be explained by how Monocle clustered cells and assigned pseudotime. Such clustering or pseudotime assignment might not be suitable for your dataset. (In my case, the cell clusters are not well-separated, but this is a case-by-case issue and may not generalize to others' issues). So I ended up with calculating pseudotime by cell-level metadata, rather than lineage identification based on gene expression data from Monocle, and a `cellWeight` vector of ones was used as @HectorRDB mentioned. It turns out that tradeSeq worked fine for me in this way.
