### ISSUE TITLE
fitGAM() error:  duplicate 'row.names' are not allowed

### ISSUE THREAD

**Issue by liuyigh** [statOmics/tradeSeq#69]
**Describe the bug**

I understand we can fit only a subset of genes and still use the whole dataset for normalization. The option is `genes = geneset` or `genes =1:2000`

If I use a vector to pass a subset of genes to fitGAM, I guess error at the end of fitting (100% progress) :
```
Error in `.rowNamesDF<-`(x, value = value) : 
  duplicate 'row.names' are not allowed
```
**To Reproduce**

If I subset the **counts** to include only genes of `geneset`, it is fine. The error shows up when I use the full 11094 gene counts but only fit a subset of genes using `genes = geneset` option.

I thought the cause may be due to genes like this: `1810037I17Rik` or `H2-K1`, however, if I do make.names(, unique = TRUE) to make row names as `X1810037I17Rik` `H2.K1`, error persists.

If I only tells it to fit two genes c('1810037I17Rik', '1110008P14Rik') it is actually fine.

What I ended up doing is subset the counts with geneset, subset the counts again with Negate(geneset), then rbind() the two to make a counts matrix with geneset genes on top, so I can use the `genes = 1:2000` option. It worked fine.

**Session info**
I installed the latest conditions branch.

**Comment by koenvandenberge** [comment]
Hi @liuyigh 

Thank you for letting us know, and apologies for the late response.
Are there duplicates in you `geneset` vector? e.g. is the result of `any(duplicated(geneset))` equal to `TRUE`?

**Comment by liuyigh** [comment]
No. `any(duplicated(geneset)`) equal to `FALSE`.

I actually did `make.names(geneset, unique = TRUE)`. Same error in both situations.

**Comment by koenvandenberge** [comment]
Thanks, this has now been fixed.
I will close the issue but feel free to let us know if you would still encounter any trouble.
