### ISSUE TITLE
How to change the dot size in function plotSmoothers()?

### ISSUE THREAD

**Issue by zhangjiaobxy** [statOmics/tradeSeq#7]
Hello,
I tried the `plotSmoothers()` function. I want to make the dot size smaller than the default dot size. But I can't find a parameter to tune the dot size. Usually, we use the `cex` parameter in `plot()` to control the dot size. Therefore, is it possible to add a parameter in the `plotSmoothers()` function to tune the dot size? Thanks.

**Comment by koenvandenberge** [comment]
Sure, the function has now been updated which allows you to set `cex`, `pch` and any other argument in the `plot()` function.

**Comment by zhangjiaobxy** [comment]
Thanks @koenvandenberge ! It works well!
