### ISSUE TITLE
Applying tradeSeq to time series datasets with no differentiation component

### ISSUE THREAD

**Issue by letaylor** [statOmics/tradeSeq#71]
Thank you for developing such a great package. 

Do you think the tradeSeq models could be used to analyse single cell time series datasets with no differentiation / pseudotime component?

For instance, a time course experiment with a low/high stimulation and expression measured at six subsequent time points (e.g., 0 hour [before stimulation], 2, 4, 8, 12 and 24 hours)?

If so, a few specific follow up questions:
1. The fitGAM function takes a matrix of pseudotimes and cell-level weights. In the above proposed experiment, I think one could use the actual measured time series points (0, 2, 4, 8, 12, and 24 hours) as the “pseudotime” measure (row is cell barcode, column is high/low perturbation, value is time point). However, it is unclear what one should use as cell-level weights since there is no pseudotime component.

2. It is not obvious if time should be modelled as time, time^2, or some other transformation. Any thoughts other than evaluate each transformation independently?

3. In the bioconductor vignettes, you note that for the patternTest function, "we use 100 points, equally distributed along pseudotime." Since we are analysing cells sampled at a few specific time points rather than over a continuous pseudotime space, does it still make sense to sample 100 points?

Thank you for your time and help!

**Comment by HectorRDB** [comment]
Hi @letaylor,
Generally speaking tradeSeq can indeed be extended to time series data (we have such an example in [our paper](https://www.nature.com/articles/s41467-020-14766-3) ) .

1/ tradeSeq can also handle trajectories with one lineage. In that case, the cellWeights arguments can just be a vector of ones with the same length as the number of cells (i.e all cells are assigned to that one lineage). 

2/ For time transformation, it is hard to advice. However, you might benefit from doing trajectory inference on your dataset, even though you have real time information. It is hard to give further advice without more biological insight into the process but it can easily be expected that, for a given time point, not all cells will have progressed as much in their response to the stimulus. Indeed, single-cell expression gives you cell level resolution, which is partly ignored when assigning the same time to all cells. 
After getting the pseudotime, you can also visualize how real time and pseudotime graph versus one another. 

3/ The patternTest uses by default 100 points along the fitted models, i.e it relies on the interpolation. So on principle, it does not really matter how many underlying time points were used. Moreover, we have found that the results are very stable to this value. However, you can easily modify those values with the `nPoints` arguments. 

Hope that helps,
Best

**Comment by HectorRDB** [comment]
Hi @letaylor,
Following a discussion with @koenvandenberge, I realized I partly misunderstood you problem. 

I will therefore modify my answer to the point 1. 

You have to conditions: high and low stimulus. Therefore, I would create a matrix of n rows (number of cells) by two. The first column would have ones if the cells come from the low stimulus (and zero otherwise), the second column would be the same but for the high stimulus.
Furthermore, since you expect that cells from `t=0` are similar (I imagine), I would advice, for some cells, to have values of 1 in both columns. This will therefore provide more solid estimates of starting values.

**Comment by letaylor** [comment]
Hi @HectorRDB, 

Thank you for your quick response! Yes @koenvandenberge chatted over email. All of this makes sense.

Just to provide a bit more context - our experiment is focused on adult tissue biopsies. At each time point we have sampled ~2-3k cells. The cells are fully differentiated and span 8 distinct cell types. Each time point and treatment (high/low) was performed with two replicates from the same individual biopsy. Time point 0 is **prior** to stimulation.

Just to clarify on point 1 for fitGAM:
* For cellWeights, you are suggesting to set this to ones (so an `n_cell` x `n_stimulus` [high or low] matrix of 1s). 
* I am not sure I follow your second comment. This is pertaining to the "pseudotimes" matrix, correct (which in this case is a matrix of time points)? You are right - within each cell type, cells should be very similar across conditions at `t=0` because this is prior to stimulation. Rather than setting `t=0` to `0`, you are suggesting set it to `1` to get accurate starting estimates. Is this correct?

Thanks again!

**Comment by HectorRDB** [comment]
Hi @letaylor 
Sorry, I think with the two part answers, it got a little confusing. Let me give a simple example of what I have in mind. 
Let's say we have this design matrix

| Cell 	| Condition 	| Time 	|
|:----:	|:---------:	|------	|
| 1    	| Low       	| 0    	|
| 2    	| High      	| 0    	|
| 3    	| Low       	| 1    	|
| 4    	| High      	| 1    	|
| 5    	| Low       	| 2    	|
| 6    	| High      	| 2    	|

Then, I would advice to use this as `CellWeights`
|:----:	|:---------:	|
| 1    	| 1       	|
| 1    	| 1      	|
| 1    	| 0       	|
| 0    	| 1      	|
| 1    	| 0       	|
| 0    	| 1      	|

All cells that have condition Low have a 1 in the first column and a zero in the second column, all cells that have condition High have a zero in the first column and a one in the second column.
Except for cells with time 0, where we have a 1 in both column.

Is that clearer?

**Comment by letaylor** [comment]
Hi @HectorRDB - very clear. Thank you for your help and for your contributions to such a useful method!

**Comment by tinggithub33** [comment]
Hello @HectorRDB 
I am working with @letaylor. it is clear on how to generate CellWeights.  in term of pseudotimes, I generated the time-point matrix replacing pseudotimes as:

lineage1 | lineage2
-- | --
0 | 0
0 | 0
1 | 1
1 | 1
2 | 2
2 | 2

do you think this is a right way to do?
your comments will be greatly appreciated.

**Comment by HectorRDB** [comment]
Hi @tinggithub33 ,
Yes this is indeed the way to do it. 
Best,

**Comment by tinggithub33** [comment]
Hello @HectorRDB,
Thank you for your reply!
when I ran 
icMat <- evaluateK(counts = as.matrix(assays(sce)$counts),
                   pseudotime = as.matrix(timePT),
                   cellWeights = as.matrix(weightM),
                   conditions = factor(cond),
                   nGenes = 300,
                   k = 3:7)
I got error message as:
Error in plot.window(xlim = xlim, ylim = ylim, log = log, yaxs = pars$yaxs) : 
  need finite 'ylim' values
Calls: evaluateK ... boxplot -> boxplot.default -> do.call -> bxp -> plot.window
In addition: Warning messages:
1: In any(counts) : coercing argument of type 'double' to logical
2: In any(counts) : coercing argument of type 'double' to logical
3: In any(counts) : coercing argument of type 'double' to logical
4: In any(counts) : coercing argument of type 'double' to logical
5: In any(counts) : coercing argument of type 'double' to logical
6: In min(x) : no non-missing arguments to min; returning Inf
7: In max(x) : no non-missing arguments to max; returning -Inf
any idea?
