### ISSUE TITLE
error fitGAM & associationTest

### ISSUE THREAD

**Issue by m21camby** [statOmics/tradeSeq#74]
Maybe overlap with previous questions, but I had error messages while running fitGAM and associationTest.

First, I ran below message and created error message:
`
sce <- fitGAM(counts = counts, pseudotime = slingPseudotime(crv, na = FALSE), cellWeights = cellWeights, sds = crv, nknots = 4, sce = TRUE, BPPARAM = BPPARAM, parallel = TRUE)
`
Error in .fitGAM(counts = counts, U = U, pseudotime = pseudotime, cellWeights = cellWeights,  : 
  object 'X' not found

I changed a bit and ran again and there were no error message
`
sce <- fitGAM(counts = counts, pseudotime = pseudotime, cellWeights = cellWeights, nknots = 4, verbose = FALSE, BPPARAM = BPPARAM, parallel = TRUE)
`

However, when i implemented associationTest, it created error message:
`
assoRes <- associationTest(sce, global = FALSE, lineages = FALSE)
` 
Error in .getModelReference(models) : All models errored

Why were these error messages created? Thanks in advance.

**Comment by koenvandenberge** [comment]
Hi @m21camby 

Could you please check if these errors persist when using the latest version of `tradeSeq` using `devtools::install_github("statOmics/tradeSeq")`, restarting R and trying again.

Given that you have a Slingshot object, the recommended fitting would be
`sce <- fitGAM(counts = counts, sds=crv, nknots = 4, sce = TRUE, BPPARAM = BPPARAM, parallel = TRUE)`
Please see our [manual](https://bioconductor.org/packages/release/bioc/vignettes/tradeSeq/inst/doc/fitGAM.html) for more details.

**Comment by m21camby** [comment]
Hi @koenvandenberge 

Thanks. After update to latest package, there were no error messages.
