### ISSUE TITLE
argument is not a matrix in fitGAM

### ISSUE THREAD

**Issue by woodylxf** [statOmics/tradeSeq#76]
Dear developers,
         I am encountering an issue that fitGAM returns error saying the matrix I use is not a matrix. When I run `as.matrix` separately, the matrix can be generated. So that seems somehow fitGAM doesn't recognize the matrix I use as a matrix. Do you have any suggestions?  I also attach the code and error below. Thanks a lot. 

Best,
Woody

------------------------
counts_Matrix = as.matrix(counts)
sce <- fitGAM (counts = counts_Matrix,
              sds = curves )

Error in t.default(do.call(cbind, betaAll)) : argument is not a matrix

**Comment by koenvandenberge** [comment]
Hi @woodylxf,

Thanks for your interest in `tradeSeq`. It may happen that `as.matrix` is not sufficient, in some cases.
What is the result if you run `is(counts_Matrix, "matrix")`?
Can you run other matrix operations, such as `head(rowSums(counts_Matrix))`?

**Comment by woodylxf** [comment]
Hi @koenvandenberge ,
     Thanks for the reply. I ran the codes you suggested and it seems there is something wrong with the package installation. Could you have a look and give some further suggestions? Thanks a lot! 
Best,
Woody

> is(counts_Matrix, "matrix")
[1] TRUE

> head(rowSums(counts_Matrix))
numeric(0)

> devtools::install_github("statOmics/tradeSeq")
Downloading GitHub repo statOmics/tradeSeq@HEAD
These packages have more recent versions available.
It is recommended to update all of them.
Which would you like to update?

1: All                           
2: CRAN packages only            
3: None                          
4: ps     (1.3.4 -> 1.4.0) [CRAN]
5: igraph (1.2.5 -> 1.2.6) [CRAN]

Enter one or more numbers, or an empty line to skip updates:1
ps     (1.3.4 -> 1.4.0) [CRAN]
igraph (1.2.5 -> 1.2.6) [CRAN]
Skipping 21 packages ahead of CRAN: BiocGenerics, RBGL, graph, Biobase, zlibbioc, XVector, GenomeInfoDbData, GenomeInfoDb, IRanges, DelayedArray, GenomicRanges, S4Vectors, SummarizedExperiment, biocViews, limma, HSMMSingleCell, SingleCellExperiment, monocle, BiocParallel, slingshot, edgeR
Installing 2 packages: ps, igraph

  There are binary versions available but the source versions are later:
       binary source needs_compilation
ps      1.3.4  1.4.0              TRUE
igraph  1.2.5  1.2.6              TRUE

Do you want to install from sources the packages which need compilation? (Yes/no/cancel) Yes
installing the source packages ‘ps’, ‘igraph’

trying URL 'https://cran.rstudio.com/src/contrib/ps_1.4.0.tar.gz'
Content type 'application/x-gzip' length 110708 bytes (108 KB)
==================================================
downloaded 108 KB

trying URL 'https://cran.rstudio.com/src/contrib/igraph_1.2.6.tar.gz'
Content type 'application/x-gzip' length 2715500 bytes (2.6 MB)
==================================================
downloaded 2.6 MB

* installing *source* package ‘ps’ ...
** package ‘ps’ successfully unpacked and MD5 sums checked
** using staged installation
** libs
clang -mmacosx-version-min=10.13 -Wall -g -O2  -Wall px.c -o px
px.c:6:10: fatal error: 'unistd.h' file not found
#include <unistd.h>
         ^~~~~~~~~~
1 error generated.
make: *** [Makevars:11: px] Error 1
ERROR: compilation failed for package ‘ps’
* removing ‘/Library/Frameworks/R.framework/Versions/4.0/Resources/library/ps’
* restoring previous ‘/Library/Frameworks/R.framework/Versions/4.0/Resources/library/ps’
Error: Failed to install 'tradeSeq' from GitHub:
  (converted from warning) installation of package ‘ps’ had non-zero exit status

**Comment by HectorRDB** [comment]
Hi @woodylxf,
The latest error seems to be related to your tentative to update the `ps` package. You can run this command again but answer 3 (i.e.e None) when asked which packages you want to update.

Related your initial question, the error seems to be when constructing the beta matrix coefficient.

Could you share a picture of what the trajectory (the curves object) looks like? Especially the number of lineages? 
As well as the command you used to construct it? Thanks

**Comment by woodylxf** [comment]
Hi @HectorRDB ,
     Thanks for the reply. I chose "3" when installing the package, and it seems the installation is successful. By running fitGAM again, however, the matrix is still not recognized. 
     Here are the codes and a picture that I generated for the trajectory. The number of lineages is 15: 

#Run default Slingshot
set.seed(1)
lineages <- getLineages(data = dimred,
                        clusterLabels = clustering,
                        start.clus = "8")

lineages

#Plot the lineages
par(mfrow=c(1,2))
plot(dimred[,1:2], col = pal[clustering],  cex=.5,pch = 16)
for(i in levels(clustering)){ 
  text( mean(dimred[clustering==i,1]),
        mean(dimred[clustering==i,2]), labels = i,font = 2) }
plot(dimred, col = pal[clustering],  pch = 16)
lines(lineages, lwd = 3, col = 'black')

curves <- getCurves(lineages, thresh = 0.01, stretch = 0.8, allow.breaks = FALSE, shrink = 0.99)
curves

plot(dimred, col = pal[clustering], asp = 1, pch = 16)
lines(curves, lwd = 3, col = 'black')
![000005](https://user-images.githubusercontent.com/49754667/95580637-f41dba00-0a37-11eb-9baf-5d5c91f649a7.png)

**Comment by HectorRDB** [comment]
Hi @woodylxf,
I am unsure where the error comes from but as an FYI, we have never run `tradeSeq` with that many lineages. Without biological information, i cannot know if those are meaningful, but I am highly skeptical of some of the lineages in the plot above (I would point you to the lineage that does a full 180 on the right of the gold cluster). 
Trajectory inference (i.e. running slingshot) should not be a fully unsupervised task. In particular, I would recommend using a clustering that represent a lower resolution (i.e. less clusters). 

Would you also mind sharing the data with us so we can further investigate this bug? 
Thanks

**Comment by woodylxf** [comment]
Hi @HectorRDB ,
      Thanks a lot for your suggestions. I think I found the issue - my data used for Slingshot has previously been integrated by CCA, but somehow I used the assay RNA to create the matrix, so that is recognized as "empty". So I think there is nothing wrong with trade seq. The other issue I had was running Slingshot took lots of time, but your answer has provided some hints - I can reduce the number of clusters and specify the ending of each lineage. That should work better. Thanks a lot for the suggestions! 
       Regarding the data, I'd like to share for further tradeSeq development, but it is currently unpublished with sensitive patient data. Hopefully, we can finish the trajectory analysis soon with Slingshot and I'd be happy to keep in touch for further access and biology inputs. 

Best regards,
Woody

**Comment by HectorRDB** [comment]
Happy to be able to help. I understand the difficulties with sharing the data. 
Let me know if anything else pops up.
Best

**Comment by bapoorva** [comment]
Hi,

I have the exact same issue. I updated the package. So no problem there. My data is a single sample with only 3 lineages. I selected only highly variable genes, so it is not too large either. The default assay is RNA and there are no other assays present. Yet, i'm getting the same error with the count matrix.

```
BPPARAM <- BiocParallel::bpparam()
BPPARAM$workers <- 20
crv= scrna@misc$sds$data
pseudotime <- slingPseudotime(crv, na=FALSE)
cellWeights <- slingCurveWeights(crv)

sce <- fitGAM(counts =counts_var, pseudotime = pseudotime, cellWeights = cellWeights,nknots = 8, verbose = FALSE,parallel=TRUE, BPPARAM = BPPARAM)
Some library sizes are zero. Offsetting these to 1.

Error in t.default(do.call(cbind, betaAll)) : argument is not a matrix
> class(counts_var)
[1] "matrix" "array" 
```

crv is an object of type PseudotimeOrdering that i got after running slingshot.
