### ISSUE TITLE
How to use fitGAM with more than one lineages? 

### ISSUE THREAD

**Issue by peaceisking** [statOmics/tradeSeq#80]
After finishing slingshot ,and get two lineages, to  get the dynamic genes in two lineage seperately  ,I use fitGAM as below:

`sds2 <- fitGAM(counts = as.matrix(assays(sds1)$counts),
               sds = SlingshotDataSet(sds1),
               parallel = TRUE, BPPARAM = BPPARAM)`

and after that ,I also do
 `ATres <- associationTest(sds2)`

but after that ,I realized the output seems does not show the pvalue of two linages seperately,just like this:

> head(ATres)
           waldStat df       pvalue
ISG15     62.989284  9 3.544863e-10
AURKAIP1   4.080825  9 9.060126e-01
MRPL20    36.940580  9 2.696865e-05
SSU72      9.070291  9 4.308112e-01
GNB1     109.566442  9 0.000000e+00
TNFRSF14  58.637232  9 2.452204e-09

so what should I do ? run the fitGAM seperately for two lineages?
Thankx

**Comment by koenvandenberge** [comment]
You can get the lineage-specific results by setting `lineages = TRUE` in the `associationTest`. Check the help file for more details on how to use the `associationTest`.
