### ISSUE TITLE
fitGAM encounters error when using a sparse matrix with conditions

### ISSUE THREAD

**Issue by asenabouth** [statOmics/tradeSeq#82]
Hello,

I have encountered another issue with fitGAM - this time with using a sparse count matrix with conditions for fitGAM. 

Reproducible example

```R
library(tradeSeq)
library(RColorBrewer)
library(SingleCellExperiment)
library(slingshot)
library(Matrix)
library(BiocParallel)

BPPARAM=MulticoreParam(workers=4)

# For reproducibility
RNGversion("3.5.0")
palette(brewer.pal(8, "Dark2"))
data(countMatrix, package = "tradeSeq")
counts <- as.matrix(countMatrix)
rm(countMatrix)
data(crv, package = "tradeSeq")
data(celltype, package = "tradeSeq")

# Generate random condition list
barcodes <- colnames(counts)
condition_list <- c("POS", "NEG")
condition_vec <- sample(condition_list, length(barcodes), replace = TRUE)
condition_vec <- factor(condition_vec, levels = condition_list)

# Run fitGAM
set.seed(13)

sparse_mat <- Matrix::Matrix(as.matrix(counts), sparse = TRUE)
tradeseq_obj <- fitGAM(counts = sparse_mat, sds = crv, conditions = condition_vec, 
                                         parallel = TRUE, nknots = 4, verbose = TRUE, BPPARAM=BPPARAM)
``` 

It produces this error message:

```R 
> tradeseq_obj <- fitGAM(counts = sparse_mat, sds = crv, conditions = condition_vec, 
+                                          parallel = TRUE, nknots = 4, verbose = TRUE, BPPARAM=BPPARAM)
Error in .local(counts, ...) : 
  unused argument (conditions = c(1, 1, 1, 1, 1, 2, 2, 2, 1, 1, 2, 1, 1, 2, 2, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 1, 2, 1, 1, 2, 2, 2, 1, 1, 2, 2, 2, 2, 2, 1, 2, 2, 1, 2, 1, 2, 1, 1, 1, 2, 1, 1, 1, 2, 1, 1, 2, 2, 1, 1, 2, 1, 1, 1, 1, 1, 2, 2, 1, 2, 2, 2, 2, 2, 1, 1, 2, 1, 2, 1, 2, 1, 1, 1, 1, 2, 2, 2, 1, 2, 2, 2, 1, 2, 1, 2, 1, 1, 1, 1, 1, 1, 1, 2, 2, 1, 2, 2, 2, 2, 2, 1, 2, 1, 2, 2, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 1, 1, 1, 2, 1, 2, 1, 2, 2, 1, 1, 2, 2, 2, 2, 1, 1, 1, 1, 2, 1, 2, 2, 1, 2, 2, 2, 2, 1, 1, 2, 
2, 1, 1, 2, 2, 1, 1, 2, 2, 1, 1, 1, 2, 1, 1, 2, 1, 2, 2, 1, 2, 1, 1, 2, 1, 1, 2, 1, 1, 1, 1, 1, 2, 1, 1, 1, 2, 2, 2, 1, 2, 2, 2, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 2, 1, 2, 1, 2, 2, 1, 2, 1, 2, 2, 2, 2, 2, 2, 1, 2, 1, 2, 2, 2, 2, 1, 1, 2, 1, 1, 2, 1, 2, 1, 1, 2, 1, 2, 1, 1, 2, 1, 1, 2, 2, 2, 2, 2, 2, 1, 2, 1, 2, 1, 2, 2, 1, 1, 2, 1, 2, 1, 2, 2, 2, 1, 2, 1, 1, 2, 2, 1, 1, 1, 2, 2, 2, 2, 1, 2, 1, 1, 2, 2, 1, 2, 2, 1, 2, 1, 2, 1, 2, 2, 2, 1, 2, 2, 1, 1, 1, 1, 1, 1, 2, 1, 2, 2, 2, 
```

It works fine if the matrix is dense. 

I really need the function to run with sparse matrices however, as I am trying to analyse a dataset with ~250K cells. I have reduced the dimensions of the matrix by only using the top 2000 most variable genes, but this matrix is still too large to convert into a dense matrix.

Thanks!

**Comment by HectorRDB** [comment]
Hi @asenabouth,
I will look into this problem. However, note that under the hood, `tradeSeq` is converting the sparse matrix as a dense matrix for now so it won't solve your issue...
I will look into improving the code but in the meantime, I can unfortunately only suggest downsampling when using `tradeSeq`

**Comment by asenabouth** [comment]
Hi @HectorRDB ,

I understand. Should I just subsample the same number of cells from each subpopulation, or should I just randomly select cells from the entire dataset?

Thanks,
Anne

**Comment by HectorRDB** [comment]
With the latest version of tradeSeq that you can get from Github 
```
devtools::install_github("statOmics/tradeSeq")
```

The bug should be fixed. Thanks for noticing this.

For downsampling, I would recommend downsampling by the same fraction, but to control by condition. For exemple, if you have two conditions, you can sample 50% of the cells for each condition, instead of sampling 50% of the overall dataset. This will ensure the condition balance is preserved. If you have cell type information, you can also sample in each condition x cell type group. 

The only caveat is if you only have  a few cells from one type (whether it is one condition or one lineage). Then, I would downsample to a fix number per type, or try a hybrid approach. It is hard to advice further without knowing more about the specific design of your experiment but I hope those general principles help a little

**Comment by asenabouth** [comment]
I just tested it  on the example dataset - it now works. Thank you, especially for the advice re: downsampling!
