### ISSUE TITLE
TradeSeq on gene expression microarray data

### ISSUE THREAD

**Issue by LetiLosa** [statOmics/tradeSeq#83]
Hi,
I'm really interested in _tradeSeq_ for my thesis project.
I'm working with gene expression microarray data from different dataset (integrated and batch-corrected by using ComBat).
Can I adapt fitGAM to this kind of data?
I'm pretty new to bioinformatics, so any suggestion will be appreciated!

Thanks

**Comment by koenvandenberge** [comment]
Hi @LetiLosa 

Thanks for your interest in using `tradeSeq`. Assuming your microarray data has been normalized (e.g. using RMA) and log(2)-transformed as would be a typical workflow, it should indeed be possible to use `tradeSeq` and fit using `fitGAM`, although we have never tried this yet.

In `fitGAM` I would advise to

- Set `offset=0` since there is no such thing as sequencing depth for microarrays.
- Set `family="gaussian"` to assume a Gaussian model.

Let us know if this works for you. If it works well, it may be an interesting application to add to our vignettes.

**Comment by LetiLosa** [comment]
Thank you @koenvandenberge, your answer was so clear!

Yes, my data are normalized and log2 transformed, so of course your suggestions seem to be great.
However when I run `evaluateK`, I find weird plots.

`icMat <- evaluateK(counts = data_com, k = 3:20, nGenes = 500, pseudotime = pseudotimes, cellWeights = cellWeights, offset=offset, verbose = T, family="gaussian")`

![image](https://user-images.githubusercontent.com/73915744/98096158-ac9a1a80-1e8b-11eb-96b2-d85c4b5e7dec.png)


The problem is that changing `set.seed(...)`, plots change too, so I can't choose the proper value for `knots`.
Is there a problem of fitting or something else?

Thanks!

**Comment by koenvandenberge** [comment]
Hi @LetiLosa 

It seems that the AIC plots as a function of `k` are pretty random. This is further confirmed by the rightmost panel where there are very little genes plotted; only genes are discovered with a change in AIC of at least 2, so it looks like changing `k` has no big impact on the fit, based on these plots. 

It is hard to figure out if that is meaningful or not without knowing more about the data you're analyzing. How many time points do you have? How many replicates in a time point? Do the fits look very different when changing `k`?

**Comment by LetiLosa** [comment]
Hi @koenvandenberge 

the time points, that I've used in _tradeSeq_, are obtained from _Slingshot_ analysis.

`pseudotimes <- slingPseudotime(sim, na=FALSE)`
where `sim` is the slingshot output.

In particular, I've 2 lineages, so for each sample there are two different pseudotime values.
These plots represent the expression of a random gene as function of pseudotimes for lineage1 and lineage2:

![image](https://user-images.githubusercontent.com/73915744/98252401-2c9eae00-1f7a-11eb-981f-2fbc99dce292.png)
![image](https://user-images.githubusercontent.com/73915744/98252327-1395fd00-1f7a-11eb-90a9-c9edc355d7d2.png)

For your last question, I've applied `fitGAM` changing the number of knots:
> `nknots=5`

![image](https://user-images.githubusercontent.com/73915744/98252597-6b346880-1f7a-11eb-815d-5970965f227a.png)

> `nknots=10`

![image](https://user-images.githubusercontent.com/73915744/98252713-88693700-1f7a-11eb-9726-faee7fb0d96c.png)

I hope that this information will help!
Many thanks!

**Comment by koenvandenberge** [comment]
Hi @LetiLosa 

Upon closer inspection of our code, it turned out that the `family` argument in `evaluateK` was not properly implemented, as we've never had to use it.
Could you please re-install `tradeSeq` using `devtools::install_github("statOmics/tradeSeq")`, restart R and try again to see if your plots are looking better?

**Comment by LetiLosa** [comment]
Unfortunately, after re-intalling `tradeSeq`, plots aren't looking better:

`icMat <- evaluateK(counts = data_com, k = 3:20, nGenes = 500, pseudotime = pseudotimes, cellWeights = cellWeights, offset=offset, verbose = T, family="gaussian")`

![image](https://user-images.githubusercontent.com/73915744/98276936-04717800-1f97-11eb-9d9a-532ff2946686.png)

This is the distribution of my data:

`hist(data_com)`
where `data_com` is a matrix of 22011(features)x321(samples)

![image](https://user-images.githubusercontent.com/73915744/98278142-79917d00-1f98-11eb-8ceb-8770f3488afd.png)


`sessionInfo()`

```
R version 4.0.2 (2020-06-22)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 18363)

... 

other attached packages:
 [1] ggpubr_0.4.0        ggplot2_3.3.2       slingshot_1.6.1     princurve_2.1.5    
 [5] sva_3.36.0          BiocParallel_1.22.0 genefilter_1.70.0   mgcv_1.8-31        
 [9] nlme_3.1-148        tradeSeq_1.3.23    

...     
```

**Comment by koenvandenberge** [comment]
Thanks @LetiLosa 

It does seem like the deviations in AIC are **very** small in your case, so I'm not sure if we should focus on interpreting the plots; the deviations look pretty random to me. Your expression patterns also seem to be fairly simple, so `k=3` or `k=4` doesn't seem unreasonable to me.

If you can share (a subset of) your data, I'm happy to take a deeper dive to make sure if the problem isn't with our `evaluateK` function.

**Comment by LetiLosa** [comment]
That would be great! I will send you an e-mail.

However, now everything is clearer to me... so really thank you!

**Comment by koenvandenberge** [comment]
Hi @LetiLosa 

I just took a look and noticed that the `family` argument wasn't properly propagated when not using a `SingleCellExperiment` object, as in your case.
If you re-install again, the plots should look as expected. I attach a plot I'm getting using the following code below. Based on this, I'd suggest using 5 knots.

```
pt <- as.matrix(read.table("~/Downloads/Pseudotime.txt"))
cw <- as.matrix(read.table("~/Downloads/CellWeights.txt"))
data <- as.matrix(read.table("~/Downloads/Data.txt"))
offset <- rep(0, ncol(data))
library(tradeSeq)
set.seed(4)
icMat <- evaluateK(counts = data, 
                   k = 3:8, 
                   nGenes = 500, 
                   pseudotime = pt, 
                   cellWeights = cw, 
                   offset=offset, 
                   verbose = T, 
                   family="gaussian")
```

![image](https://user-images.githubusercontent.com/10134844/99193957-2609f680-2731-11eb-8b69-12196fdc6469.png)

**Comment by LetiLosa** [comment]
Thank you @koenvandenberge!

I've tried on my computer after reinstalling `tradeSeq` and plots are the same.
I was just wondering why in the middle right panel values are increasing. Is it ok?

**Comment by koenvandenberge** [comment]
Great. 
Yes, that's ok. The relative AIC that's plotted there is the average relative AIC for each gene with respect to 3 knots, but we find that the average is often driven by a few big outliers, so we're even considering remove that panel in an upcoming version of `tradeSeq`.
