### ISSUE TITLE
Heatmap after tradeSeq

### ISSUE THREAD

**Issue by zhanglab2008** [statOmics/tradeSeq#84]
Hi team, thanks for developing this tool. Could you give some example codes for reproducing the Figure 6C (a heat map of the gene dynamics across pseudo time) from your Nature Communications paper? Thanks very much!!

**Comment by HectorRDB** [comment]
The code to reproduce the paper can be found in this repo: https://github.com/statOmics/tradeSeqPaper

To produce the heatmap, I would refer you to our recent bioconctor workshop, here: https://kstreet13.github.io/bioc2020trajectories/articles/workshopTrajectories.html#visualization-of-de-genes

**Comment by zhanglab2008** [comment]
Thanks, that's helpful!
