### ISSUE TITLE
Rename lineages

### ISSUE THREAD

**Issue by kristiangu** [statOmics/tradeSeq#89]
Thanks for the beautiful tool. It has been working pretty well from my monocle 3 data, and thanks to your vignettes it has been very easy to apply.
I have a question in regard whether it is possible to rename the lineages on the sce output from fitgam. I couldn't find a way but maybe I missed something.

Thanks!

**Comment by koenvandenberge** [comment]
Hi @kristiangu 

Thanks. There isn't a way to rename the lineages right now. 
If you'd like to name them for, for example plotting, you can override the default `ggplot2` labels, e.g. for three lineages

```
plotSmoothers(sce, counts, gene=rownames(sce)[1]) +
  scale_color_viridis_d(labels = c("lineage1", "lineage2", "lineage3")) 
```
