### ISSUE TITLE
installation problems

### ISSUE THREAD

**Issue by ltosti** [statOmics/tradeSeq#9]
Hi there,

When I try to install tradeSeq, I get the following error:

```Error in parse_repo_spec(repo) : Invalid git repo specification: 'statOmics/tradeSeq/'```

and it is not a problem of proxy. Any idea?

Thank you!

**Comment by koenvandenberge** [comment]
Hi, you have to remove the slash `/` in the code, i.e. instead of `devtools::install_github("statOmics/tradeSeq/")`  you should use `devtools::install_github("statOmics/tradeSeq")`.

Let me know if it works.

**Comment by ltosti** [comment]
Yes, it works! Thank you!

**Comment by koenvandenberge** [comment]
Great, hope you enjoy using the package and let us know if you encounter any further issues.
