### ISSUE TITLE
Error: package or namespace load failed for ‘tradeSeq’

### ISSUE THREAD

**Issue by yu-tong-wang** [statOmics/tradeSeq#90]
`tradeSeq` cannot be loaded after upgrading my OS system to Big Sur. It used to work just fine before my upgrading. I tried to uninstall and reinstall the package, and specify the library location as the error messages specified. Nothing worked. Do you know what the problem might be, and could you help out? Thanks!

> library(tradeSeq)
Error: package or namespace load failed for ‘tradeSeq’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/Library/Frameworks/R.framework/Versions/4.0/Resources/library/sf/libs/sf.so':
  dlopen(/Library/Frameworks/R.framework/Versions/4.0/Resources/library/sf/libs/sf.so, 6): Library not loaded: /usr/lib/libpq.5.dylib
  Referenced from: /Library/Frameworks/R.framework/Versions/4.0/Resources/library/sf/libs/sf.so
  Reason: image not found

![image](https://user-images.githubusercontent.com/42732738/100281939-a691d980-2f1f-11eb-89d6-a051ef7f7cae.png)
![image](https://user-images.githubusercontent.com/42732738/100281970-adb8e780-2f1f-11eb-8be8-dae66a51a250.png)

Update: there is a similar issue with a package in GitHub: https://github.com/r-spatial/sf/issues/1536. I am not very familiar with Bioconductor package installation - do you think if there is any similar way to solve the issue? I tried `BiocManager::install("tradeSeq", configure.args = "--with-proj-lib=/usr/local/lib/")`, yet it did not solve the problem.

**Comment by HectorRDB** [comment]
Hi Yutong,
I think this is probably more an issue with Big Sur than with tradeSeq unfortunatly.
One thing I would recommand is trying outside R studio, this sometimes helps when dealing with MacOs updates. Otherwise, I fear your guesses are as good as mine. If I update soon, I'll let you know but I'm not really planning to do it in the near future.

**Comment by yu-tong-wang** [comment]
Thanks for the speedy reply, Hector. Neither terminal nor the R console work for me unfortunately ... I think Big Sur changed the system directory and thus I no longer have this: "/usr/lib/libpq.5.dylib" as the error message pointed out. 
I know the hope is tiny, but if either you or @koenvandenberge figures out the potential solution like another similar github issue I attached, please let me know. Keep my fingers crossed ...

**Comment by yu-tong-wang** [comment]
Problem solved! Jeroen Omms mentioned that https://twitter.com/opencpu/status/1331752975547715584?s=20
> The issue with gdal was solved a few days ago. Just reinstall the sf and rgdal packages from CRAN: install.packages(c("sf", "rgdal"))
I can load `tradeSeq` now after a quick installation of `BiocGenerics`.
