### ISSUE TITLE
Query: associationTest and conditionTest output: waldStat

### ISSUE THREAD

**Issue by kmshort** [statOmics/tradeSeq#91]
Hi,

I would like to use the goana library to determine what GO and KEGG pathways are associated with DEs along a slingshot lineage using tradeSeq. So to apply the output of associationTest and conditionTest, I would like to understand what the waldStat output is. Is it something akin to a magnitude of a change, such that higher waldStat numbers represent a greater change? Such that it is akin to a  log2fc, which would typically be used for regular differential gene expression tests between 2 groups?

thanks,

**Comment by koenvandenberge** [comment]
You can think about the Wald test statistic as a squared z-test statistic, so it is the relevant log fold change divided by its standard error, squared. It therefore incorporates the magnitude of change, but also how uncertain we are about that magnitude. If you would like to rank genes for downstream analysis, it would be a good idea to use the Wald test statistic to do this; high values would correspond to genes with a lot of signal. More details can be found in our [paper](https://www.nature.com/articles/s41467-020-14766-3).

**Comment by kmshort** [comment]
Fantastic, that's what I took it to mean. Thanks Koen.
