### ISSUE TITLE
error plotSmoothers and plotGeneCount

### ISSUE THREAD

**Issue by EAC-T** [statOmics/tradeSeq#92]
Hi everyone,
I have a Seurat object and I'm following the vignette, I used slingshot and then Treadeseq but for some reason I'm having troubles getting any plot. Here is the code, I hope someone can help:

sce<- as.SingleCellExperiment(seurat)
### running slingshot
sce <- slingshot(sce, clusterLabels = 'seurat_clusters', reducedDim = 'UMAP', start.clus=2, stretch=0)
##creating slingshotdataset
slingsce<-SlingshotDataSet(sce)
## GETTING PARAMETERS from slingsce
pseudotimeED <- slingPseudotime(slingsce, na = FALSE)
cellWeightsED <- slingCurveWeights(slingsce)
## Getting counts from sce object
countsED<-sce@assays@data@listData$counts
##FITGAM
sce <- fitGAM(counts = countsED, pseudotime = pseudotimeED, cellWeights = cellWeightsED,
              nknots = 6, verbose = T)
table(rowData(sce)$tradeSeq$converged) ### FALSE 994, TRUE 14521, not all genes converged.
## association test
assoRes <- associationTest(sce)
head(assoRes)
##Discovering progenitor marker genes
startRes <- startVsEndTest(sce)
#visualization
oStart <- order(startRes$waldStat, decreasing = TRUE)
sigGeneStart <- names(sce)[oStart[3]]
plotSmoothers(sce, counts, gene = sigGeneStart) 

I get an error:
Error in counts[gene, ] : object of type 'closure' is not subsettable.

I'm wondering if I did anything wrong in my code, the way I transformed seurat to sce then to slingsce and did the fitgam.
I would really appreciate any help thank you.

**Comment by koenvandenberge** [comment]
Hi @EAC-T 

Is it possibe you should be using `countsED` instead of `counts` in the `plotSmoothers` function?

**Comment by EAC-T** [comment]
YESSS omg thank you a lot!
