### ISSUE TITLE
Discover specific genes within a lineage

### ISSUE THREAD

**Issue by woodylxf** [statOmics/tradeSeq#96]
Hi,
Thanks a lot for tradeSeq, a very useful package!
I am new here so the questions could be naive: I am trying to analyze the differential genes along the trajectory. Ideally, I would like to see how specific genes are highly expressed in different "regions" along the same lineage, visualize by `plotGeneCount() `for example. What I am doing now is to calculate the most differential expressed genes by `customRes <- startVsEndTest(sce, pseudotimeValues = c(0.1, 0.8))`, filter them by p-value and plot them one by one using `plotGeneCount()`. In this way, I can only hope they end up in different places of the lineage, and manually pick the interesting ones to suggest they are highly associated with different phases during the cell differentiation. So I am wondering if there is some unbiased / more convenient way to get this result. I got some suggestions from another page that I should use `associationTest` instead, as I want to see more than just the specific genes at the start and end of the lineage. However, after `assoRes <- associationTest(sce)`, I don't know what to do further to generate the plot I'd like to have, especially I have 9 lineages in the same dataset, and I dont know which lineage the genes calculated by `assoRes <- associationTest(sce)` belong to... 

Another question is when using plotSmoothers(), I find it a bit hard to distinguish some lineages by eye due to similar curve color. Is pointCol the one to change? What shall I replace "NULL" with? I also checked the issue [#39 ](https://github.com/statOmics/tradeSeq/issues/39), but using scale_color_manual() only changes the color of points, not curves... Any suggestions to change the color of the curves too? 

Thanks a lot for your time in advance. I look forward to your reply.

Best,
Woody

**Comment by koenvandenberge** [comment]
Hi @woodylxf 

I should start by saying that 9 lineages is a lot, and we have not worked yet with trajectories of that size.

Note that the `associationTest` has an argument `lineages` which, if you set `lineages=TRUE` will perform the `associationTest` for each lineage separately. By default (`lineages=FALSE`) it does so for all lineages simultaneously in a global test fashion.
Once you have these results, based on what you write, I think a better and unbiased way of your approach would be to plot the fitted values (e.g. in a heatmap) and cluster the genes according to their estimated expression profile. You could do this for one lineage or for multiple lineages. We do this for one lineage in our workshop, see the first chunk of code  [here](https://kstreet13.github.io/bioc2020trajectories/articles/workshopTrajectories.html#visualization-of-de-genes).
You can then use the hierarchical clustering to make clusters of genes that will be behaving similarly, see the code below the heatmap.

Regarding `plotSmoothers`, it is mentioned in the documentation that `pointCol` will change the colour of the data points. Note that `plotSmoothers` returns a `ggplot2` object, which you can post-creation adjust to change anything you like, such as the colour of the lineages. @HectorRDB, do you have a recommendation on how to best change the color of the lineages following `plotSmoothers`?

**Comment by HectorRDB** [comment]
Sorry, It's very challenging to design a function where the points and the curves can be in different colors scales, and have those scales by user-defined so there is really no plan short term to make this.
Right now, the user can choose the colors of the points. The color of the lines is fixed, using the viridis scale. I may be possible to change it by tweaking the final ggplot object manually but this is far far beyond my knowledge. 

To pile up on what Koen said, I think this mainly stems from having 9 lineages, which indeed seems like a lot.

**Comment by HectorRDB** [comment]
Well I ended up having the same issue (3 lineages and 3 conditions) and that forced me to be more creative ... 
There is now a new option called `curvesCol` in the `plotSmoothers` function that allows users to specify colors for each curve independently.  You can use this with the latest version of `tradeSeq` from github. 
Still a little work remaining on adding a legend, I'll work on that next.
Best,
