### ISSUE TITLE
pValue = 0

### ISSUE THREAD

**Issue by kmshort** [statOmics/tradeSeq#99]
Hi all,

I'm doing some conditionTests, and some of the pValues come out at 0. What is the best way to treat these?
Are they just so low that they're below the limit of precision that R4 can calculate? Or should they be treated with caution and discarded?

thanks

**Comment by HectorRDB** [comment]
Hi,
Yes it's a problem of very small values. The p-values are computed as `1 - stats::pchisq(waldStat, df = df)`. If you want more non-zero values for very large statistics, you can use instead `stats::pchisq(waldStat, df = df, lower.tail = FALSE, log.p = TRUE)`.

**Comment by fishmatt** [comment]
Hi Hector, 
sorry to re-open this but I just wanted to clarify where I can implement your line of code here as I am having the same issue with a lot of P values coming out as 0. 
I get this when using `startVsEndTest(sce_fitGAM)`. where do i run your solution above?

thanks for this great package, I have been implementing it on bulk RNAseq and am having a lot of success with it alongside slingshot. 

Thanks!

**Comment by fishmatt** [comment]
Hi @HectorRDB 
thanks for your speedy reply. All sorted and working! Ha, you are welcome. - thanks for the appreciation ;)

**Comment by sam-israel** [comment]
> Hi, Yes it's a problem of very small values. The p-values are computed as `1 - stats::pchisq(waldStat, df = df)`. If you want more non-zero values for very large statistics, you can use instead `stats::pchisq(waldStat, df = df, lower.tail = FALSE, log.p = TRUE)`.

I have noticed that using the calculation `stats::pchisq(waldStat, df = df, lower.tail = FALSE), even without `log.p` yields many more non-zero values.

```
> ATres <- ATres %>% mutate(pvalue_precise = stats::pchisq(waldStat, df = df, lower.tail=F) )
>
> sum(ATres$pvalue==0)
[1] 8774
> sum(ATres$pvalue_precise==0)
[1] 1215

> quantile(ATres$pvalue, seq(0,1,0.1))
          0%          10%          20%          30%          40%          50%          60%          70%          80%          90%         100% 
0.000000e+00 0.000000e+00 0.000000e+00 0.000000e+00 0.000000e+00 3.885781e-15 8.221572e-08 5.052108e-04 3.985483e-02 2.998846e-01 9.999733e-01 
> quantile(ATres$pvalue_precise, seq(0,1,0.1))
           0%           10%           20%           30%           40%           50%           60%           70%           80%           90% 
 0.000000e+00 1.270347e-210  4.859423e-93  3.919611e-50  1.151962e-27  3.900121e-15  8.221572e-08  5.052108e-04  3.985483e-02  2.998846e-01 
         100% 
 9.999733e-01 
```
